Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2019-05, with the labels that each got.

#800 [NEW] Admin
  android/app/build.gradle
  android/app/src/main/java/chat/rocket/reactnative/MainApplication.java
  android/settings.gradle
  app/i18n/locales/en.js
  app/index.js
  app/views/AdminPanelView/index.js
  app/views/OAuthView.js
  app/views/SidebarView/index.js
  ios/Podfile
  ios/Podfile.lock
  ios/Pods/Headers/Private/react-native-webview/RNCUIWebView.h
  ios/Pods/Headers/Private/react-native-webview/RNCUIWebViewManager.h
  ios/Pods/Headers/Private/react-native-webview/RNCWKProcessPoolManager.h
  ios/Pods/Headers/Private/react-native-webview/RNCWKWebView.h
  ios/Pods/Headers/Private/react-native-webview/RNCWKWebViewManager.h
  ios/Pods/Headers/Public/react-native-webview/RNCUIWebView.h
  ios/Pods/Headers/Public/react-native-webview/RNCUIWebViewManager.h
  ios/Pods/Headers/Public/react-native-webview/RNCWKProcessPoolManager.h
  ios/Pods/Headers/Public/react-native-webview/RNCWKWebView.h
  ios/Pods/Headers/Public/react-native-webview/RNCWKWebViewManager.h
  ios/Pods/Local Podspecs/react-native-webview.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/react-native-webview/react-native-webview-dummy.m
  ios/Pods/Target Support Files/react-native-webview/react-native-webview-prefix.pch
  ios/Pods/Target Support Files/react-native-webview/react-native-webview.xcconfig
  package.json
  yarn.lock
Labels: 🎉 feature, 👀 needs review

#880 Message render performance
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/actions/index.js
  app/containers/FileModal.js
  app/containers/HeaderButton.js
  app/containers/MessageBox/ReplyPreview.js
  app/containers/MessageBox/UploadModal.js
  app/containers/ReactionsModal.js
  app/containers/message/Attachments.js
  app/containers/message/Audio.js
  app/containers/message/Broadcast.js
  app/containers/message/Content.js
  app/containers/message/Discussion.js
  app/containers/message/Emoji.js
  app/containers/message/Image.js
  app/containers/message/Markdown.js
  app/containers/message/Message.js
  app/containers/message/MessageAvatar.js
  app/containers/message/MessageError.js
  app/containers/message/PhotoModal.js
  app/containers/message/Reactions.js
  app/containers/message/ReactionsModal.js
  app/containers/message/RepliedThread.js
  app/containers/message/Reply.js
  app/containers/message/Thread.js
  app/containers/message/Urls.js
  app/containers/message/User.js
  app/containers/message/Video.js
  app/containers/message/constants.js
  app/containers/message/index.js
  app/containers/message/styles.js
  app/containers/message/utils.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/lib/methods/getCustomEmojis.js
  app/lib/methods/helpers/mergeSubscriptionsRooms.js
  app/lib/methods/helpers/normalizeMessage.js
  app/lib/methods/subscriptions/room.js
  app/lib/realm.js
  app/lib/rocketchat.js
  app/lib/utils.js
  app/reducers/customEmojis.js
  app/reducers/index.js
  app/sagas/rooms.js
  app/sagas/selectServer.js
  app/views/MessagesView/index.js
  app/views/OAuthView.js
  app/views/RoomMembersView/index.js
  app/views/RoomView/Header/RightButtons.js
  app/views/RoomView/List.js
  app/views/RoomView/index.js
  app/views/RoomsListView/index.js
  app/views/SearchMessagesView/index.js
  app/views/ThreadMessagesView/index.js
  ios/RocketChatRN/AppDelegate.m
  package.json
  storybook/stories/Message.js
  yarn.lock
Labels: 🚀 performance, 🚧 wip

#816 add precommit hooks to run: eslint fix, eslint, jest
  .eslintrc.js
  package.json
  yarn.lock
Labels: 👀 needs review, 🚚 chore

#907 [IMPROVEMENT] Add toggle markdown to settings
  app/actions/actionsTypes.js
  app/actions/markdown.js
  app/containers/message/Markdown.js
  app/i18n/locales/de.js
  app/i18n/locales/en.js
  app/i18n/locales/fr.js
  app/i18n/locales/pt-BR.js
  app/i18n/locales/pt-PT.js
  app/i18n/locales/ru.js
  app/i18n/locales/zh-CN.js
  app/lib/rocketchat.js
  app/reducers/index.js
  app/reducers/markdown.js
  app/sagas/init.js
  app/views/RoomView/index.js
  app/views/RoomsListView/index.js
  app/views/SettingsView/index.js
Labels: 👍 improvement

#911 [FIX] Message grouping not re-rendering
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/message/Message.js
  app/containers/message/MessageAvatar.js
  app/containers/message/index.js
Labels: 🐛 bug

#885 [CHORE] Update Current priorities and Features
  README.md
Labels: 📝 docs, 🚚 chore

#915 [CHORE] Android app bundle
  .circleci/config.yml
  android/app/build.gradle
Labels: 👍 improvement, 👷 ci, 🚚 chore

#920 Messagebox typing and buttons refactor
  app/containers/MessageBox/FilesActions.js
  app/containers/MessageBox/LeftButtons.android.js
  app/containers/MessageBox/LeftButtons.ios.js
  app/containers/MessageBox/RightButtons.android.js
  app/containers/MessageBox/RightButtons.ios.js
  app/containers/MessageBox/buttons/AudioButton.js
  app/containers/MessageBox/buttons/BaseButton.js
  app/containers/MessageBox/buttons/CancelEditingButton.js
  app/containers/MessageBox/buttons/FileButton.js
  app/containers/MessageBox/buttons/SendButton.js
  app/containers/MessageBox/buttons/ToggleEmojiButton.js
  app/containers/MessageBox/buttons/index.js
  app/containers/MessageBox/index.js
Labels: 👍 improvement

#924 [IMPROVEMENT] Update user presence endpoint
  app/lib/rocketchat.js
Labels: 👀 needs review, 👍 improvement

#908 [IMPROVEMENT] Share channel
  app/containers/MessageActions.js
  app/containers/MessageBox/index.js
  app/lib/rocketchat.js
  app/views/RoomActionsView/index.js
  e2e/09-roomactions.spec.js
Labels: 👀 needs review, 👍 improvement

#906 [FIX] App crash with backspace on input message
  app/containers/MessageBox/index.js
Labels: 🐛 bug, 👀 needs review

#921 [FIX] Gitlab url hardcoded problem
  app/constants/settings.js
  app/views/LoginSignupView.js
Labels: 👀 needs review, 👍 improvement

#945 [FIX] Crash on message long press
  app/containers/MessageActions.js
Labels: 👍 improvement

#949 [IMPROVEMENT] Open links as push instead of modal
  app/utils/openLink/index.ios.js
Labels: 👍 improvement
