Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2019-06, with the labels that each got.

#937 [FIX] Crashing on app launch
  package.json
  yarn.lock
Labels: ⬆️ update dependencies, 🐛 bug, 🚨 needs changes

#957 [FIX] Stop mention tracking if text is empty.
  app/containers/MessageBox/index.js
Labels: 🐛 bug

#933 [CHORE] Make e2e pass on CircleCI
  .circleci/config.yml
  e2e/03-forgotpassword.spec.js
  e2e/04-createuser.spec.js
  e2e/14-joinpublicroom.spec.js
  e2e/README.md
  e2e/data.js
Labels: ✅ tests, 👷 ci, 📝 docs, 🚚 chore

#962 [CHORE] Bump version to 1.15.0
  android/app/build.gradle
  ios/RocketChatRN/Info.plist
Labels: 🚚 chore

#959 [IMPROVEMENT] Lazy fetch server info
  app/sagas/selectServer.js
Labels: 👍 improvement

#958 [REGRESSION] Get rooms on app restore
  app/views/RoomsListView/index.js
Labels: 🐛 bug, 👀 needs review, 🛠 fix

#963 [CHORE] Use no-JIT JSC
  android/app/build.gradle
  android/build.gradle
  package.json
  yarn.lock
Labels: 🚚 chore, 🛠 fix

#955 [FIX] Profile update
  app/lib/rocketchat.js
  app/views/ProfileView/index.js
Labels: 🛠 fix

#960 [FIX] Change server issue
  app/lib/rocketchat.js
  app/sagas/selectServer.js
  app/views/RoomsListView/Header/Header.android.js
  app/views/RoomsListView/Header/Header.ios.js
  app/views/RoomsListView/Header/index.js
Labels: 🐛 bug, 🛠 fix

#967 [NEW] Directory and Federation
  app/constants/settings.js
  app/containers/Check.js
  app/containers/SearchBox.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/index.js
  app/lib/rocketchat.js
  app/views/DirectoryView/DirectoryItem.js
  app/views/DirectoryView/Options.js
  app/views/DirectoryView/index.js
  app/views/DirectoryView/styles.js
  app/views/NewMessageView.js
  app/views/RoomsListView/Check.js
  app/views/RoomsListView/ListHeader/Directory.js
  app/views/RoomsListView/ListHeader/index.js
  app/views/RoomsListView/ServerDropdown.js
  app/views/RoomsListView/SortDropdown.js
  app/views/RoomsListView/index.js
  app/views/RoomsListView/styles.js
Labels: 🎉 feature

#964 [NEW] In-app notification
  app/actions/actionsTypes.js
  app/actions/notification.js
  app/constants/colors.js
  app/index.js
  app/lib/methods/subscriptions/rooms.js
  app/lib/rocketchat.js
  app/notifications/inApp/index.js
  app/notifications/push/index.js
  app/notifications/push/push.android.js
  app/notifications/push/push.ios.js
  app/reducers/index.js
  app/reducers/notification.js
  app/sagas/state.js
Labels: 🎉 feature

#975 [NEW] Read receipt
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/constants/settings.js
  app/containers/MessageActions.js
  app/containers/message/Message.js
  app/containers/message/ReadReceipt.js
  app/containers/message/index.js
  app/containers/message/styles.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/index.js
  app/lib/methods/helpers/normalizeMessage.js
  app/lib/realm.js
  app/lib/rocketchat.js
  app/views/ReadReceiptView/index.js
  app/views/ReadReceiptView/styles.js
  app/views/RoomView/index.js
  storybook/stories/Message.js
Labels: 🎉 feature

#886 [NEW] Slash commands
  app/containers/MessageBox/CommandPreview.js
  app/containers/MessageBox/index.js
  app/containers/MessageBox/styles.js
  app/lib/methods/getSlashCommands.js
  app/lib/realm.js
  app/lib/rocketchat.js
  e2e/08-room.spec.js
Labels: 🎉 feature

#900 [NEW] Settings view
  __mocks__/reactotron-react-native.js
  app/containers/DisclosureIndicator.js
  app/containers/ListItem.js
  app/containers/Separator.js
  app/i18n/locales/en.js
  app/index.js
  app/utils/deviceInfo.js
  app/views/LanguageView/index.js
  app/views/SettingsView/index.js
  app/views/SettingsView/styles.js
  app/views/SidebarView/index.js
  app/views/Styles.js
  e2e/08-room.spec.js
  e2e/14-setting.spec.js
  e2e/15-joinpublicroom.spec.js
Labels: 👀 needs review, 👍 improvement

#984 [FIX] Cancel ongoing tasks on server change
  app/actions/actionsTypes.js
  app/actions/server.js
  app/lib/methods/getCustomEmojis.js
  app/lib/methods/getPermissions.js
  app/lib/methods/getRoles.js
  app/lib/methods/getSlashCommands.js
  app/lib/methods/subscriptions/rooms.js
  app/lib/rocketchat.js
  app/reducers/server.js
  app/sagas/login.js
  app/sagas/rooms.js
  app/sagas/selectServer.js
  app/views/RoomsListView/index.js
Labels: 🐛 bug, 👀 needs review

#996 [FIX] Broadcast channel is not readonly
  app/views/RoomView/index.js
Labels: 👀 needs review, 🛠 fix

#980 [IMPROVEMENT] Activity indicator on web view OAuth
  app/views/OAuthView.js
Labels: 👀 needs review, 👍 improvement

#1000 [FIX] Join discussion
  app/lib/rocketchat.js
  app/views/RoomView/index.js
Labels: 🐛 bug, 🛠 fix

#974 [BUG] Profile screen gets frozen when submitting invalid current password
  app/utils/info.js
  app/views/ProfileView/index.js
Labels: 🐛 bug, 🛠 fix

#997 [FIX] App hang on "updating"
  app/lib/methods/subscriptions/rooms.js
  app/notifications/push/push.ios.js
Labels: 🛠 fix

#982 [IMPROVEMENT] Share credentials with Rocket.Chat.iOS
  app/constants/userDefaults.js
  app/lib/realm.js
  app/lib/rocketchat.js
  app/sagas/deepLinking.js
  app/sagas/init.js
  app/sagas/login.js
  app/sagas/selectServer.js
  app/views/RoomsListView/ServerDropdown.js
  app/views/RoomsListView/index.js
  app/views/SidebarView/index.js
  ios/RocketChatRN.xcodeproj/project.pbxproj
  ios/RocketChatRN/RocketChatRN.entitlements
  package.json
  yarn.lock
Labels: 👀 needs review, 👍 improvement

#792 [IMPROVEMENT] Hide frequently used emoji tab when empty
  app/containers/EmojiPicker/index.js
Labels: 👀 needs review, 👍 improvement

#793 [IMPROVEMENT] Bigger emoji in emoji only messages
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/message/Markdown.js
  app/containers/message/styles.js
  storybook/stories/Message.js
Labels: 👍 improvement, 🚨 needs changes

#787 Fix empty message if contains only a link
  app/containers/message/Markdown.js
Labels: 🐛 bug, 🚨 needs changes, 🛠 fix

#1017 [IMPROVEMENT] Code of regex empty space on quote
  app/containers/message/Markdown.js
Labels: 👀 needs review, 👍 improvement

#1013 [NEW] Custom fields on signup
  app/views/RegisterView.js
Labels: 🎉 feature, 👀 needs review

#1012 [NEW] Auto-translate
  app/constants/colors.js
  app/constants/settings.js
  app/containers/MessageActions.js
  app/containers/message/index.js
  app/containers/message/utils.js
  app/i18n/locales/en.js
  app/index.js
  app/lib/methods/helpers/normalizeMessage.js
  app/lib/realm.js
  app/lib/rocketchat.js
  app/views/AutoTranslateView/index.js
  app/views/CreateChannelView.js
  app/views/DirectoryView/Options.js
  app/views/LanguageView/index.js
  app/views/RoomActionsView/index.js
  app/views/RoomInfoEditView/SwitchContainer.js
  app/views/RoomView/index.js
  app/views/SettingsView/index.js
Labels: 🎉 feature, 👀 needs review

#1016 [IMPROVEMENT] Use haptics rather than vibration
  android/app/src/main/java/chat/rocket/reactnative/generated/BasePackageList.java
  app/containers/MessageActions.js
  app/utils/vibration.js
  app/views/RoomMembersView/index.js
  app/views/RoomView/index.js
  ios/Podfile.lock
  ios/Pods/Headers/Private/EXHaptics/EXHapticsModule.h
  ios/Pods/Headers/Public/EXHaptics/EXHapticsModule.h
  ios/Pods/Local Podspecs/EXHaptics.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/Target Support Files/EXHaptics/EXHaptics-dummy.m
  ios/Pods/Target Support Files/EXHaptics/EXHaptics-prefix.pch
  ios/Pods/Target Support Files/EXHaptics/EXHaptics.xcconfig
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.release.xcconfig
  package.json
  yarn.lock
Labels: 👍 improvement

#1005 [IMPROVEMENT] Use Rest API for file upload
  android/app/build.gradle
  android/app/src/main/java/chat/rocket/reactnative/MainApplication.java
  android/settings.gradle
  app/containers/MessageBox/Recording.js
  app/lib/methods/sendFileMessage.js
  ios/RocketChatRN.xcodeproj/project.pbxproj
  package.json
  yarn.lock
Labels: 👍 improvement
