Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2019-12, with the labels that each got.

#1435 [FIX] Rooms grouping not working properly
  app/views/RoomsListView/index.js
Labels: 🛠 fix

#1429 [FIX] Share extension doesn't reconnect to previous selected server on Android
  app/lib/database/index.js
  app/lib/methods/sendMessage.js
  app/lib/rocketchat.js
  app/share.js
Labels: 👀 needs review, 🛠 fix

#1438 [FIX] Init local settings on notification tap
  app/actions/actionsTypes.js
  app/actions/index.js
  app/index.js
  app/sagas/init.js
Labels: 👀 needs review, 🛠 fix

#1445 [FIX] Emoji parser not working on Hermes
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/EmojiPicker/EmojiCategory.js
  app/containers/EmojiPicker/index.js
  app/containers/MessageBox/Mentions/MentionEmoji.js
  app/containers/markdown/Emoji.js
  app/containers/markdown/index.js
  app/containers/message/Emoji.js
  app/containers/message/RepliedThread.js
  app/presentation/RoomItem/LastMessage.js
  app/utils/shortnameToUnicode/ascii.js
  app/utils/shortnameToUnicode/emojis.js
  app/utils/shortnameToUnicode/index.js
  app/utils/shortnameToUnicode/shortnameToUnicode.test.js
  app/views/RoomView/Header/Header.js
  index.js
  package.json
  yarn.lock
Labels: 👀 needs review, 🛠 fix

#1446 [NEW] Enable Hermes
  .circleci/config.yml
  android/app/build.gradle
  android/build.gradle
Labels: 👀 needs review, 🚀 performance

#1457 [FIX] Automatic theme repeating
  app/views/ThemeView.js
Labels: 🛠 fix

#1458 [CHORE] Sync Experimental and Official app versions
  android/app/build.gradle
  ios/RocketChatRN/Info.plist
  ios/ShareRocketChatRN/Info.plist
Labels: 🚚 chore

#1459 [DOCS] Update readme
  README.md
Labels: 👀 needs review, 📝 docs

#1469 [FIX] Messages being sent but showing as temp status
  app/lib/methods/sendMessage.js
  app/views/RoomView/index.js
Labels: 👀 needs review, 🛠 fix

#1401 [FIX] Crash while displaying the attached image with “http” in the “File Name” field
  app/lib/utils.js
Labels: 👀 needs review, 🛠 fix

#1425 [IMPROVEMENT] Tap app and server version to copy to clipboard
  app/views/SettingsView/index.js
Labels: 👀 needs review, 👍 improvement

#1448 [NEW] Reply notification
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/chat/rocket/reactnative/CustomPushNotification.java
  android/app/src/main/java/chat/rocket/reactnative/DismissNotification.java
  android/app/src/main/java/chat/rocket/reactnative/Ejson.java
  android/app/src/main/java/chat/rocket/reactnative/ReplyBroadcast.java
  app/notifications/push/push.ios.js
  app/sagas/login.js
  ios/Podfile.lock
  ios/Pods/Local Podspecs/RNUserDefaults.podspec.json
  ios/Pods/Manifest.lock
  ios/RocketChatRN/Info.plist
  package.json
  patches/react-native-notifications+2.0.6.patch
  yarn.lock
Labels: 🎉 feature, 👀 needs review

#1480 [FIX] Incorrect background color login on iPad
  app/views/LoginSignupView.js
Labels: 👀 needs review, 🚸 ux, 🛠 fix

#1481 [FIX] Prevent multiple tap on send (Share Extension)
  app/views/ShareView/index.js
Labels: 👀 needs review, 🛠 fix

#1485 [DOCS] Update Readme
  README.md
Labels: 👀 needs review, 📝 docs
