Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2019-07, with the labels that each got.

#1026 [Chore] [CI] [TESTS] update detox to make ci pass
  package.json
Labels: ✅ tests, 👷 ci, 🚚 chore

#976 [NEW] Room swipe actions: mark as read/unread, hide, fav
  __mocks__/react-native-gesture-handler.js
  app/i18n/locales/en.js
  app/lib/rocketchat.js
  app/presentation/RoomItem/index.js
  app/presentation/RoomItem/styles.js
  app/views/RoomsListView/index.js
Labels: 🎉 feature, 👀 needs review

#1027 [FIX] Android build
  yarn.lock
Labels: ⬆️ update dependencies, 🚚 chore, 🛠 fix

#1029 [CI] Restore cache on CI
  .circleci/config.yml
  ios/Gemfile
  ios/Gemfile.lock
  ios/fastlane/Fastfile
Labels: 👷 ci, 🚀 performance

#1038 [FIX] Append server URL on avatar if necessary
  app/containers/Avatar.js
Labels: 🐛 bug, 🛠 fix

#1040 [i18n] German translation for room swipe actions: mark as read/unread, hide, fav
  app/i18n/locales/de.js
Labels: 🌎 i18n

#1043 [CHORE] Switch to react-native-localize
  __mocks__/react-native-localize.js
  android/app/build.gradle
  android/app/src/main/java/chat/rocket/reactnative/MainApplication.java
  android/settings.gradle
  app/containers/MessageBox/index.js
  app/i18n/index.js
  app/presentation/RoomItem/index.js
  app/utils/room.js
  app/views/RoomsListView/index.js
  ios/Podfile
  ios/Podfile.lock
  ios/Pods/Headers/Private/RNLocalize/RNLocalize.h
  ios/Pods/Headers/Public/RNLocalize/RNLocalize.h
  ios/Pods/Local Podspecs/RNLocalize.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/RNLocalize/RNLocalize-dummy.m
  ios/Pods/Target Support Files/RNLocalize/RNLocalize-prefix.pch
  ios/Pods/Target Support Files/RNLocalize/RNLocalize.xcconfig
  ios/RocketChatRN.xcodeproj/project.pbxproj
  package.json
  yarn.lock
Labels: 🚚 chore

#1056 Load views as needed
  app/index.js
  package.json
  yarn.lock
Labels: 🚀 performance

#1048 [IMPROVEMENT] Change "resend" icon position
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/message/Content.js
  app/containers/message/Message.js
  app/containers/message/MessageError.js
  app/containers/message/User.js
  app/containers/message/index.js
  app/containers/message/styles.js
Labels: 👀 needs review, 👍 improvement

#801 [NEW] Video support
  app/containers/MessageBox/UploadModal.js
  app/containers/MessageBox/index.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  yarn.lock
Labels: 🎉 feature, 👀 needs review

#882 [NEW] File upload
  android/app/build.gradle
  android/app/src/main/java/chat/rocket/reactnative/MainApplication.java
  android/settings.gradle
  app/constants/settings.js
  app/containers/MessageBox/UploadModal.js
  app/containers/MessageBox/index.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  ios/Podfile
  ios/Podfile.lock
  ios/Pods/Headers/Private/react-native-document-picker/RNDocumentPicker.h
  ios/Pods/Headers/Public/react-native-document-picker/RNDocumentPicker.h
  ios/Pods/Local Podspecs/react-native-document-picker.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/react-native-document-picker/react-native-document-picker-dummy.m
  ios/Pods/Target Support Files/react-native-document-picker/react-native-document-picker-prefix.pch
  ios/Pods/Target Support Files/react-native-document-picker/react-native-document-picker.xcconfig
  ios/RocketChatRN.xcodeproj/project.pbxproj
  package.json
  yarn.lock
Labels: 🎉 feature, 👀 needs review

#1065 [IMPROVEMENT] Reusable toast
  app/containers/MessageActions.js
  app/containers/Toast.js
  app/index.js
  app/utils/info.js
  app/views/ProfileView/index.js
  app/views/RoomInfoEditView/index.js
  app/views/RoomMembersView/index.js
  app/views/RoomView/index.js
Labels: 👀 needs review, 👍 improvement

#1066 [FIX] Moment locales
  app/sagas/login.js
  app/utils/moment.js
  app/views/RoomsListView/index.js
Labels: 🛠 fix

#1064 [FIX] Share Extension issues
  app/actions/actionsTypes.js
  app/actions/share.js
  app/containers/HeaderButton.js
  app/containers/MessageBox/index.js
  app/containers/SearchBox.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/lib/ShareNavigation.js
  app/lib/methods/getSettings.js
  app/lib/methods/sendFileMessage.js
  app/lib/methods/sendMessage.js
  app/lib/realm.js
  app/lib/rocketchat.js
  app/presentation/DirectoryItem/index.js
  app/presentation/ServerItem/styles.js
  app/reducers/index.js
  app/reducers/share.js
  app/share.js
  app/views/RoomView/UploadProgress.js
  app/views/RoomView/index.js
  app/views/SelectServerView.js
  app/views/ShareListView/Header.js
  app/views/ShareListView/Header/Header.android.js
  app/views/ShareListView/Header/Header.ios.js
  app/views/ShareListView/Header/index.js
  app/views/ShareListView/index.js
  app/views/ShareListView/styles.js
  app/views/ShareView/index.js
  app/views/Styles.js
  app/views/WithoutServersView.js
  ios/Podfile
  ios/Podfile.lock
  ios/Pods/Headers/Private/react-native-realm-path/RNRealmPath.h
  ios/Pods/Headers/Private/rn-extensions-share/ReactNativeShareExtension.h
  ios/Pods/Headers/Public/react-native-realm-path/RNRealmPath.h
  ios/Pods/Headers/Public/rn-extensions-share/ReactNativeShareExtension.h
  ios/Pods/Local Podspecs/react-native-realm-path.podspec.json
  ios/Pods/Local Podspecs/rn-extensions-share.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/react-native-realm-path/react-native-realm-path-dummy.m
  ios/Pods/Target Support Files/react-native-realm-path/react-native-realm-path-prefix.pch
  ios/Pods/Target Support Files/react-native-realm-path/react-native-realm-path.xcconfig
  ios/Pods/Target Support Files/rn-extensions-share/rn-extensions-share-dummy.m
  ios/Pods/Target Support Files/rn-extensions-share/rn-extensions-share-prefix.pch
  ios/Pods/Target Support Files/rn-extensions-share/rn-extensions-share.xcconfig
  ios/RocketChatRN.xcodeproj/project.pbxproj
  ios/ShareRocketChatRN/Info.plist
  package.json
  yarn.lock
Labels: 👀 needs review, 👍 improvement, 🛠 fix

#1077 [FIX] Empty white list enables all media types upload
  app/containers/MessageBox/UploadModal.js
Labels: 🛠 fix

#1081 [CHORE] Update README
  README.md
Labels: 🚚 chore
