Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2019-09, with the labels that each got.

#1161 [FIX] Patch expo-av crashing with java.lang.IllegalArgumentException: Receiver not registered
  package.json
  patches/expo-av+6.0.0.patch
  yarn.lock
Labels: 👀 needs review, 🛠 fix

#1125 [NEW] Support client certificates for SSL (two-way authentication)
  app/actions/server.js
  app/i18n/locales/en.js
  app/lib/rocketchat.js
  app/sagas/selectServer.js
  app/utils/server.js
  app/views/NewServerView.js
  package.json
  patches/react-native+0.60.4.patch
  yarn.lock
Labels: 🎉 feature, 👀 needs review

#1170 [FIX] Prevent navigation if serverInfo is Undefined
  app/sagas/selectServer.js
  app/views/NewServerView.js
Labels: 👀 needs review, 🛠 fix

#1164 [IMPROVEMENT] Use JoyPixels
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/EmojiPicker/EmojiCategory.js
  app/containers/EmojiPicker/index.js
  app/containers/MessageBox/index.js
  app/containers/markdown/Emoji.js
  app/containers/markdown/index.js
  app/containers/message/Emoji.js
  app/containers/message/RepliedThread.js
  app/presentation/RoomItem/LastMessage.js
  app/views/RoomView/Header/Header.js
  index.js
  package.json
  patches/emoji-toolkit+5.0.4.patch
  yarn.lock
Labels: 👀 needs review, 👍 improvement

#1172 [FIX] Custom OAuth URL
  app/views/LoginSignupView.js
Labels: 🛠 fix

#1175 [FIX] Server URL regex
  app/views/NewServerView.js
Labels: 🛠 fix

#1185 [FIX] Video default resize
  app/containers/FileModal.js
Labels: 👀 needs review, 🛠 fix

#1190 [FIX][Android] Remove unread count
  app/views/RoomView/index.js
Labels: 🛠 fix

#1195 [IMPROVEMENT] Use FastImage to custom emojis
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/EmojiPicker/CustomEmoji.js
  app/containers/markdown/index.js
Labels: 👀 needs review, 👍 improvement

#1197 [FIX] Intended direct mutation state running before initial state gets initiated
  app/views/NotificationPreferencesView/index.js
  app/views/RoomActionsView/index.js
  app/views/RoomMembersView/index.js
  app/views/RoomView/UploadProgress.js
  app/views/ThreadMessagesView/index.js
Labels: 🛠 fix

#1173 [FIX] Delete push token when logout
  app/sagas/login.js
  package.json
  yarn.lock
Labels: 🛠 fix

#1196 [NEW] Jitsi integration
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/assets/index.android.bundle
  android/app/src/main/assets/index.android.bundle.meta
  android/app/src/main/java/chat/rocket/reactnative/MainApplication.java
  android/build.gradle
  android/settings.gradle
  app/constants/settings.js
  app/containers/message/CallButton.js
  app/containers/message/Message.js
  app/containers/message/index.js
  app/containers/message/utils.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/lib/database/index.js
  app/lib/database/model/Subscription.js
  app/lib/database/model/migrations.js
  app/lib/database/schema/app.js
  app/lib/methods/callJitsi.js
  app/lib/methods/helpers/mergeSubscriptionsRooms.js
  app/lib/methods/subscriptions/rooms.js
  app/lib/rocketchat.js
  app/presentation/RoomItem/LastMessage.js
  app/views/RoomActionsView/index.js
  app/views/RoomView/index.js
  e2e/09-roomactions.spec.js
  ios/Podfile.lock
  ios/Pods/Headers/Private/react-native-background-timer/RNBackgroundTimer.h
  ios/Pods/Headers/Public/react-native-background-timer/RNBackgroundTimer.h
  ios/Pods/Local Podspecs/react-native-background-timer.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/react-native-background-timer/react-native-background-timer-dummy.m
  ios/Pods/Target Support Files/react-native-background-timer/react-native-background-timer-prefix.pch
  ios/Pods/Target Support Files/react-native-background-timer/react-native-background-timer.xcconfig
  ios/RocketChatRN.xcodeproj/project.pbxproj
  ios/RocketChatRN/AppDelegate.m
  ios/RocketChatRN/Info.plist
  package.json
  react-native.config.js
  yarn.lock
Labels: 🎉 feature, 👀 needs review

#1206 [IMPROVEMENT] Use Reanimated's Transitions instead of LayoutAnimation
  app/animations/collapse.js
  app/animations/fade.js
  app/index.js
  app/share.js
  app/utils/layoutAnimation.js
  app/views/LoginView.js
  app/views/NewServerView.js
  app/views/RoomView/List.js
  app/views/RoomView/index.js
  app/views/RoomsListView/index.js
  app/views/SelectedUsersView.js
  app/views/ShareListView/Header/Header.ios.js
  app/views/ShareListView/index.js
  app/views/SidebarView/index.js
  app/views/Styles.js
Labels: 👍 improvement

#1218 [FIX] Link WatermelonDB on share extension
  ios/RocketChatRN.xcodeproj/project.pbxproj
Labels: 👀 needs review, 🛠 fix

#1226 [FIX] Unnecessary rooms list render on focus
  app/views/RoomsListView/index.js
Labels: 🚀 performance, 🛠 fix

#1215 [REGRESSION] Share this app
  app/views/SettingsView/index.js
Labels: 👀 needs review, 🛠 fix

#1229 [FIX] Unify upload check
  app/containers/MessageBox/Recording.js
  app/containers/MessageBox/UploadModal.js
  app/containers/MessageBox/index.js
  app/lib/methods/sendFileMessage.js
  app/utils/media.js
  app/views/ShareListView/index.js
Labels: 🛠 fix

#1212 [CHORE] Use React Fragment shorthand
  app/containers/MessageBox/RightButtons.android.js
  app/containers/message/Audio.js
  app/containers/message/Broadcast.js
  app/containers/message/Discussion.js
  app/containers/message/Message.js
  app/containers/message/Urls.js
  app/containers/message/Video.js
  app/index.js
  app/notifications/inApp/index.js
  app/presentation/RoomItem/Actions.js
  app/views/AuthLoadingView.js
  app/views/AuthenticationWebView.js
  app/views/DirectoryView/Options.js
  app/views/DirectoryView/index.js
  app/views/RoomInfoView/index.js
  app/views/RoomView/index.js
  app/views/RoomsListView/ListHeader/index.js
  app/views/RoomsListView/SortDropdown.js
  app/views/ShareListView/index.js
  app/views/SidebarView/index.js
Labels: 👀 needs review, 🚚 chore

#1232 [FIX] Cancel upload and check failed upload
  app/lib/methods/sendFileMessage.js
  app/views/RoomView/UploadProgress.js
Labels: 👀 needs review, 🛠 fix

#1233 [FIX] Slash commands not cleaning is typing and not using state
  app/containers/MessageBox/index.js
Labels: 👀 needs review, 🛠 fix

#1234 [FIX] Dispatch roomsRequest on app foreground event even if not connected
  app/views/RoomsListView/index.js
Labels: 👀 needs review, 🛠 fix

#1235 [CHORE] react-native-jitsi-meet update
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/chat/rocket/reactnative/MainApplication.java
  android/settings.gradle
  app/index.js
  app/lib/methods/callJitsi.js
  app/views/JitsiMeetView.js
  app/views/RoomActionsView/index.js
  app/views/RoomView/index.js
  ios/Podfile.lock
  ios/Pods/Headers/Private/react-native-jitsi-meet/RNJitsiMeetView.h
  ios/Pods/Headers/Private/react-native-jitsi-meet/RNJitsiMeetViewManager.h
  ios/Pods/Headers/Public/react-native-jitsi-meet/RNJitsiMeetView.h
  ios/Pods/Headers/Public/react-native-jitsi-meet/RNJitsiMeetViewManager.h
  ios/Pods/Local Podspecs/react-native-jitsi-meet.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-frameworks.sh
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/react-native-jitsi-meet/react-native-jitsi-meet-dummy.m
  ios/Pods/Target Support Files/react-native-jitsi-meet/react-native-jitsi-meet-prefix.pch
  ios/Pods/Target Support Files/react-native-jitsi-meet/react-native-jitsi-meet.xcconfig
  ios/RocketChatRN.xcodeproj/project.pbxproj
  ios/RocketChatRN/AppDelegate.m
  package.json
  patches/react-native-jitsi-meet+2.0.0.patch
  patches/react-native-orientation-locker+1.1.6.patch
  react-native.config.js
  yarn.lock
Labels: 👀 needs review, 🚚 chore

#1223 [FIX] Regex on run slash command
  app/containers/MessageBox/index.js
Labels: 👀 needs review, 🛠 fix

#1238 [FIX] Try/catch JSON.parse XHR response
  app/lib/methods/sendFileMessage.js
Labels: 👀 needs review, 🛠 fix

#1241 [FIX] Change messagebox icon immediate on change text
  app/containers/MessageBox/index.js
Labels: 👀 needs review, 🛠 fix

#1240 [FIX] Update last open on message stream received
  app/lib/methods/subscriptions/room.js
Labels: 👀 needs review, 🛠 fix

#1239 [FIX] Remove animation from RoomsListView.willFocus
  app/views/RoomsListView/index.js
Labels: 👀 needs review, 🛠 fix

#1214 [FIX] Delete message on thread
  app/containers/MessageActions.js
  app/containers/message/Thread.js
Labels: 👀 needs review, 🛠 fix

#1243 [FIX] Jest
  __tests__/__snapshots__/Storyshots.test.js.snap
Labels: 👷 ci, 🛠 fix

#1162 [FIX] Avatar shown when useRealName is activated
  app/presentation/RoomItem/index.js
  app/views/RoomsListView/index.js
Labels: 👀 needs review, 🛠 fix

#1244 [CHORE] Add security doc
  SECURITY.md
Labels: 📝 docs

#1246 [CHORE] Update react-native-reanimated to 1.3.0
  app/views/RoomsListView/index.js
  ios/Podfile.lock
  ios/Pods/Headers/Private/RNReanimated/REACallFuncNode.h
  ios/Pods/Headers/Private/RNReanimated/REAFunctionNode.h
  ios/Pods/Headers/Private/RNReanimated/REAParamNode.h
  ios/Pods/Headers/Public/RNReanimated/REACallFuncNode.h
  ios/Pods/Headers/Public/RNReanimated/REAFunctionNode.h
  ios/Pods/Headers/Public/RNReanimated/REAParamNode.h
  ios/Pods/Local Podspecs/RNReanimated.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  package.json
  yarn.lock
Labels: 👀 needs review, 🚚 chore

#1245 [FIX] Run credentials migration only once
  app/sagas/init.js
Labels: 👀 needs review, 🛠 fix

#1252 [FIX] Messagebox onChangeText issues
  app/containers/EmojiPicker/CustomEmoji.js
  app/containers/MessageBox/index.js
Labels: 👀 needs review, 🛠 fix

#1255 [FIX] Room subscription issues
  app/lib/methods/subscriptions/room.js
  app/views/RoomView/index.js
  app/views/RoomsListView/index.js
Labels: 👀 needs review, 🛠 fix
