Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2019-08, with the labels that each got.

#1088 [RELEASE] Merge beta into master
  app/views/ShareListView/index.js
  app/views/ShareView/index.js
Labels: 💎 release

#1093 [NEW] Custom OAuth
  app/lib/rocketchat.js
  app/reducers/login.js
  app/views/LoginSignupView.js
Labels: 🎉 feature

#1071 [IMPROVEMENT] Use autoFocus rather than timeout + focus
  app/views/CreateChannelView.js
  app/views/ForgotPasswordView.js
  app/views/LoginView.js
  app/views/NewServerView.js
  app/views/RegisterView.js
  app/views/RoomsListView/Header/Header.android.js
  app/views/RoomsListView/Header/index.js
  app/views/SearchMessagesView/index.js
  app/views/SetUsernameView.js
Labels: 👀 needs review, 👍 improvement

#1109 [FEATURE] Share app
  app/constants/links.js
  app/views/SettingsView/index.js
Labels: 🎉 feature

#1117 [IMPROVEMENT] Hide "Forgot password" by server "Accounts_PasswordReset" property
  app/constants/settings.js
  app/views/LoginView.js
Labels: 👀 needs review, 👍 improvement

#1108 [NEW] SAML authentication support
  app/index.js
  app/lib/rocketchat.js
  app/views/AuthenticationWebView.js
  app/views/LoginSignupView.js
Labels: 🎉 feature

#1116 [NEW] CAS authentication
  app/constants/settings.js
  app/lib/rocketchat.js
  app/views/AuthenticationWebView.js
  app/views/LoginSignupView.js
Labels: 🎉 feature, 👀 needs review

#1124 [FIX] Remove console on production builds
  .babelrc
  android/gradle.properties
  app/lib/createStore.js
  babel.config.js
  index.js
  package.json
  patches/react-native-markdown-renderer+3.2.8.patch
  yarn.lock
Labels: 🐛 bug

#1131 [FIX] Handle disconnect and reconnect properly
  app/lib/methods/subscriptions/room.js
  app/lib/methods/subscriptions/rooms.js
  package.json
  patches/react-native+0.60.4.patch
  yarn.lock
Labels: 🛠 fix

#1134 [DOCS] Update README.md
  README.md
Labels: 📝 docs

#1097 [IMPROVEMENT] Tap on avatar/username/channel to show info
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/message/Content.js
  app/containers/message/Markdown.js
  app/containers/message/MessageAvatar.js
  app/containers/message/index.js
  app/lib/rocketchat.js
  app/views/RoomActionsView/index.js
  app/views/RoomInfoView/index.js
  app/views/RoomView/index.js
  yarn.lock
Labels: 👀 needs review, 👍 improvement

#1083 [NEW] Unread count on header back button
  app/views/RoomView/Header/Header.js
  app/views/RoomView/index.js
  app/views/RoomView/styles.js
Labels: 🎉 feature, 🚨 needs changes

#1140 [IMPROVEMENT] Checks if custom OAuth button should be shown
  app/lib/rocketchat.js
Labels: 👍 improvement

#1105 [IMPROVEMENT] Notification Preference
  app/i18n/locales/en.js
  app/index.js
  app/lib/methods/helpers/mergeSubscriptionsRooms.js
  app/lib/realm.js
  app/views/NotificationPreferencesView/index.js
  app/views/NotificationPreferencesView/styles.js
  app/views/RoomActionsView/index.js
  app/views/RoomInfoView/index.js
  e2e/09-roomactions.spec.js
Labels: 👍 improvement, 🚨 needs changes

#1165 [FIX] Fix calls to bugsnag.notify
  app/containers/MessageActions.js
  app/containers/MessageBox/index.js
  app/lib/methods/getSlashCommands.js
  app/lib/methods/sendFileMessage.js
  app/presentation/ServerItem/index.js
  app/views/NotificationPreferencesView/index.js
  app/views/RoomInfoView/index.js
Labels: 👀 needs review, 🛠 fix

#1163 [FIX] Block code on thread preview
  app/containers/message/Content.js
Labels: 👀 needs review, 🛠 fix

#1168 [FIX] Bugsnag notify only accept Error
  app/utils/log.js
Labels: 👀 needs review, 🛠 fix
