Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2019-10, with the labels that each got.

#1266 [FIX] Select user from native credentials
  app/lib/rocketchat.js
  app/sagas/selectServer.js
Labels: 👍 improvement, 🛠 fix

#1271 [FIX] Some issues on preview message
  app/containers/markdown/AtMention.js
  app/containers/markdown/Hashtag.js
  app/containers/markdown/Link.js
  app/containers/markdown/index.js
Labels: 👀 needs review, 🛠 fix

#1273 [FIX] Audio player track and thumb not rendering on Android
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/message/Audio.js
  ios/Podfile.lock
  ios/Pods/Headers/Private/react-native-slider/RNCSlider.h
  ios/Pods/Headers/Private/react-native-slider/RNCSliderManager.h
  ios/Pods/Headers/Public/react-native-slider/RNCSlider.h
  ios/Pods/Headers/Public/react-native-slider/RNCSliderManager.h
  ios/Pods/Local Podspecs/react-native-slider.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/react-native-slider/react-native-slider-dummy.m
  ios/Pods/Target Support Files/react-native-slider/react-native-slider-prefix.pch
  ios/Pods/Target Support Files/react-native-slider/react-native-slider.xcconfig
  ios/RocketChatRN/Images.xcassets/Icons/audio_thumb.imageset/Contents.json
  ios/RocketChatRN/Images.xcassets/Icons/audio_thumb.imageset/audio_thumb.png
  ios/RocketChatRN/Images.xcassets/Icons/audio_thumb.imageset/audio_thumb@2x.png
  ios/RocketChatRN/Images.xcassets/Icons/audio_thumb.imageset/audio_thumb@3x.png
  package.json
  yarn.lock
Labels: 🛠 fix

#1272 [FIX] Record audio message throws exception when FileSystem.getInfoAsync is called
  app/containers/MessageBox/Recording.js
Labels: 👀 needs review, 🛠 fix

#1277 [FIX] Watermelon batches
  app/containers/EmojiPicker/index.js
  app/containers/MessageErrorActions.js
  app/containers/message/Message.js
  app/containers/message/RepliedThread.js
  app/lib/methods/readMessages.js
  app/lib/methods/sendMessage.js
  app/lib/methods/subscriptions/room.js
  app/lib/methods/subscriptions/rooms.js
  app/lib/rocketchat.js
  app/views/RoomView/index.js
  app/views/ShareListView/index.js
Labels: 🚧 wip, 🛠 fix

#1285 Bump version to 1.20.1
  android/app/build.gradle
  ios/RocketChatRN/Info.plist
  ios/ShareRocketChatRN/Info.plist
Labels: 🚚 chore

#1284 [CHORE] Remove memoize-one
  package.json
  yarn.lock
Labels: 🚚 chore

#1291 [FIX] End Jitsi call on unmount
  app/views/JitsiMeetView.js
Labels: 👀 needs review, 🛠 fix

#1310 [FIX] Allow self-signed certificates
  android/app/src/debug/AndroidManifest.xml
  android/app/src/debug/res/xml/react_native_config.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/xml/network_security_config.xml
Labels: 🛠 fix

#1318 [FIX] Set User-Agent
  app/lib/methods/getSettings.js
  app/lib/methods/sendFileMessage.js
  app/lib/rocketchat.js
  app/utils/fetch.js
  patches/@rocket.chat+sdk+1.0.0-alpha.31.patch
Labels: 👀 needs review, 🛠 fix

#1322 [FIX] Server with subpath
  app/lib/database/index.js
Labels: 🛠 fix

#1320 [FIX] Server with backslash
  app/views/NewServerView.js
Labels: 👀 needs review, 🛠 fix

#1299 [FIX] Serverdrop not closing after changing screens
  app/views/RoomsListView/index.js
Labels: 👀 needs review, 🛠 fix

#1319 [FIX] Invalid version
  app/lib/methods/getSettings.js
  app/lib/rocketchat.js
  app/sagas/selectServer.js
Labels: 👀 needs review, 🛠 fix

#1306 [IMPROVEMENT] Respect "Hide counter" preference
  app/lib/database/model/Subscription.js
  app/lib/database/model/migrations.js
  app/lib/database/schema/app.js
  app/presentation/RoomItem/index.js
  app/views/RoomsListView/index.js
Labels: 👀 needs review, 👍 improvement

#1309 [FIX] Pass isFocused as a function to Messagebox
  app/containers/MessageBox/index.js
  app/views/RoomView/index.js
Labels: 👀 needs review, 🛠 fix

#1290 [CHORE] Remove icons folder
  icons/20x20/at.svg
  icons/20x20/image.svg
  icons/20x20/location.svg
  icons/20x20/video.svg
  icons/20x20/volume.svg
Labels: 🚚 chore

#1336 [FIX] Unnecessary rerender on RoomItem when status is undefined
  app/presentation/RoomItem/index.js
Labels: 👀 needs review, 🛠 fix

#1337 [UPDATE DEPS] react-navigation and react-navigation-stack
  package.json
  yarn.lock
Labels: ⬆️ update dependencies, 👀 needs review

#1339 [FIX] Avatars not loading on share extension when Accounts_AvatarBlockUnauthenticatedAccess is enabled
  app/views/ShareListView/index.js
Labels: 👀 needs review, 🛠 fix

#1340 Bump version to 1.20.2
  android/app/build.gradle
  ios/RocketChatRN/Info.plist
  ios/ShareRocketChatRN/Info.plist
Labels: 💎 release

#1341 [FIX] Remove some unnecessary re-renders on Messagebox
  app/containers/MessageBox/CommandPreview.js
  app/containers/MessageBox/CommandsPreview/Item.js
  app/containers/MessageBox/CommandsPreview/index.js
  app/containers/MessageBox/Context.js
  app/containers/MessageBox/Mentions/FixedMentionItem.js
  app/containers/MessageBox/Mentions/MentionEmoji.js
  app/containers/MessageBox/Mentions/MentionItem.js
  app/containers/MessageBox/Mentions/index.js
  app/containers/MessageBox/ReplyPreview.js
  app/containers/MessageBox/constants.js
  app/containers/MessageBox/index.js
Labels: 👀 needs review, 🚀 performance, 🛠 fix

#1344 [IMPROVEMENT] Save last message as message when subscription changes
  app/lib/methods/subscriptions/rooms.js
  app/sagas/rooms.js
Labels: 👀 needs review, 👍 improvement

#1345 [UPDATE DEPS] Update RN to 0.61.3
  android/app/_BUCK
  app/lib/methods/subscriptions/rooms.js
  app/notifications/inApp/index.js
  app/views/DirectoryView/Options.js
  app/views/NewServerView.js
  app/views/RoomsListView/ServerDropdown.js
  app/views/RoomsListView/SortDropdown.js
  ios/Podfile.lock
  ios/Pods/Local Podspecs/FBLazyVector.podspec.json
  ios/Pods/Local Podspecs/FBReactNativeSpec.podspec.json
  ios/Pods/Local Podspecs/RCTRequired.podspec.json
  ios/Pods/Local Podspecs/RCTTypeSafety.podspec.json
  ios/Pods/Local Podspecs/React-Core.podspec.json
  ios/Pods/Local Podspecs/React-CoreModules.podspec.json
  ios/Pods/Local Podspecs/React-RCTActionSheet.podspec.json
  ios/Pods/Local Podspecs/React-RCTAnimation.podspec.json
  ios/Pods/Local Podspecs/React-RCTBlob.podspec.json
  ios/Pods/Local Podspecs/React-RCTImage.podspec.json
  ios/Pods/Local Podspecs/React-RCTLinking.podspec.json
  ios/Pods/Local Podspecs/React-RCTNetwork.podspec.json
  ios/Pods/Local Podspecs/React-RCTSettings.podspec.json
  ios/Pods/Local Podspecs/React-RCTText.podspec.json
  ios/Pods/Local Podspecs/React-RCTVibration.podspec.json
  ios/Pods/Local Podspecs/React-cxxreact.podspec.json
  ios/Pods/Local Podspecs/React-jsi.podspec.json
  ios/Pods/Local Podspecs/React-jsiexecutor.podspec.json
  ios/Pods/Local Podspecs/React-jsinspector.podspec.json
  ios/Pods/Local Podspecs/React.podspec.json
  ios/Pods/Local Podspecs/ReactCommon.podspec.json
  ios/Pods/Local Podspecs/yoga.podspec.json
  ios/Pods/Manifest.lock
  package.json
  patches/react-native+0.61.3.patch
  yarn.lock
Labels: ⬆️ update dependencies, 👀 needs review

#1352 [CHORE] Remove react-native-scrollable-tab-view fork
  package.json
  yarn.lock
Labels: ⬆️ update dependencies, 👀 needs review
