Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2019-11, with the labels that each got.

#1360 [FIX] URL preview
  app/lib/methods/subscriptions/rooms.js
Labels: 👀 needs review, 🛠 fix

#1361 [REGRESSION] Decrease list view memory size
  app/views/RoomView/List.js
Labels: 👀 needs review, 🚀 performance, 🛠 fix

#1350 [FIX] Paste
  .eslintrc.js
  app/index.js
Labels: 👀 needs review, 🛠 fix

#1365 [CHORE] Update gems
  .circleci/config.yml
  ios/Gemfile.lock
Labels: ⬆️ update dependencies, 👷 ci, 🚚 chore

#1366 Bump version to 1.20.3
  android/app/build.gradle
  ios/RocketChatRN/Info.plist
  ios/ShareRocketChatRN/Info.plist
Labels: 💎 release

#1368 [FIX] Use Ruby 2.4 on TestFlight upload
  .circleci/config.yml
Labels: 👷 ci, 🛠 fix

#1372 [FIX] Parse image URL only if it's not empty
  app/lib/methods/helpers/parseUrls.js
Labels: 👀 needs review, 🛠 fix

#1373 [FIX] Load messages issues
  app/lib/methods/subscriptions/room.js
  app/lib/methods/subscriptions/rooms.js
  app/sagas/rooms.js
  app/views/RoomView/List.js
  app/views/RoomView/index.js
Labels: 👀 needs review, 🚀 performance, 🛠 fix

#1381 [FIX] Crowd login
  app/lib/rocketchat.js
Labels: 👀 needs review, 🛠 fix

#1363 [FIX] Clicking user avatar in thread previews crashes app
  app/views/ThreadMessagesView/index.js
Labels: 🛠 fix

#1383 [FIX] ProfileView input navigation error when custom fields aren't set
  app/views/ProfileView/index.js
Labels: 👀 needs review, 🛠 fix

#1382 [FIX] Batch server deletion on logout
  app/lib/rocketchat.js
  app/sagas/login.js
Labels: 👀 needs review, 🛠 fix

#1395 [FIX] Crash when open thread
  app/views/RoomView/Header/RightButtons.js
Labels: 👀 needs review, 🛠 fix

#1362 [FIX] CAS building wrong URL
  app/views/LoginSignupView.js
Labels: 🛠 fix

#1399 [FIX] Delete messages
  app/lib/methods/updateMessages.js
Labels: 👀 needs review, 🛠 fix

#1400 [FIX] In-app notification showing wrong content on channels
  app/notifications/inApp/index.js
Labels: 👀 needs review, 🛠 fix

#1402 [FIX] Prevent server with whitespace
  app/views/NewServerView.js
Labels: 👀 needs review, 🛠 fix

#1403 [IMPROVEMENT] Keyboard and content type on login
  app/views/LoginView.js
  app/views/NewServerView.js
Labels: 👀 needs review, 👍 improvement

#1410 [FIX] Messages stop loading
  app/views/RoomView/List.js
  app/views/RoomView/index.js
Labels: 👀 needs review, 🛠 fix

#1418 [IMPROVEMENT] Authentication via deep linking
  app/actions/login.js
  app/lib/rocketchat.js
  app/sagas/deepLinking.js
  app/sagas/login.js
  app/sagas/selectServer.js
Labels: 👀 needs review, 👍 improvement

#1422 [IMPROVEMENT] Markdown performance when identifying emoji only content
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/markdown/index.js
Labels: 👀 needs review, 👍 improvement

#1423 [FIX] BackHandler remove random failing on development
  app/views/RoomsListView/index.js
Labels: 👀 needs review, 🛠 fix

#1424 Bump version to 1.25.0
  android/app/build.gradle
  ios/RocketChatRN/Info.plist
  ios/ShareRocketChatRN/Info.plist
Labels: 👀 needs review, 💎 release
