Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2020-08, with the labels that each got.

#2370 [IMPROVEMENT] Use parsed EJSON info on load notification
  android/app/src/main/java/chat/rocket/reactnative/CustomPushNotification.java
  android/app/src/main/java/chat/rocket/reactnative/LoadNotification.java
Labels: 👀 needs review, 👍 improvement

#2376 [FIX] WorkspaceView not looking for the correct image path
  app/views/WorkspaceView/index.js
Labels: 👀 needs review, 🛠 fix

#2375 [FIX] Android targeting wrong SDK version
  android/build.gradle
Labels: 👀 needs review, 🛠 fix

#2374 [FIX] Mentions crashing without username
  app/containers/markdown/AtMention.js
Labels: 👀 needs review, 🛠 fix

#2373 [FIX] Missing delete icon on MessageErrorActions
  app/containers/MessageErrorActions.js
Labels: 👀 needs review, 🛠 fix

#2372 [FIX] Quote not working on Group DM
  app/lib/rocketchat.js
Labels: 👀 needs review, 🛠 fix

#2379 [DOCS] Add Whitelabel
  README.md
Labels: 📝 docs

#2390 [CHORE] Improve ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: 🚚 chore

#2400 [CHORE] Add to Google Play Internal track instead of alpha
  .circleci/config.yml
  android/fastlane/Fastfile
Labels: 👀 needs review, 👷 ci, 🚚 chore

#2405 [CHORE] Remove Google Services files from repo
  .circleci/config.yml
  android/app/google-services.prod.json
  ios/GoogleService-Info.prod.plist
Labels: 👀 needs review, 👷 ci, 🚚 chore

#2408 [FIX] REST for method calls not raising errors
  app/lib/rocketchat.js
Labels: 🐛 bug, 👀 needs review

#2413 [FIX] SharedPreferences data migration
  android/app/src/main/java/chat/rocket/reactnative/MainActivity.java
Labels: 👀 needs review, 🛠 fix

#2414 [IMPROVEMENT] Move Directory to header
  app/views/RoomsListView/ListHeader/Directory.js
  app/views/RoomsListView/ListHeader/index.js
  app/views/RoomsListView/index.js
  app/views/RoomsListView/styles.js
Labels: 👀 needs review, 👍 improvement, 🚸 ux

#2415 [FIX] Android crashing on receive a notification
  android/app/src/main/java/chat/rocket/reactnative/Ejson.java
Labels: 👀 needs review, 🛠 fix

#2429 [FIX] Rooms not opening again
  app/lib/methods/subscriptions/room.js
Labels: 👀 needs review, 🛠 fix

#2377 [FIX] Logout from custom oauth
  app/containers/MessageActions/index.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/lib/database/model/User.js
  app/lib/database/model/serversMigrations.js
  app/lib/database/schema/servers.js
  app/lib/rocketchat.js
  app/sagas/login.js
  app/utils/info.js
  app/views/NewServerView.js
  app/views/RoomActionsView/index.js
  app/views/RoomMembersView/index.js
  app/views/RoomsListView/ServerDropdown.js
  app/views/RoomsListView/index.js
  app/views/SettingsView/index.js
  ios/Podfile.lock
  ios/Pods/Headers/Private/react-native-cookies/RNCookieManagerIOS.h
  ios/Pods/Headers/Public/react-native-cookies/RNCookieManagerIOS.h
  ios/Pods/Local Podspecs/react-native-cookies.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/Target Support Files/Pods-NotificationService/Pods-NotificationService.debug.xcconfig
  ios/Pods/Target Support Files/Pods-NotificationService/Pods-NotificationService.release.xcconfig
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/react-native-cookies/react-native-cookies-dummy.m
  ios/Pods/Target Support Files/react-native-cookies/react-native-cookies-prefix.pch
  ios/Pods/Target Support Files/react-native-cookies/react-native-cookies.debug.xcconfig
  ios/Pods/Target Support Files/react-native-cookies/react-native-cookies.release.xcconfig
  package.json
  yarn.lock
Labels: 👀 needs review, 🛠 fix

#2409 [FIX] Wrong date and time shown in file section
  app/views/MessagesView/index.js
Labels: 🐛 bug, 🚨 needs changes

#2436 [FIX] Crashlytics reportError not working after #2171
  app/utils/log/index.js
Labels: 👀 needs review, 🛠 fix

#2435 [FIX] Logout from custom oauth when using password
  app/lib/rocketchat.js
Labels: 👀 needs review, 🛠 fix

#2426 [IMPROVEMENT] Move toggle and inquiry to Enterprise Edition license
  app/ee/LICENSE
  app/ee/README.md
  app/ee/omnichannel/actions/inquiry.js
  app/ee/omnichannel/containers/OmnichannelStatus.js
  app/ee/omnichannel/lib/index.js
  app/ee/omnichannel/lib/subscriptions/inquiry.js
  app/ee/omnichannel/reducers/inquiry.js
  app/ee/omnichannel/sagas/inquiry.js
  app/ee/omnichannel/selectors/inquiry.js
  app/ee/omnichannel/views/QueueListView.js
  app/lib/rocketchat.js
  app/reducers/index.js
  app/sagas/index.js
  app/sagas/login.js
  app/sagas/selectServer.js
  app/stacks/InsideStack.js
  app/stacks/MasterDetailStack/index.js
  app/views/RoomView/index.js
  app/views/RoomsListView/ListHeader/index.js
  app/views/RoomsListView/index.js
Labels: 👀 needs review, 👍 improvement

#2439 [CHORE] App Group path as a iOS constant
  app/lib/database/index.js
  app/utils/appGroup.js
  ios/AppGroup/AppGroup.m
  ios/AppGroup/AppGroup.swift
  ios/Podfile.lock
  ios/Pods/Headers/Private/rn-fetch-blob/IOS7Polyfill.h
  ios/Pods/Headers/Private/rn-fetch-blob/RNFetchBlob.h
  ios/Pods/Headers/Private/rn-fetch-blob/RNFetchBlobConst.h
  ios/Pods/Headers/Private/rn-fetch-blob/RNFetchBlobFS.h
  ios/Pods/Headers/Private/rn-fetch-blob/RNFetchBlobNetwork.h
  ios/Pods/Headers/Private/rn-fetch-blob/RNFetchBlobProgress.h
  ios/Pods/Headers/Private/rn-fetch-blob/RNFetchBlobReqBuilder.h
  ios/Pods/Headers/Private/rn-fetch-blob/RNFetchBlobRequest.h
  ios/Pods/Headers/Public/rn-fetch-blob/IOS7Polyfill.h
  ios/Pods/Headers/Public/rn-fetch-blob/RNFetchBlob.h
  ios/Pods/Headers/Public/rn-fetch-blob/RNFetchBlobConst.h
  ios/Pods/Headers/Public/rn-fetch-blob/RNFetchBlobFS.h
  ios/Pods/Headers/Public/rn-fetch-blob/RNFetchBlobNetwork.h
  ios/Pods/Headers/Public/rn-fetch-blob/RNFetchBlobProgress.h
  ios/Pods/Headers/Public/rn-fetch-blob/RNFetchBlobReqBuilder.h
  ios/Pods/Headers/Public/rn-fetch-blob/RNFetchBlobRequest.h
  ios/Pods/Local Podspecs/rn-fetch-blob.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/Target Support Files/Pods-NotificationService/Pods-NotificationService-resources.sh
  ios/Pods/Target Support Files/Pods-NotificationService/Pods-NotificationService.debug.xcconfig
  ios/Pods/Target Support Files/Pods-NotificationService/Pods-NotificationService.release.xcconfig
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/rn-fetch-blob/rn-fetch-blob-dummy.m
  ios/Pods/Target Support Files/rn-fetch-blob/rn-fetch-blob-prefix.pch
  ios/Pods/Target Support Files/rn-fetch-blob/rn-fetch-blob.debug.xcconfig
  ios/Pods/Target Support Files/rn-fetch-blob/rn-fetch-blob.release.xcconfig
  ios/RocketChatRN.xcodeproj/project.pbxproj
  package.json
  yarn.lock
Labels: 👀 needs review, 🚚 chore

#2440 [CHORE] Use official repository to Rocket.Chat sdk
  package.json
  patches/@rocket.chat+sdk+1.0.0-dj.15.patch
  yarn.lock
Labels: 👀 needs review, 🚚 chore
