Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2020-12, with the labels that each got.

#2664 [FIX] Initial users' status is not fetched
  app/presentation/RoomItem/index.js
Labels: 👀 needs review, 🛠 fix

#2683 [CHORE] Force normalized params for 2FA
  app/lib/rocketchat.js
Labels: 👀 needs review, 🚚 chore

#2676 [FIX] Thread message flickering while thread parent isn't found
  app/containers/message/index.js
Labels: 👀 needs review, 🛠 fix

#2675 [FIX] Light theme not working on Android with Dark Theme set
  android/app/src/main/res/values/styles.xml
Labels: 👀 needs review, 🛠 fix

#2514 [FIX] App not prompting join code for password protected channels
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/lib/rocketchat.js
  app/views/DirectoryView/index.js
  app/views/RoomView/JoinCode.js
  app/views/RoomView/index.js
  e2e/data.js
  e2e/data/data.cloud.js
  e2e/data/data.docker.js
  e2e/helpers/data_setup.js
  e2e/tests/assorted/08-joinprotectedroom.spec.js
Labels: 🛠 fix

#2537 [IMPROVEMENT] i18n Adding Arabic Translation
  app/i18n/index.js
  app/i18n/locales/ar.js
Labels: 🌎 i18n, 🕵️ needs investigation, 🚨 needs changes

#2553 [IMPROVEMENT] Add username on status messages
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/message/Content.js
  app/containers/message/Message.js
  app/containers/message/User.js
  app/containers/message/styles.js
  app/containers/message/utils.js
  app/i18n/locales/en.js
  app/i18n/locales/es-ES.js
  app/i18n/locales/fr.js
  app/i18n/locales/nl.js
  app/i18n/locales/pt-BR.js
  app/i18n/locales/pt-PT.js
  app/i18n/locales/ru.js
  e2e/tests/room/02-room.spec.js
Labels: 👀 needs review, 👍 improvement

#2671 [FIX] Filenames are incorrect in non-latin alphabets on upload
  app/lib/methods/sendFileMessage.js
  app/utils/fileUpload/index.android.js
  app/utils/fileUpload/index.ios.js
  app/views/ShareListView/index.js
  patches/react-native-image-crop-picker+0.31.1.patch
Labels: 👀 needs review, 🛠 fix

#2685 [IMPROVEMENT] Ease white labelling for Android
  .circleci/config.yml
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/chat/rocket/reactnative/MainApplication.java
  android/app/src/main/java/chat/rocket/reactnative/networking/SSLPinningModule.java
  android/app/src/main/java/chat/rocket/reactnative/networking/SSLPinningPackage.java
  android/app/src/play/AndroidManifest.xml
  android/gradle.properties
  package.json
Labels: 👍 improvement, 🚚 chore, 🚨 needs changes

#2688 [FIX] Chats order
  app/lib/methods/helpers/mergeSubscriptionsRooms.js
  app/presentation/RoomItem/RoomItem.js
  app/presentation/RoomItem/UpdatedAt.js
  app/presentation/RoomItem/index.js
  storybook/stories/RoomItem.js
Labels: 👀 needs review, 🛠 fix

#2704 [FIX] Empty space on Messagebox
  app/containers/MessageBox/index.js
Labels: 👀 needs review, 🛠 fix

#2716 [FIX] Yarn android scripts
  package.json
Labels: 🛠 fix

#2717 [CHORE] Rename Experimental iOS lane
  .circleci/config.yml
  ios/fastlane/Fastfile
Labels: ♻️ refactor, 🚚 chore

#2718 [IMPROVEMENT] Use class variable instead of state for List's animated
  app/views/RoomView/List.js
Labels: 👍 improvement, 🚀 performance

#2723 [IMPROVEMENT] Match background and text mention colors
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/constants/colors.js
  app/presentation/UnreadBadge/getUnreadStyle.js
  app/presentation/UnreadBadge/getUnreadStyle.test.js
  app/utils/room.js
  app/views/ThreadMessagesView/Item.stories.js
  storybook/stories/index.js
Labels: 👍 improvement
