Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2020-03, with the labels that each got.

#1754 [FIX] Watermelon throwing "Cannot update a record with pending updates"
  app/containers/message/Content.js
  app/lib/methods/sendMessage.js
  app/lib/methods/subscriptions/room.js
  app/lib/methods/updateMessages.js
  app/utils/layoutAnimation.js
Labels: 👀 needs review, 🚀 performance, 🛠 fix

#1790 [FIX] Detox tests
  .circleci/config.yml
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/MessageBox/Mentions/index.js
  app/containers/markdown/index.js
  app/containers/message/Broadcast.js
  app/containers/message/Content.js
  app/sagas/login.js
  app/views/NotificationPreferencesView/index.js
  app/views/ProfileView/index.js
  app/views/ProfileView/styles.js
  app/views/RoomInfoEditView/index.js
  app/views/RoomInfoView/index.js
  app/views/RoomView/Header/Header.js
  app/views/RoomView/index.js
  e2e/00-onboarding.spec.js
  e2e/01-welcome.spec.js
  e2e/02-legal.spec.js
  e2e/03-forgotpassword.spec.js
  e2e/04-createuser.spec.js
  e2e/05-login.spec.js
  e2e/06-roomslist.spec.js
  e2e/07-createroom.spec.js
  e2e/08-room.spec.js
  e2e/09-roomactions.spec.js
  e2e/10-roominfo.spec.js
  e2e/11-changeserver.spec.js
  e2e/12-broadcast.spec.js
  e2e/13-profile.spec.js
  e2e/14-setting.spec.js
  e2e/15-joinpublicroom.spec.js
  e2e/helpers/app.js
  e2e/helpers/screenshot.js
  ios/Pods/Local Podspecs/SocketRocket.podspec.json
  package.json
  yarn.lock
Labels: ✅ tests, 🚧 wip, 🛠 fix

#1807 [CHORE] Use markdown preview on RoomView Header
  app/views/RoomView/Header/Header.js
Labels: 👀 needs review, 🚚 chore

#1809 [FIX] LoginSignup blink services
  app/actions/index.js
  app/constants/types.js
  app/lib/methods/getSettings.js
  app/lib/rocketchat.js
  app/reducers/reducers.js
  app/sagas/selectServer.js
Labels: 👀 needs review, 🛠 fix

#1813 [IMPROVEMENT] Request user presence on demand
  app/lib/methods/getUsersPresence.js
  app/lib/rocketchat.js
  app/presentation/RoomItem/index.js
  app/sagas/login.js
  app/views/RoomsListView/index.js
Labels: 👀 needs review, 👍 improvement

#1814 [FIX] Remove all invited users when create a channel
  app/presentation/UserItem.js
  app/views/CreateChannelView.js
Labels: 👀 needs review, 🛠 fix

#1819 [FIX] Pop from room which you have been removed
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/lib/methods/subscriptions/rooms.js
  app/views/RoomView/index.js
Labels: 👀 needs review, 🛠 fix

#1820 [FIX] Room Info styles
  app/views/RoomInfoView/index.js
Labels: 👀 needs review, 🛠 fix

#1822 [FIX] Empty mentions for @all and @here when real name is enabled
  app/containers/markdown/AtMention.js
Labels: 👀 needs review, 🛠 fix

#1827 [REGRESSION] Room View header title
  app/containers/markdown/index.js
  app/i18n/locales/de.js
  app/i18n/locales/en.js
  app/i18n/locales/es-ES.js
  app/i18n/locales/fr.js
  app/i18n/locales/it.js
  app/i18n/locales/ja.js
  app/i18n/locales/nl.js
  app/i18n/locales/pt-BR.js
  app/i18n/locales/pt-PT.js
  app/i18n/locales/ru.js
  app/i18n/locales/zh-CN.js
  app/views/RoomInfoView/index.js
  app/views/RoomView/Header/Header.js
  e2e/10-roominfo.spec.js
  e2e/12-broadcast.spec.js
Labels: 👀 needs review, 🛠 fix

#1829 [FIX] Mentions
  app/lib/methods/sendMessage.js
  yarn.lock
Labels: 👀 needs review, 🛠 fix

#1830 [FIX] Not found thread message
  app/lib/methods/sendMessage.js
Labels: 👀 needs review, 🛠 fix

#1832 [FIX] Separate delete and remove channel
  app/actions/actionsTypes.js
  app/actions/room.js
  app/i18n/locales/de.js
  app/i18n/locales/en.js
  app/i18n/locales/es-ES.js
  app/i18n/locales/fr.js
  app/i18n/locales/it.js
  app/i18n/locales/ja.js
  app/i18n/locales/nl.js
  app/i18n/locales/pt-BR.js
  app/i18n/locales/pt-PT.js
  app/i18n/locales/ru.js
  app/i18n/locales/zh-CN.js
  app/lib/methods/subscriptions/rooms.js
  app/lib/rocketchat.js
  app/reducers/index.js
  app/reducers/room.js
  app/sagas/room.js
  app/tablet.js
  app/views/RoomInfoEditView/index.js
  app/views/RoomView/index.js
Labels: 👀 needs review, 🛠 fix

#1815 [NEW] Filter system messages per room
  app/containers/UIKit/MultiSelect/Chips.js
  app/containers/UIKit/MultiSelect/index.js
  app/containers/UIKit/MultiSelect/styles.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/lib/database/model/Subscription.js
  app/lib/database/model/migrations.js
  app/lib/database/schema/app.js
  app/lib/methods/helpers/mergeSubscriptionsRooms.js
  app/utils/messageTypes.js
  app/views/RoomInfoEditView/SwitchContainer.js
  app/views/RoomInfoEditView/index.js
  app/views/RoomInfoEditView/styles.js
  app/views/RoomView/List.js
  app/views/RoomView/index.js
Labels: 🎉 feature, 👀 needs review

#1851 [FIX] Consecutive clear cache calls freezing app
  app/views/AuthLoadingView.js
  app/views/SettingsView/index.js
Labels: 👀 needs review, 🛠 fix

#1862 [FIX] Ignore silent mode on audio player
  app/containers/message/Audio.js
Labels: 🛠 fix

#1858 [IMPROVEMENT] Create App Group property on Info.plist
  app/index.js
  app/share.js
  ios/Podfile.lock
  ios/Pods/Local Podspecs/RNUserDefaults.podspec.json
  ios/Pods/Manifest.lock
  ios/RocketChatRN/Info.plist
  ios/ShareRocketChatRN/Info.plist
  package.json
  patches/react-native+0.61.5.patch
  patches/react-native-notifications+2.0.6.patch
  yarn.lock
Labels: 👀 needs review, 👍 improvement

#1618 [IMPROVEMENT] Make username clickable on message
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/message/User.js
Labels: 👀 needs review, 👍 improvement

#1768 [FIX] Show proper error message on profile
  app/views/ProfileView/index.js
Labels: 👀 needs review, 🛠 fix

#1616 [IMPROVEMENT] Show toast when a message is starred/unstarred
  app/containers/MessageActions.js
  app/i18n/locales/en.js
Labels: 👍 improvement, 🚨 needs changes

#1875 [FIX] Incorrect size params to avatar endpoint
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/Avatar.js
Labels: 👀 needs review

#1887 [FIX] Remove unrecognized emoji flags on android
  app/emojis.js
  app/utils/shortnameToUnicode/emojis.js
Labels: 👀 needs review

#1886 [FIX] Remove react-native global installs
  .circleci/config.yml
  README.md
Labels: 👀 needs review

#1881 [FIX][Android] opacity of emojis now are correct on android
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/EmojiPicker/styles.js
  app/containers/message/styles.js
Labels: 👀 needs review

#1909 [FIX] Encode Image URI
  app/containers/markdown/index.js
  app/utils/url.js
Labels: 👀 needs review, 🛠 fix

#1904 [NEW] Adaptive Icons
  android/app/src/debug/res/mipmap-hdpi/ic_launcher.png
  android/app/src/debug/res/mipmap-mdpi/ic_launcher.png
  android/app/src/debug/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/debug/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/debug/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/debug/res/values/colors.xml
  android/app/src/debug/res/values/strings.xml
  android/app/src/debug/res/values/styles.xml
  android/app/src/main/ic_launcher-web.png
  android/app/src/main/res/drawable-v24/ic_launcher_background.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/app/src/main/res/values/strings.xml
Labels: 🎉 feature, 👀 needs review

#1896 [FIX] Stop showing message on leave channel
  app/actions/actionsTypes.js
  app/actions/room.js
  app/lib/methods/subscriptions/rooms.js
  app/reducers/room.js
  app/sagas/room.js
  app/views/RoomInfoEditView/index.js
Labels: 👀 needs review, 🛠 fix

#1913 [FIX] Linkedin OAuth login
  app/views/LoginSignupView.js
Labels: 👀 needs review, 🛠 fix

#1930 [CHORE] Fix typo in CreateChannel View
  app/views/CreateChannelView.js
Labels: 🚚 chore

#1933 [FIX] Respect protocol in HTTP Auth IPs
  app/views/NewServerView.js
Labels: 👀 needs review, 🛠 fix

#1935 [FIX] Use new LinkedIn OAuth url
  app/views/LoginSignupView.js
Labels: 👀 needs review, 🛠 fix

#1939 [CHORE] Use storyboard on splash screen
  android/app/src/main/java/chat/rocket/reactnative/MainActivity.java
  ios/LaunchScreen.storyboard
  ios/LaunchScreen.xib
  ios/Podfile.lock
  ios/Pods/Local Podspecs/RNBootSplash.podspec.json
  ios/Pods/Manifest.lock
  ios/RocketChatRN.xcodeproj/project.pbxproj
  ios/RocketChatRN.xcodeproj/xcshareddata/xcschemes/RocketChatRN.xcscheme
  ios/RocketChatRN/AppDelegate.m
  package.json
  yarn.lock
Labels: 👀 needs review, 🚚 chore

#1927 [FIX] Check if avatar exists before create Icon
  android/app/src/main/java/chat/rocket/reactnative/CustomPushNotification.java
Labels: 🚧 wip, 🛠 fix

#1950 [FIX] Ignore self typing event
  app/lib/methods/subscriptions/room.js
Labels: 👀 needs review, 🛠 fix

#1942 [NEW] Create discussions
  README.md
  app/actions/actionsTypes.js
  app/actions/createDiscussion.js
  app/containers/Avatar.js
  app/containers/MessageActions.js
  app/containers/MessageBox/LeftButtons.ios.js
  app/containers/MessageBox/RightButtons.android.js
  app/containers/MessageBox/buttons/ActionsButton.js
  app/containers/MessageBox/buttons/index.js
  app/containers/MessageBox/index.js
  app/containers/UIKit/MultiSelect/Chips.js
  app/containers/UIKit/MultiSelect/Input.js
  app/containers/UIKit/MultiSelect/Items.js
  app/containers/UIKit/MultiSelect/index.js
  app/containers/UIKit/MultiSelect/styles.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/index.js
  app/lib/rocketchat.js
  app/reducers/createDiscussion.js
  app/reducers/index.js
  app/sagas/createDiscussion.js
  app/sagas/index.js
  app/tablet.js
  app/utils/avatar.js
  app/views/CreateDiscussionView/SelectChannel.js
  app/views/CreateDiscussionView/SelectUsers.js
  app/views/CreateDiscussionView/index.js
  app/views/CreateDiscussionView/styles.js
  app/views/NewMessageView.js
Labels: 🎉 feature, 👀 needs review

#1910 [FIX] Load messages
  app/lib/methods/loadMessagesForRoom.js
  app/lib/methods/loadMissedMessages.js
  app/lib/methods/readMessages.js
  app/views/RoomView/index.js
Labels: 🛠 fix

#1811 [NEW] Custom Status
  app/constants/settings.js
  app/containers/HeaderButton.js
  app/containers/ListItem.js
  app/containers/MessageBox/UploadModal.js
  app/containers/Status/Status.js
  app/containers/Status/index.js
  app/containers/TextInput.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/index.js
  app/lib/database/index.js
  app/lib/database/model/User.js
  app/lib/database/model/serversMigrations.js
  app/lib/database/schema/servers.js
  app/lib/methods/getUsersPresence.js
  app/lib/rocketchat.js
  app/presentation/RoomItem/index.js
  app/sagas/login.js
  app/sagas/selectServer.js
  app/tablet.js
  app/views/RoomActionsView/index.js
  app/views/RoomInfoView/index.js
  app/views/RoomView/Banner.js
  app/views/RoomView/Header/Header.js
  app/views/RoomView/Header/Icon.js
  app/views/RoomView/Header/index.js
  app/views/RoomView/index.js
  app/views/RoomView/styles.js
  app/views/ShareListView/Header/Header.ios.js
  app/views/ShareListView/index.js
  app/views/SidebarView/SidebarItem.js
  app/views/SidebarView/index.js
  app/views/SidebarView/styles.js
  app/views/StatusView.js
  app/views/WithoutServersView.js
  e2e/13-profile.spec.js
  e2e/16-status.spec.js
  storybook/stories/index.js
Labels: 🎉 feature, 👀 needs review
