Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2020-11, with the labels that each got.

#2547 [IMPROVEMENT] Auto search when text changes in directory textfield
  app/views/DirectoryView/index.js
Labels: 👀 needs review, 👍 improvement

#2503 [FIX] Rooms header overlapping right icons
  app/containers/Header/index.js
Labels: 🛠 fix

#2602 [FIX] App crashing when notification is received/replied (Android)
  android/app/src/play/java/chat/rocket/reactnative/Ejson.java
  android/app/src/play/java/chat/rocket/reactnative/LoadNotification.java
Labels: 👀 needs review, 🛠 fix

#2603 [REGRESSION] Avatars doesn't show up on older servers (< 3.6.0)
  app/utils/avatar.js
  storybook/index.js
Labels: 👀 needs review, 🛠 fix

#2562 [FIX] Missing locales in moment helper
  app/utils/moment.js
Labels: 🚨 needs changes, 🛠 fix

#2555 [i18n] Add missing Russian strings
  app/i18n/locales/ru.js
Labels: 🌎 i18n, 👀 needs review

#2606 [FIX] 'Send to channel' when replying as a quote
  app/containers/MessageBox/index.js
  app/views/RoomView/index.js
Labels: 👀 needs review, 🛠 fix

#2604 [FIX] Android notification on Dark Theme using Official main color
  android/app/src/main/res/values-night/colors.xml
Labels: 👀 needs review, 🛠 fix

#2607 [FIX] Storybook not able to import Avatar
  __tests__/Storyshots.test.js
  app/containers/Avatar/Avatar.js
  app/containers/Avatar/index.js
  app/containers/MessageBox/EmojiKeyboard.js
  app/containers/message/MessageAvatar.js
  app/containers/message/index.js
  app/i18n/locales/ru.js
  app/lib/rocketchat.js
  app/presentation/RoomItem/RoomItem.js
  app/presentation/RoomItem/Wrapper.js
  app/presentation/RoomItem/index.js
  app/reducers/share.js
  app/sagas/encryption.js
  app/utils/avatar.js
  app/views/CreateDiscussionView/SelectChannel.js
  app/views/CreateDiscussionView/SelectUsers.js
  app/views/CreateDiscussionView/index.js
  app/views/RoomInfoEditView/index.js
  app/views/RoomsListView/index.js
  app/views/SelectServerView.js
  app/views/ShareListView/index.js
  app/views/ShareView/index.js
  app/views/ThreadMessagesView/Item.stories.js
  storybook/index.js
  storybook/stories/index.js
  yarn.lock
Labels: 👀 needs review, 🛠 fix

#2584 [BUG] App isn't showing message for PDF/file uploads
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/message/Reply.js
  storybook/stories/Message.js
Labels: 🚨 needs changes, 🛠 fix

#2608 [FIX] Header title positioning not changing according to the number of icons
  app/containers/Header/index.js
  app/views/RoomView/index.js
  app/views/RoomsListView/index.js
  app/views/ThreadMessagesView/index.js
Labels: 🛠 fix

#2611 [DOCS] Update Android Supported versions
  README.md
Labels: 👀 needs review, 📝 docs

#2615 [FIX] User notification preferences throwing an error
  app/views/UserNotificationPreferencesView/index.js
Labels: 👀 needs review, 🛠 fix

#2616 [FIX] MomentJS crashing on Spanish language
  app/utils/moment.js
Labels: 👀 needs review, 🛠 fix

#2617 [FIX] AllowBackup manifest attribute causing unexpected behaviour on login
  android/app/src/main/AndroidManifest.xml
  android/app/src/play/AndroidManifest.xml
Labels: 🛠 fix

#2618 [FIX] Search messages crashing when show a thread message
  app/containers/message/Thread.js
Labels: 👀 needs review, 🛠 fix

#2557 [FIX] F-Droid build for store
  android/app/build.gradle
  android/app/src/foss/java/chat/rocket/reactnative/CustomPushNotification.java
  android/app/src/foss/java/chat/rocket/reactnative/DismissNotification.java
  android/app/src/foss/java/chat/rocket/reactnative/Ejson.java
  android/app/src/foss/java/chat/rocket/reactnative/ReplyBroadcast.java
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/chat/rocket/reactnative/MainApplication.java
  android/app/src/play/AndroidManifest.xml
  android/app/src/play/java/chat/rocket/reactnative/MainPlayApplication.java
  android/build.gradle
  patches/react-native-device-info+5.6.2.patch
  yarn.lock
Labels: 👀 needs review, 🚚 chore

#2637 [FIX] Notification stream throwing an error when there isn't a message on payload
  app/lib/methods/subscriptions/rooms.js
Labels: 👀 needs review, 🛠 fix

#2636 [FIX] Threads not being updated and other related issues
  app/containers/message/Thread.js
  app/containers/message/index.js
  app/views/RoomView/Header/Header.js
  app/views/RoomView/List.js
  app/views/RoomView/index.js
  app/views/RoomsListView/index.js
  storybook/stories/index.js
Labels: 👀 needs review, 🛠 fix

#2630 [FIX] Minor room header issues
  app/views/RoomView/Header/Header.js
  app/views/RoomView/index.js
Labels: 👀 needs review, 🛠 fix

#2640 [FIX] Model columns misplaced
  app/lib/database/model/User.js
  app/lib/database/model/servers/User.js
Labels: 👀 needs review, 🛠 fix

#2639 [FIX] Connect a null server
  app/views/NewServerView/index.js
Labels: 👀 needs review, 🛠 fix

#2641 Bump version to 4.12.1
  android/app/build.gradle
  ios/RocketChatRN.xcodeproj/project.pbxproj
  ios/RocketChatRN/Info.plist
  ios/ShareRocketChatRN/Info.plist
Labels: 🚚 chore

#2657 Bump version to 4.13.0
  android/app/build.gradle
  ios/RocketChatRN.xcodeproj/project.pbxproj
  ios/RocketChatRN/Info.plist
  ios/ShareRocketChatRN/Info.plist
Labels: 💎 release

#2658 [FIX] Update Loading logo
  app/static/images/logo.png
Labels: 👀 needs review, 🛠 fix

#2656 [NEW] Support RTL
  __tests__/__snapshots__/Storyshots.test.js.snap
  android/app/src/main/AndroidManifest.xml
  app/containers/ActionSheet/styles.js
  app/containers/Button/index.js
  app/containers/EmojiPicker/styles.js
  app/containers/List/ListIcon.js
  app/containers/List/ListItem.js
  app/containers/MessageActions/Header.js
  app/containers/MessageBox/styles.js
  app/containers/ReactionsModal.js
  app/containers/TextInput.js
  app/containers/Toast.js
  app/containers/markdown/index.js
  app/containers/message/styles.js
  app/i18n/index.js
  app/i18n/isRTL.js
  app/presentation/RoomItem/Actions.js
  app/presentation/RoomItem/Touchable.js
  app/presentation/RoomItem/styles.js
  app/presentation/TextInput.js
  app/sagas/login.js
  app/stacks/InsideStack.js
  app/utils/navigation/animations.js
  app/views/LanguageView/index.js
  app/views/OnboardingView/styles.js
  app/views/PickerView.js
  app/views/RoomActionsView/index.js
  app/views/RoomActionsView/styles.js
  app/views/RoomInfoEditView/styles.js
  app/views/ShareListView/styles.js
  app/views/ShareView/Preview.js
  app/views/Styles.js
  app/views/ThreadMessagesView/NoDataFound.js
  app/views/VisitorNavigationView.js
  app/views/WithoutServersView.js
  app/views/WorkspaceView/styles.js
  ios/Podfile.lock
  ios/Pods/Headers/Private/react-native-restart/Restart.h
  ios/Pods/Headers/Public/react-native-restart/Restart.h
  ios/Pods/Local Podspecs/react-native-restart.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/Target Support Files/Pods-NotificationService/Pods-NotificationService-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-NotificationService/Pods-NotificationService-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-NotificationService/Pods-NotificationService.debug.xcconfig
  ios/Pods/Target Support Files/Pods-NotificationService/Pods-NotificationService.release.xcconfig
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/react-native-restart/react-native-restart-dummy.m
  ios/Pods/Target Support Files/react-native-restart/react-native-restart-prefix.pch
  ios/Pods/Target Support Files/react-native-restart/react-native-restart.debug.xcconfig
  ios/Pods/Target Support Files/react-native-restart/react-native-restart.release.xcconfig
  package.json
  yarn.lock
Labels: 🎉 feature, 👀 needs review
