Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2020-04, with the labels that each got.

#1958 [NEW] Direct Message between multiple users
  app/constants/settings.js
  app/containers/RoomTypeIcon.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/lib/database/model/Subscription.js
  app/lib/database/model/migrations.js
  app/lib/database/schema/app.js
  app/lib/methods/helpers/mergeSubscriptionsRooms.js
  app/lib/methods/subscriptions/rooms.js
  app/lib/rocketchat.js
  app/presentation/RoomItem/TypeIcon.js
  app/presentation/RoomItem/index.js
  app/presentation/UserItem.js
  app/sagas/createChannel.js
  app/views/CreateChannelView.js
  app/views/DirectoryView/index.js
  app/views/NewMessageView.js
  app/views/RoomActionsView/index.js
  app/views/RoomActionsView/styles.js
  app/views/RoomInfoView/index.js
  app/views/RoomView/Header/Header.js
  app/views/RoomView/Header/Icon.js
  app/views/RoomView/Header/index.js
  app/views/RoomView/index.js
  app/views/RoomsListView/index.js
  app/views/SelectedUsersView.js
Labels: 🎉 feature, 👀 needs review

#1968 [FIX] Add server and hide login
  app/lib/rocketchat.js
  app/selectors/login.js
  app/views/RegisterView.js
  app/views/RoomsListView/ServerDropdown.js
  app/views/WorkspaceView/index.js
Labels: 👀 needs review, 🛠 fix

#1969 [FIX] MultiSelect Keyboard behavior (Android)
  app/containers/UIKit/MultiSelect/index.js
Labels: 🛠 fix

#1967 [FIX] Clear settings on server change
  app/actions/actionsTypes.js
  app/actions/index.js
  app/actions/settings.js
  app/constants/types.js
  app/lib/methods/getSettings.js
  app/reducers/index.js
  app/reducers/initialState.js
  app/reducers/reducers.js
  app/reducers/rootReducer.js
  app/reducers/settings.js
  app/sagas/selectServer.js
Labels: 👀 needs review, 🛠 fix

#1925 [FIX] Deeplinking without RoomId
  app/lib/methods/canOpenRoom.js
  app/sagas/deepLinking.js
  app/views/RoomView/index.js
Labels: 👀 needs review, 🛠 fix

#1961 [NEW] Two Factor authentication via email
  app/containers/TwoFactor/index.js
  app/containers/TwoFactor/styles.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/index.js
  app/lib/rocketchat.js
  app/utils/fetch.js
  app/utils/twoFactor.js
  app/views/LoginView.js
  app/views/ProfileView/index.js
  package.json
  yarn.lock
Labels: 🎉 feature, 👀 needs review

#1906 [FIX] Correct message for manual approval user Registration
  app/constants/settings.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/views/RegisterView.js
Labels: 🛠 fix

#1974 [FIX] Direct Message between multiple users REST
  app/lib/rocketchat.js
  app/sagas/createChannel.js
Labels: 👀 needs review, 🛠 fix

#1890 [FIX] Investigate app losing connection issues
  __mocks__/@rocket.chat/sdk.js
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/lib/methods/getUsersPresence.js
  app/lib/methods/subscriptions/room.js
  app/lib/rocketchat.js
  app/presentation/RoomItem/index.js
  app/sagas/login.js
  app/sagas/selectServer.js
  app/views/RoomView/Header/index.js
  app/views/RoomView/index.js
  app/views/RoomsListView/index.js
  package.json
  patches/@rocket.chat+sdk+1.0.0-alpha.41.patch
  yarn.lock
Labels: 🛠 fix

#1999 [FIX] Single message thread inserting thread without rid
  app/views/RoomView/index.js
Labels: 👀 needs review, 🛠 fix

#1997 [FIX] ThreadMessagesView crashing on load
  app/views/ThreadMessagesView/index.js
Labels: 👀 needs review, 🛠 fix

#1996 [FIX] Saml
  app/views/AuthenticationWebView.js
Labels: 👀 needs review, 🛠 fix

#1995 [FIX] Change user own status
  app/lib/rocketchat.js
  app/sagas/login.js
  app/views/StatusView.js
Labels: 👀 needs review, 🛠 fix

#2000 [FIX] Change notifications preferences
  app/containers/Check.js
  app/containers/ListItem.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/index.js
  app/views/NotificationPreferencesView/index.js
  app/views/NotificationPreferencesView/styles.js
  app/views/PickerView.js
Labels: 👀 needs review, 🛠 fix

#2011 [FIX] DM header blink
  app/lib/methods/canOpenRoom.js
  app/lib/rocketchat.js
  app/sagas/deepLinking.js
  app/views/RoomActionsView/index.js
  app/views/RoomView/index.js
  app/views/RoomsListView/index.js
Labels: 👀 needs review, 🛠 fix

#2017 [FIX] Split get settings into two requests
  app/lib/methods/getSettings.js
  app/sagas/selectServer.js
Labels: 👀 needs review, 🛠 fix

#2007 [REGRESSION] Invite Links
  app/sagas/deepLinking.js
Labels: 👀 needs review, 🛠 fix

#1951 [FIX] Read only channel/broadcast
  app/lib/database/index.js
  app/lib/methods/subscriptions/rooms.js
  app/lib/rocketchat.js
  app/utils/room.js
  app/views/DirectoryView/index.js
  app/views/RoomView/index.js
  app/views/RoomsListView/index.js
  app/views/ShareView/index.js
Labels: 👀 needs review, 🛠 fix

#2024 [FIX] Cas auth
  app/views/AuthenticationWebView.js
Labels: 👀 needs review, 🛠 fix

#2018 [FIX] Login TOTP Compatibility to older servers
  app/containers/TwoFactor/index.js
  app/containers/TwoFactor/styles.js
  app/lib/rocketchat.js
Labels: 👀 needs review, 🛠 fix

#2029 Bump version to 4.6.4
  android/app/build.gradle
  ios/RocketChatRN/Info.plist
  ios/ShareRocketChatRN/Info.plist
Labels: 🚚 chore

#2030 [FIX] Lint
  app/utils/isReadOnly.js
  app/utils/room.js
  app/views/RoomView/index.js
  app/views/ShareView/index.js
Labels: 👀 needs review, 👷 ci, 🛠 fix

#2022 [FIX] UIKit with only one block
  app/containers/message/Blocks.js
  app/views/ModalBlockView.js
Labels: 👀 needs review, 🛠 fix

#2035 Bump version to 4.7.0
  android/app/build.gradle
  ios/RocketChatRN/Info.plist
  ios/ShareRocketChatRN/Info.plist
Labels: 🚚 chore

#2081 [FIX] Action Tint Color on Black theme
  app/constants/colors.js
Labels: 👀 needs review, 🛠 fix

#2080 [FIX] Prevent crash when thread is not found
  app/views/RoomView/List.js
Labels: 👀 needs review, 🛠 fix

#2079 [FIX] Prevent double click
  app/views/RoomsListView/index.js
Labels: 👀 needs review, 🛠 fix

#2078 [FIX] Show slash commands when disconnected
  app/containers/MessageBox/Mentions/MentionItem.js
Labels: 👀 needs review, 🛠 fix

#2077 [FIX] Backhandler onBoarding
  app/views/NewServerView.js
Labels: 👀 needs review, 🛠 fix

#2076 [FIX] Respect UI_Allow_room_names_with_special_chars setting
  app/constants/settings.js
  app/lib/rocketchat.js
  app/views/RoomActionsView/index.js
  app/views/RoomInfoEditView/index.js
  app/views/RoomInfoView/index.js
  app/views/RoomView/index.js
Labels: 👀 needs review, 🛠 fix

#2071 [FIX] RoomsList update sometimes isn't fired
  app/views/RoomsListView/index.js
Labels: 👀 needs review, 🛠 fix

#2069 [IMPROVEMENT] Stop inserting last message as message object from rooms stream if room is focused
  app/actions/actionsTypes.js
  app/actions/room.js
  app/lib/methods/subscriptions/room.js
  app/lib/methods/subscriptions/rooms.js
  app/reducers/room.js
Labels: 👀 needs review, 👍 improvement

#2067 [FIX] Hide system messages
  app/containers/UIKit/MultiSelect/index.js
Labels: 👀 needs review, 🛠 fix

#2066 [FIX] Pending update
  app/lib/methods/subscriptions/room.js
Labels: 👀 needs review, 🛠 fix

#2055 [FIX] Prevent crash when room.uids was not inserted yet
  app/lib/rocketchat.js
Labels: 👀 needs review, 🛠 fix

#2063 [FEATURE] Save video
  app/i18n/locales/en.js
  app/views/AttachmentView.js
Labels: 🎉 feature

#2050 [FIX] Send totp-code to meteor call
  app/lib/rocketchat.js
Labels: 🛠 fix

#2049 [FIX] MessageBox mention shouldn't show group DMs
  app/lib/rocketchat.js
Labels: 👀 needs review, 🛠 fix

#2047 [FIX] AttachmentView (Android)(Tablet)
  app/index.js
  app/views/RoomActionsView/index.js
Labels: 🛠 fix

#2020 [FIX] Allow special chars in Filename
  app/lib/methods/sendFileMessage.js
  app/views/AttachmentView.js
Labels: 🛠 fix

#2073 [FIX] Recorded audio on Android doesn't play on iOS
  __mocks__/expo-av.js
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/MessageBox/Recording.js
  app/containers/message/Audio.js
  ios/Podfile.lock
  ios/Pods/Headers/Private/SocketRocket/NSRunLoop+SRWebSocket.h
  ios/Pods/Headers/Private/SocketRocket/NSRunLoop+SRWebSocketPrivate.h
  ios/Pods/Headers/Private/SocketRocket/NSURLRequest+SRWebSocket.h
  ios/Pods/Headers/Private/SocketRocket/NSURLRequest+SRWebSocketPrivate.h
  ios/Pods/Headers/Private/SocketRocket/SRConstants.h
  ios/Pods/Headers/Private/SocketRocket/SRDelegateController.h
  ios/Pods/Headers/Private/SocketRocket/SRError.h
  ios/Pods/Headers/Private/SocketRocket/SRHTTPConnectMessage.h
  ios/Pods/Headers/Private/SocketRocket/SRHash.h
  ios/Pods/Headers/Private/SocketRocket/SRIOConsumer.h
  ios/Pods/Headers/Private/SocketRocket/SRIOConsumerPool.h
  ios/Pods/Headers/Private/SocketRocket/SRLog.h
  ios/Pods/Headers/Private/SocketRocket/SRMutex.h
  ios/Pods/Headers/Private/SocketRocket/SRPinningSecurityPolicy.h
  ios/Pods/Headers/Private/SocketRocket/SRProxyConnect.h
  ios/Pods/Headers/Private/SocketRocket/SRRandom.h
  ios/Pods/Headers/Private/SocketRocket/SRRunLoopThread.h
  ios/Pods/Headers/Private/SocketRocket/SRSIMDHelpers.h
  ios/Pods/Headers/Private/SocketRocket/SRSecurityPolicy.h
  ios/Pods/Headers/Private/SocketRocket/SRURLUtilities.h
  ios/Pods/Headers/Private/SocketRocket/SRWebSocket.h
  ios/Pods/Headers/Private/SocketRocket/SocketRocket.h
  ios/Pods/Headers/Private/react-native-video/RCTVideo.h
  ios/Pods/Headers/Private/react-native-video/RCTVideoManager.h
  ios/Pods/Headers/Private/react-native-video/RCTVideoPlayerViewController.h
  ios/Pods/Headers/Private/react-native-video/RCTVideoPlayerViewControllerDelegate.h
  ios/Pods/Headers/Private/react-native-video/UIView+FindUIViewController.h
  ios/Pods/Headers/Public/SocketRocket/NSRunLoop+SRWebSocket.h
  ios/Pods/Headers/Public/SocketRocket/NSURLRequest+SRWebSocket.h
  ios/Pods/Headers/Public/SocketRocket/SRSecurityPolicy.h
  ios/Pods/Headers/Public/SocketRocket/SRWebSocket.h
  ios/Pods/Headers/Public/SocketRocket/SocketRocket.h
  ios/Pods/Headers/Public/react-native-video/RCTVideo.h
  ios/Pods/Headers/Public/react-native-video/RCTVideoManager.h
  ios/Pods/Headers/Public/react-native-video/RCTVideoPlayerViewController.h
  ios/Pods/Headers/Public/react-native-video/RCTVideoPlayerViewControllerDelegate.h
  ios/Pods/Headers/Public/react-native-video/UIView+FindUIViewController.h
  ios/Pods/Local Podspecs/ReactNativeKeyboardTrackingView.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/SocketRocket/SocketRocket-dummy.m
  ios/Pods/Target Support Files/SocketRocket/SocketRocket-prefix.pch
  ios/Pods/Target Support Files/SocketRocket/SocketRocket.xcconfig
  ios/Pods/Target Support Files/react-native-video/react-native-video-dummy.m
  ios/Pods/Target Support Files/react-native-video/react-native-video.xcconfig
  package.json
  yarn.lock
Labels: 👀 needs review, 🛠 fix

#2082 [IMPROVEMENT] Message Touchable
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/Avatar.js
  app/containers/message/Attachments.js
  app/containers/message/Audio.js
  app/containers/message/Broadcast.js
  app/containers/message/CallButton.js
  app/containers/message/Content.js
  app/containers/message/Context.js
  app/containers/message/Discussion.js
  app/containers/message/Emoji.js
  app/containers/message/Image.js
  app/containers/message/Message.js
  app/containers/message/MessageAvatar.js
  app/containers/message/MessageError.js
  app/containers/message/Reactions.js
  app/containers/message/Reply.js
  app/containers/message/Touchable.js
  app/containers/message/Urls.js
  app/containers/message/User.js
  app/containers/message/Video.js
  app/containers/message/index.js
  app/views/RoomView/Header/RoomHeaderLeft.js
  storybook/stories/Message.js
Labels: 👀 needs review, 👍 improvement
