Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2020-06, with the labels that each got.

#2166 [CHORE] Update WatermelonDB to 0.16.2
  ios/Podfile.lock
  ios/Pods/Local Podspecs/RNCAsyncStorage.podspec.json
  ios/Pods/Manifest.lock
  package.json
  patches/@nozbe+watermelondb+0.16.2.patch
  yarn.lock
Labels: ⬆️ update dependencies, 🚚 chore

#2173 Markdown linting for e2e README
  e2e/README.md
Labels: 📝 docs, 🚨 needs changes

#2101 [FIX] Load messages when hideSystemMessages is enabled
  app/views/RoomView/List.js
Labels: 👀 needs review, 🛠 fix

#2175 [FIX] Respect server HideSystemMessages
  app/views/RoomView/index.js
Labels: 👀 needs review, 🛠 fix

#2185 [FIX] Load messages
  app/views/RoomView/List.js
Labels: 👀 needs review, 🛠 fix

#2187 [FIX] Show registration form when add server by a invite link
  app/views/LoginView.js
  app/views/WorkspaceView/index.js
Labels: 👀 needs review, 🛠 fix

#2188 [FIX] 2FA email - send code again
  app/lib/rocketchat.js
Labels: 👀 needs review, 🛠 fix

#2114 [NEW] Action Sheet
  app/AppContainer.js
  app/containers/ActionSheet/ActionSheet.js
  app/containers/ActionSheet/Button.js
  app/containers/ActionSheet/Handle.js
  app/containers/ActionSheet/Item.js
  app/containers/ActionSheet/Provider.js
  app/containers/ActionSheet/index.js
  app/containers/ActionSheet/styles.js
  app/containers/MessageActions.js
  app/containers/MessageActions/Header.js
  app/containers/MessageActions/index.js
  app/containers/MessageBox/ReplyPreview.js
  app/containers/MessageBox/index.js
  app/containers/MessageErrorActions.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/theme.js
  app/views/MessagesView/index.js
  app/views/NewServerView.js
  app/views/RoomMembersView/index.js
  app/views/RoomView/index.js
  e2e/tests/room/02-room.spec.js
  e2e/tests/room/03-roomactions.spec.js
  package.json
  patches/react-native-scroll-bottom-sheet+0.6.1.patch
  yarn.lock
Labels: 🎉 feature, 👀 needs review

#2100 [NEW] Add fastlane to android module and configure CI
  .circleci/config.yml
  .gitignore
  android/Gemfile
  android/Gemfile.lock
  android/fastlane/Appfile
  android/fastlane/Fastfile
  android/fastlane/Pluginfile
  android/fastlane/README.md
Labels: 👀 needs review, 👷 ci

#2139 [IMPROVEMENT] Use react-native-notifier for in-app notifications
  app/AppContainer.js
  app/actions/actionsTypes.js
  app/actions/notification.js
  app/containers/InAppNotification/NotifierComponent.js
  app/containers/InAppNotification/index.js
  app/index.js
  app/lib/methods/subscriptions/rooms.js
  app/notifications/inApp/index.js
  app/reducers/index.js
  app/reducers/notification.js
  app/stacks/InsideStack.js
  app/stacks/MasterDetailStack/index.js
  package.json
  yarn.lock
Labels: 👍 improvement, 🚨 needs changes

#2098 [CHORE] Create DimensionsContext
  app/containers/ActionSheet/ActionSheet.js
  app/containers/EmojiPicker/EmojiCategory.js
  app/containers/InAppNotification/NotifierComponent.js
  app/containers/MessageActions/Header.js
  app/containers/MessageBox/UploadModal.js
  app/containers/message/Audio.js
  app/dimensions.js
  app/index.js
  app/presentation/ImageViewer/index.android.js
  app/views/RoomView/Header/index.js
  app/views/RoomView/ReactionPicker.js
  app/views/RoomView/UploadProgress.js
  app/views/RoomView/index.js
  app/views/RoomsListView/index.js
  package.json
  yarn.lock
Labels: 🚚 chore, 🚨 needs changes

#2184 [NEW] IFrame authentication
  app/constants/settings.js
  app/lib/methods/getSettings.js
  app/views/AuthenticationWebView.js
  app/views/WorkspaceView/index.js
Labels: 🎉 feature, 👀 needs review

#2217 [NEW] Omnichannel Status Toggle
  app/i18n/locales/en.js
  app/lib/methods/subscriptions/rooms.js
  app/lib/rocketchat.js
  app/sagas/room.js
  app/views/SettingsView/index.js
  package.json
  patches/@rocket.chat+sdk+1.0.0-dj.15.patch
  yarn.lock
Labels: 🎉 feature, 👀 needs review

#2216 [FIX] Typing when UI_Use_Real_Name is enabled
  app/lib/methods/subscriptions/room.js
  app/lib/rocketchat.js
Labels: 👀 needs review, 🛠 fix

#2222 [REGRESSION] Logout failing after #2217
  app/views/SettingsView/index.js
Labels: 👀 needs review, 🛠 fix

#2104 [CHORE] Add wrapper to make Meteor methods calls over REST
  app/constants/settings.js
  app/lib/methods/callJitsi.js
  app/lib/rocketchat.js
  app/views/RoomView/index.js
  app/views/SetUsernameView.js
Labels: 🚚 chore

#2225 [IMPROVEMENT] Mark thread as read on open
  app/lib/rocketchat.js
  app/views/RoomView/List.js
Labels: 👀 needs review, 👍 improvement
