Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2020-10, with the labels that each got.

#2558 [FIX] Failing iOS build on fork PR
  .circleci/config.yml
  ios/fastlane/Fastfile
Labels: 👷 ci, 🚨 needs changes, 🛠 fix

#2504 [NEW] Support for custom avatar images in channels
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/Avatar/Avatar.js
  app/containers/Avatar/index.js
  app/containers/InAppNotification/NotifierComponent.js
  app/containers/message/utils.js
  app/i18n/locales/en.js
  app/lib/database/model/Room.js
  app/lib/database/model/Subscription.js
  app/lib/database/model/migrations.js
  app/lib/database/schema/app.js
  app/lib/methods/helpers/findSubscriptionsRooms.js
  app/lib/methods/helpers/mergeSubscriptionsRooms.js
  app/lib/methods/subscriptions/rooms.js
  app/lib/rocketchat.js
  app/presentation/DirectoryItem/index.js
  app/presentation/RoomItem/RoomItem.js
  app/presentation/RoomItem/Wrapper.js
  app/presentation/RoomItem/index.js
  app/utils/avatar.js
  app/views/CreateDiscussionView/SelectChannel.js
  app/views/DirectoryView/index.js
  app/views/RoomActionsView/index.js
  app/views/RoomInfoEditView/index.js
  app/views/RoomInfoEditView/styles.js
  app/views/RoomInfoView/index.js
  package.json
  storybook/stories/Avatar.js
  yarn.lock
Labels: 🎉 feature

#2517 [FIX] App always sends auth for Avatar requests
  app/actions/actionsTypes.js
  app/actions/share.js
  app/constants/settings.js
  app/containers/Avatar/Avatar.js
  app/containers/Avatar/index.js
  app/lib/database/index.js
  app/lib/rocketchat.js
  app/reducers/share.js
  app/utils/avatar.js
  app/views/CreateDiscussionView/SelectChannel.js
  app/views/CreateDiscussionView/SelectUsers.js
  app/views/CreateDiscussionView/index.js
  app/views/ShareListView/index.js
  storybook/stories/index.js
Labels: 🛠 fix

#2516 [FIX] iOS uploads always cropping as squares
  app/containers/MessageBox/index.js
  app/views/ProfileView/index.js
Labels: 👀 needs review, 🛠 fix

#2559 [IMPROVEMENT] Mentions layout without background
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/constants/colors.js
  app/containers/markdown/AtMention.js
  app/containers/markdown/Hashtag.js
  app/containers/markdown/styles.js
  app/presentation/UnreadBadge.js
  storybook/stories/Message.js
Labels: 👀 needs review, 👍 improvement, 🚸 ux

#2566 [IMPROVEMENT] Support badge number on header buttons
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/constants/colors.js
  app/containers/Header/index.js
  app/containers/HeaderButton.js
  app/containers/HeaderButton/Common.js
  app/containers/HeaderButton/HeaderButtonContainer.js
  app/containers/HeaderButton/HeaderButtonItem.js
  app/containers/HeaderButton/HeaderButtonItemBadge.js
  app/containers/HeaderButton/index.js
  app/ee/omnichannel/views/QueueListView.js
  app/presentation/RoomItem/RoomItem.js
  app/presentation/RoomItem/index.js
  app/presentation/UnreadBadge.js
  app/presentation/UnreadBadge/getUnreadStyle.js
  app/presentation/UnreadBadge/getUnreadStyle.test.js
  app/presentation/UnreadBadge/index.js
  app/views/AdminPanelView/index.js
  app/views/AttachmentView.js
  app/views/AuthenticationWebView.js
  app/views/CreateChannelView.js
  app/views/CreateDiscussionView/index.js
  app/views/DirectoryView/index.js
  app/views/E2EEnterYourPasswordView.js
  app/views/E2EHowItWorksView.js
  app/views/E2ESaveYourPasswordView.js
  app/views/LoginView.js
  app/views/ModalBlockView.js
  app/views/NewMessageView.js
  app/views/NewServerView/index.js
  app/views/ProfileView/index.js
  app/views/ReadReceiptView/index.js
  app/views/RegisterView.js
  app/views/RoomActionsView/index.js
  app/views/RoomInfoView/index.js
  app/views/RoomMembersView/index.js
  app/views/RoomView/Header/RightButtons.js
  app/views/RoomsListView/index.js
  app/views/SearchMessagesView/index.js
  app/views/SelectedUsersView.js
  app/views/SettingsView/index.js
  app/views/ShareListView/Header/Header.ios.js
  app/views/ShareListView/index.js
  app/views/ShareView/index.js
  app/views/StatusView.js
  app/views/ThreadMessagesView/index.js
  app/views/WithoutServersView.js
  package.json
  patches/react-navigation-header-buttons+3.0.5.patch
  storybook/stories/HeaderButtons.js
  storybook/stories/RoomItem.js
  storybook/stories/UnreadBadge.js
  storybook/stories/index.js
  yarn.lock
Labels: ♻️ refactor, 👀 needs review, 👍 improvement

#2542 [IMPROVEMENT] Add `Change Encryption Password` and `Reset E2E Key`
  app/containers/Button/index.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/lib/encryption/encryption.js
  app/lib/rocketchat.js
  app/sagas/login.js
  app/stacks/InsideStack.js
  app/stacks/MasterDetailStack/index.js
  app/utils/log/events.js
  app/views/E2EEncryptionSecurityView.js
  app/views/E2EEnterYourPasswordView.js
  app/views/E2ESaveYourPasswordView.js
  app/views/RoomActionsView/index.js
  app/views/RoomsListView/ListHeader/Encryption.js
  app/views/SecurityPrivacyView.js
  app/views/SettingsView/index.js
  e2e/tests/assorted/01-e2eencryption.spec.js
  e2e/tests/assorted/04-setting.spec.js
  e2e/tests/assorted/07-changeserver.spec.js
Labels: ✅ tests, 👀 needs review, 👍 improvement
