Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2020-09, with the labels that each got.

#2450 [CHORE] Update run-ios and run-android scripts
  CONTRIBUTING.md
  package.json
Labels: 👀 needs review, 🚚 chore

#2449 [IMPROVEMENT] Show errors on server enter
  app/i18n/locales/de.js
  app/i18n/locales/en.js
  app/i18n/locales/es-ES.js
  app/i18n/locales/fr.js
  app/i18n/locales/it.js
  app/i18n/locales/ja.js
  app/i18n/locales/nl.js
  app/i18n/locales/pt-BR.js
  app/i18n/locales/pt-PT.js
  app/i18n/locales/ru.js
  app/i18n/locales/zh-CN.js
  app/lib/rocketchat.js
  app/sagas/selectServer.js
  ios/Podfile.lock
  ios/Pods/Headers/Private/rn-fetch-blob/IOS7Polyfill.h
  ios/Pods/Headers/Private/rn-fetch-blob/RNFetchBlob.h
  ios/Pods/Headers/Private/rn-fetch-blob/RNFetchBlobConst.h
  ios/Pods/Headers/Private/rn-fetch-blob/RNFetchBlobFS.h
  ios/Pods/Headers/Private/rn-fetch-blob/RNFetchBlobNetwork.h
  ios/Pods/Headers/Private/rn-fetch-blob/RNFetchBlobProgress.h
  ios/Pods/Headers/Private/rn-fetch-blob/RNFetchBlobReqBuilder.h
  ios/Pods/Headers/Private/rn-fetch-blob/RNFetchBlobRequest.h
  ios/Pods/Headers/Public/rn-fetch-blob/IOS7Polyfill.h
  ios/Pods/Headers/Public/rn-fetch-blob/RNFetchBlob.h
  ios/Pods/Headers/Public/rn-fetch-blob/RNFetchBlobConst.h
  ios/Pods/Headers/Public/rn-fetch-blob/RNFetchBlobFS.h
  ios/Pods/Headers/Public/rn-fetch-blob/RNFetchBlobNetwork.h
  ios/Pods/Headers/Public/rn-fetch-blob/RNFetchBlobProgress.h
  ios/Pods/Headers/Public/rn-fetch-blob/RNFetchBlobReqBuilder.h
  ios/Pods/Headers/Public/rn-fetch-blob/RNFetchBlobRequest.h
  ios/Pods/Local Podspecs/rn-fetch-blob.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/Target Support Files/Pods-NotificationService/Pods-NotificationService.debug.xcconfig
  ios/Pods/Target Support Files/Pods-NotificationService/Pods-NotificationService.release.xcconfig
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/rn-fetch-blob/rn-fetch-blob-dummy.m
  ios/Pods/Target Support Files/rn-fetch-blob/rn-fetch-blob-prefix.pch
  ios/Pods/Target Support Files/rn-fetch-blob/rn-fetch-blob.debug.xcconfig
  ios/Pods/Target Support Files/rn-fetch-blob/rn-fetch-blob.release.xcconfig
  package.json
  yarn.lock
Labels: 👀 needs review, 👍 improvement

#2421 [NEW] Show server history
  app/actions/server.js
  app/containers/FormContainer.js
  app/lib/database/index.js
  app/lib/database/model/ServersHistory.js
  app/lib/database/model/serversMigrations.js
  app/lib/database/schema/servers.js
  app/sagas/login.js
  app/sagas/selectServer.js
  app/views/LoginView.js
  app/views/NewServerView/ServerInput/Item.js
  app/views/NewServerView/ServerInput/index.js
  app/views/NewServerView/index.js
  e2e/tests/onboarding/07-server-history.spec.js
Labels: 🎉 feature, 👀 needs review

#2422 [NEW] Toggle analytics events
  app/actions/actionsTypes.js
  app/actions/crashReport.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/lib/rocketchat.js
  app/reducers/crashReport.js
  app/sagas/init.js
  app/utils/log/events.js
  app/views/SettingsView/index.js
Labels: 🎉 feature, 👀 needs review

#2462 [FIX] Local database searches using non-latin characters
  app/containers/MessageBox/index.js
  app/lib/database/utils.js
  app/lib/database/utils.test.js
  app/lib/rocketchat.js
  app/views/NewServerView/index.js
  app/views/SearchMessagesView/index.js
  app/views/ShareListView/index.js
  package.json
  yarn.lock
Labels: 👀 needs review, 🛠 fix

#2464 [FIX] Read receipt crashing in some cases
  app/views/ReadReceiptView/index.js
  app/views/ReadReceiptView/styles.js
Labels: 👀 needs review, 🛠 fix

#2459 [IMPROVEMENT] Add "Allow_Save_Media_to_Gallery" setting
  app/constants/settings.js
  app/views/AttachmentView.js
Labels: 👀 needs review, 👍 improvement

#2468 [FIX] Jitsi breaking changes
  package.json
  patches/react-native-jitsi-meet+2.1.1.patch
  yarn.lock
Labels: 👀 needs review, 👷 ci, 🛠 fix

#2471 [FIX] SanitizeLikeString util crashes for empty strings
  app/lib/database/utils.js
  app/lib/database/utils.test.js
Labels: 👀 needs review, 🛠 fix

#2465 [i18n] Add Traditional Chinese (zh_TW)
  app/i18n/index.js
  app/i18n/locales/zh_TW.js
  app/views/LanguageView/index.js
Labels: 🌎 i18n, 🚨 needs changes

#2466 [I18n] Improve Simplified Chinese (zh_CN)
  app/i18n/locales/zh-CN.js
Labels: 🌎 i18n, 👍 improvement, 🚨 needs changes

#2472 [CHORE] Simplify i18n files
  app/i18n/index.js
  app/i18n/locales/zh-TW.js
  app/views/LanguageView/index.js
Labels: 👀 needs review, 👍 improvement, 🚚 chore

#2473 [FIX] Remove assets from share extension on iOS
  ios/RocketChatRN.xcodeproj/project.pbxproj
  ios/ShareRocketChatRN/Images.xcassets/Contents.json
  ios/ShareRocketChatRN/Images.xcassets/Icons/Contents.json
  ios/ShareRocketChatRN/Images.xcassets/Icons/hashtag.imageset/Contents.json
  ios/ShareRocketChatRN/Images.xcassets/Icons/hashtag.imageset/hashtag.png
  ios/ShareRocketChatRN/Images.xcassets/Icons/hashtag.imageset/hashtag@2x.png
  ios/ShareRocketChatRN/Images.xcassets/Icons/hashtag.imageset/hashtag@3x.png
  ios/ShareRocketChatRN/Images.xcassets/Icons/lock.imageset/Contents.json
  ios/ShareRocketChatRN/Images.xcassets/Icons/lock.imageset/lock.png
  ios/ShareRocketChatRN/Images.xcassets/Icons/lock.imageset/lock@2x.png
  ios/ShareRocketChatRN/Images.xcassets/Icons/lock.imageset/lock@3x.png
Labels: 👀 needs review, 🛠 fix

#2483 [CHORE] Change database location to Experimental Apps
  app/lib/database/index.js
  app/lib/encryption/encryption.js
  app/lib/methods/enterpriseModules.js
  app/lib/methods/getSettings.js
  app/sagas/encryption.js
  app/sagas/init.js
  app/sagas/rooms.js
  app/sagas/selectServer.js
Labels: 👀 needs review, 🚚 chore

#2484 [FIX] WatermelonDB caching Date as String
  patches/@nozbe+watermelondb+0.19.0.patch
Labels: 👀 needs review, 🛠 fix

#2481 [NEW] E2E Encryption push (Android)
  .circleci/config.yml
  android/app/src/play/java/chat/rocket/reactnative/Callback.java
  android/app/src/play/java/chat/rocket/reactnative/CustomPushNotification.java
  android/app/src/play/java/chat/rocket/reactnative/DismissNotification.java
  android/app/src/play/java/chat/rocket/reactnative/Ejson.java
  android/app/src/play/java/chat/rocket/reactnative/Encryption.java
  android/app/src/play/java/chat/rocket/reactnative/LoadNotification.java
  android/app/src/play/java/chat/rocket/reactnative/ReplyBroadcast.java
  package.json
  patches/@nozbe+watermelondb+0.19.0.patch
  yarn.lock
Labels: 🎉 feature, 👀 needs review

#2488 [FIX] Language set by web client
  app/i18n/index.js
  app/sagas/login.js
Labels: 👀 needs review, 🛠 fix

#2490 [REGRESSION] HTTP Basic Auth
  app/lib/rocketchat.js
Labels: 👀 needs review, 🛠 fix

#2493 [FIX] Logout when install fresh Official and Experimental iOS app
  ios/RocketChatRN/AppDelegate.m
Labels: 👀 needs review, 🛠 fix

#2494 [FIX] Show images in iOS 14
  patches/react-native+0.63.1.patch
Labels: 👀 needs review, 🛠 fix

#2510 [REGRESSION] SSL Pinning stopped working after #2449
  patches/react-native+0.63.1.patch
  patches/react-native-webview+10.3.2.patch
  patches/rn-fetch-blob+0.12.0.patch
Labels: 👀 needs review, 🛠 fix
