Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2020-05, with the labels that each got.

#2085 [FIX] ReactionsModal
  app/containers/message/Emoji.js
Labels: 👀 needs review, 🛠 fix

#1975 [NEW] Delete Server
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/lib/database/index.js
  app/lib/methods/logout.js
  app/lib/rocketchat.js
  app/presentation/UserItem.js
  app/utils/longPress.js
  app/utils/url.js
  app/views/RoomsListView/ServerDropdown.js
Labels: 🎉 feature, 👀 needs review

#1981 [IMPROVEMENT] Change server while connecting/updating
  app/lib/rocketchat.js
  app/sagas/selectServer.js
  app/utils/fetch.js
  app/views/RoomsListView/Header/Header.ios.js
  package.json
  patches/@rocket.chat+sdk+1.0.0-dj.15.patch
  yarn.lock
Labels: 👀 needs review, 👍 improvement

#2088 [FIX] UIKit crashing when UIKitModal receive update event
  app/views/ModalBlockView.js
  package.json
  yarn.lock
Labels: 👀 needs review, 🛠 fix

#2064 [IMPROVEMENT] Close announcement banner
  app/lib/database/model/Subscription.js
  app/lib/database/model/migrations.js
  app/lib/database/schema/app.js
  app/lib/methods/helpers/findSubscriptionsRooms.js
  app/lib/methods/subscriptions/rooms.js
  app/sagas/rooms.js
  app/views/RoomView/Banner.js
  app/views/RoomView/index.js
  app/views/RoomView/styles.js
Labels: 👍 improvement

#2090 [FIX] Messages View
  app/containers/message/Audio.js
  app/containers/message/Reply.js
  app/views/MessagesView/index.js
  app/views/SearchMessagesView/index.js
Labels: 🛠 fix

#2072 [FIX] Big names overflow
  app/containers/message/User.js
  app/presentation/UserItem.js
  app/views/RoomActionsView/index.js
  app/views/RoomActionsView/styles.js
  app/views/RoomInfoView/styles.js
  app/views/RoomView/Header/Header.js
  app/views/RoomsListView/Header/Header.android.js
  app/views/RoomsListView/Header/Header.ios.js
  app/views/RoomsListView/ServerDropdown.js
  app/views/SidebarView/SidebarItem.js
Labels: 👀 needs review, 🛠 fix

#2038 [FIX] Avatar of message as an emoji
  app/containers/Avatar.js
  app/containers/markdown/Emoji.js
  app/containers/markdown/index.js
  app/containers/message/MessageAvatar.js
  app/containers/message/index.js
  app/lib/database/model/Message.js
  app/lib/database/model/Thread.js
  app/lib/database/model/ThreadMessage.js
  app/lib/database/model/migrations.js
  app/lib/database/schema/app.js
Labels: 🛠 fix

#2004 [NEW] Livechat
  app/actions/actionsTypes.js
  app/actions/room.js
  app/constants/settings.js
  app/containers/LoginServices.js
  app/containers/OrSeparator.js
  app/containers/RoomTypeIcon.js
  app/containers/TextInput.js
  app/containers/UIKit/MultiSelect/Chips.js
  app/containers/UIKit/MultiSelect/Input.js
  app/containers/UIKit/MultiSelect/index.js
  app/containers/message/User.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/index.js
  app/lib/database/model/Room.js
  app/lib/database/model/Subscription.js
  app/lib/database/model/migrations.js
  app/lib/database/schema/app.js
  app/lib/methods/helpers/findSubscriptionsRooms.js
  app/lib/methods/helpers/mergeSubscriptionsRooms.js
  app/lib/methods/subscriptions/rooms.js
  app/lib/rocketchat.js
  app/presentation/RoomItem/TypeIcon.js
  app/presentation/RoomItem/index.js
  app/reducers/room.js
  app/sagas/room.js
  app/views/ForwardLivechatView.js
  app/views/LivechatEditView.js
  app/views/NewServerView.js
  app/views/PickerView.js
  app/views/RoomActionsView/index.js
  app/views/RoomInfoView/Channel.js
  app/views/RoomInfoView/CustomFields.js
  app/views/RoomInfoView/Direct.js
  app/views/RoomInfoView/Item.js
  app/views/RoomInfoView/Livechat.js
  app/views/RoomInfoView/Timezone.js
  app/views/RoomInfoView/index.js
  app/views/RoomView/Header/Icon.js
  app/views/RoomView/Header/index.js
  app/views/RoomView/index.js
  app/views/RoomsListView/index.js
  app/views/VisitorNavigationView.js
  package.json
  yarn.lock
Labels: 🎉 feature, 🚨 needs changes

#2091 [FIX] Delete Subs
  app/sagas/rooms.js
Labels: 👀 needs review, 🛠 fix

#2093 [FIX] Blink header DM
  app/views/RoomInfoView/index.js
  app/views/RoomView/index.js
Labels: 👀 needs review, 🛠 fix

#2095 [FIX] Default biometry enabled
  app/views/ScreenLockConfigView.js
Labels: 👀 needs review, 🛠 fix

#2115 [IMPROVEMENT] Enable navigating to a room from auth deep linking
  app/sagas/deepLinking.js
Labels: 👀 needs review, 👍 improvement

#2116 [FIX] NewMessageView Press Item should open DM
  app/utils/goRoom.js
  app/views/NewMessageView.js
  app/views/RoomsListView/index.js
Labels: 👀 needs review, 🛠 fix

#2110 [FIX] Roles
  app/lib/rocketchat.js
Labels: 👀 needs review, 🛠 fix

#2111 [FIX] Wait attach activity before changeNavigationBarColor
  app/utils/theme.js
Labels: 👀 needs review, 🛠 fix

#2117 [FIX] UIKit crash when some app send a list
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/UIKit/Section.js
  app/containers/UIKit/index.js
  storybook/stories/Message.js
  storybook/stories/UiKitMessage.js
  storybook/stories/index.js
Labels: 👀 needs review, 🛠 fix

#2130 [FIX] Change bar color while no activity attached
  patches/react-native-navigation-bar-color+2.0.1.patch
Labels: 👀 needs review, 🛠 fix

#2120 [FIX] Screen Lock options i18n
  app/constants/localAuthentication.js
  app/lib/methods/getSettings.js
  app/views/ScreenLockConfigView.js
Labels: 👀 needs review, 🛠 fix

#2131 [FIX] Sometimes SDK is null when try to connect
  app/lib/rocketchat.js
Labels: 👀 needs review, 🛠 fix

#2106 [FIX] Autocomplete position on Android
  app/containers/MessageBox/index.js
Labels: 👀 needs review, 🛠 fix

#2136 Revert "[FIX] Autocomplete position on Android"
  app/containers/MessageBox/index.js
Labels: 👀 needs review, 🛠 fix

#2137 [FIX] Here and all mentions shouldn't refer to users
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/markdown/AtMention.js
Labels: 👀 needs review, 🛠 fix

#2133 [FIX] No send data to bugsnag if it's an aborted request
  app/utils/log.js
Labels: 👀 needs review, 🛠 fix

#2126 [TESTS] Update and separate E2E tests
  .circleci/config.yml
  README.md
  app/containers/FormContainer.js
  app/containers/TwoFactor/index.js
  app/sagas/messages.js
  app/views/ForgotPasswordView.js
  app/views/LoginView.js
  app/views/NewServerView.js
  app/views/OnboardingView/index.js
  app/views/RegisterView.js
  app/views/RoomInfoView/Channel.js
  app/views/RoomInfoView/Item.js
  app/views/SidebarView/index.js
  app/views/WorkspaceView/index.js
  e2e/00-onboarding.spec.js
  e2e/01-welcome.spec.js
  e2e/02-legal.spec.js
  e2e/helpers/app.js
  e2e/tests/assorted/01-changeserver.spec.js
  e2e/tests/assorted/02-broadcast.spec.js
  e2e/tests/assorted/03-profile.spec.js
  e2e/tests/assorted/04-setting.spec.js
  e2e/tests/assorted/05-joinpublicroom.spec.js
  e2e/tests/assorted/06-status.spec.js
  e2e/tests/assorted/init.js
  e2e/tests/onboarding/01-onboarding.spec.js
  e2e/tests/onboarding/02-legal.spec.js
  e2e/tests/onboarding/03-forgotpassword.spec.js
  e2e/tests/onboarding/04-createuser.spec.js
  e2e/tests/onboarding/05-login.spec.js
  e2e/tests/onboarding/06-roomslist.spec.js
  e2e/tests/onboarding/init.js
  e2e/tests/room/01-createroom.spec.js
  e2e/tests/room/02-room.spec.js
  e2e/tests/room/03-roomactions.spec.js
  e2e/tests/room/04-roominfo.spec.js
  e2e/tests/room/init.js
  package.json
  yarn.lock
Labels: ✅ tests, 👀 needs review

#2141 [FIX] Screen Lock Time respect local value
  app/lib/methods/getSettings.js
  app/views/ScreenLockConfigView.js
Labels: 👀 needs review, 🛠 fix

#2147 Bump version to 4.8.0
  android/app/build.gradle
  ios/RocketChatRN/Info.plist
  ios/ShareRocketChatRN/Info.plist
Labels: 🚚 chore
