Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2020-02, with the labels that each got.

#1627 [NEW] Request review
  README.md
  app/constants/links.js
  app/containers/MessageBox/index.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/utils/review.js
  app/views/CreateChannelView.js
  app/views/RoomView/index.js
  app/views/SettingsView/index.js
Labels: 🎉 feature, 👀 needs review

#1657 [NEW] Pull to refresh RoomView
  app/views/RoomView/List.js
Labels: 🎉 feature, 👀 needs review

#1655 [FIX] Unsubscribe from room
  app/lib/methods/subscriptions/room.js
  app/lib/rocketchat.js
  app/views/RoomView/index.js
Labels: 👀 needs review, 🛠 fix

#1660 [NEW] Clear cache
  app/actions/login.js
  app/i18n/locales/en.js
  app/lib/rocketchat.js
  app/sagas/init.js
  app/sagas/login.js
  app/views/SettingsView/index.js
  app/views/SettingsView/styles.js
  app/views/SidebarView/index.js
Labels: 🎉 feature

#1642 [IMPROVEMENT] Memoize and batch subscriptions updates
  app/lib/methods/subscriptions/rooms.js
  app/sagas/rooms.js
Labels: 👍 improvement, 🚀 performance

#1664 [FIX] Disallow empty sharing
  app/containers/MessageActions.js
  app/views/InviteUsersView/index.js
  app/views/RoomActionsView/index.js
Labels: 👀 needs review, 🛠 fix

#1663 [REGRESSION] Use HTTPS links for sharing and markets protocol for review
  app/constants/links.js
Labels: 👀 needs review, 🛠 fix

#1649 [FIX] In some cases, share extension doesn't load images
  app/views/ShareListView/index.js
Labels: 👀 needs review, 🛠 fix

#1631 [i18n] DE translations for new invite function and some minor fixes
  app/i18n/locales/de.js
Labels: 🌎 i18n, 👀 needs review

#1628 [FIX] remove duplicate jetify step
  .circleci/config.yml
Labels: 👀 needs review, 👷 ci

#1672 [FIX] Notifications crash on older Android Versions
  android/app/src/main/java/chat/rocket/reactnative/CustomPushNotification.java
Labels: 👀 needs review, 🛠 fix

#1676 [i18n] Added Dutch translation
  app/i18n/index.js
  app/i18n/locales/nl.js
  app/views/LanguageView/index.js
Labels: 🌎 i18n

#1674 [NEW] Omnichannel Beta
  android/app/src/main/res/drawable-hdpi/livechat.png
  android/app/src/main/res/drawable-mdpi/livechat.png
  android/app/src/main/res/drawable-xhdpi/livechat.png
  android/app/src/main/res/drawable-xxhdpi/livechat.png
  android/app/src/main/res/drawable-xxxhdpi/livechat.png
  app/containers/RoomTypeIcon.js
  app/lib/rocketchat.js
  app/notifications/push/index.js
  app/sagas/deepLinking.js
  app/views/RoomActionsView/index.js
  app/views/RoomInfoView/index.js
  app/views/RoomView/Header/Icon.js
  app/views/RoomsListView/index.js
  ios/RocketChatRN/Images.xcassets/Icons/livechat.imageset/Contents.json
  ios/RocketChatRN/Images.xcassets/Icons/livechat.imageset/livechat.png
  ios/RocketChatRN/Images.xcassets/Icons/livechat.imageset/livechat@2x.png
  ios/RocketChatRN/Images.xcassets/Icons/livechat.imageset/livechat@3x.png
Labels: 🎉 feature, 👀 needs review

#1688 [NEW] Confirm logout/clear cache
  app/containers/MessageActions.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/utils/info.js
  app/views/SettingsView/index.js
Labels: 🎉 feature, 👀 needs review

#1696 [IMPROVEMENT] Use reselect
  app/containers/MessageBox/EmojiKeyboard.js
  app/containers/MessageBox/ReplyPreview.js
  app/containers/MessageBox/index.js
  app/lib/methods/sendFileMessage.js
  app/notifications/inApp/index.js
  app/selectors/login.js
  app/views/AdminPanelView/index.js
  app/views/AttachmentView.js
  app/views/CreateChannelView.js
  app/views/DirectoryView/index.js
  app/views/LanguageView/index.js
  app/views/MessagesView/index.js
  app/views/NewMessageView.js
  app/views/ProfileView/index.js
  app/views/ReadReceiptView/index.js
  app/views/RoomActionsView/index.js
  app/views/RoomInfoView/index.js
  app/views/RoomMembersView/index.js
  app/views/RoomView/Header/RightButtons.js
  app/views/RoomView/Header/index.js
  app/views/RoomView/ReactionPicker.js
  app/views/RoomView/index.js
  app/views/RoomsListView/index.js
  app/views/SearchMessagesView/index.js
  app/views/SelectedUsersView.js
  app/views/SetUsernameView.js
  app/views/SettingsView/index.js
  app/views/ShareListView/index.js
  app/views/ShareView/index.js
  app/views/SidebarView/index.js
  app/views/ThreadMessagesView/index.js
  package.json
  yarn.lock
Labels: 👀 needs review, 👍 improvement

#1692 [FIX] Notification in Android API level less than 24
  android/app/src/main/java/chat/rocket/reactnative/CustomPushNotification.java
Labels: 👀 needs review, 🛠 fix

#1698 [IMPROVEMENT] Send tmid on slash commands and media
  app/containers/MessageBox/index.js
  app/lib/rocketchat.js
Labels: 👀 needs review, 👍 improvement

#1703 [FIX] Unhandled action on UIKit
  app/containers/UIKit/utils.js
  app/lib/methods/actions.js
Labels: 👀 needs review, 🛠 fix

#1701 [NEW] Pull to refresh RoomsList
  app/actions/actionsTypes.js
  app/actions/rooms.js
  app/reducers/rooms.js
  app/sagas/rooms.js
  app/views/RoomView/List.js
  app/views/RoomsListView/index.js
Labels: 🎉 feature, 👀 needs review

#1702 [IMPROVEMENT] Reset app when change language
  app/views/LanguageView/index.js
Labels: 👀 needs review, 👍 improvement

#1709 [FIX] Small Fixes on UiKit
  app/actions/notification.js
  app/containers/UIKit/MultiSelect/Items.js
  app/containers/UIKit/MultiSelect/styles.js
  app/containers/UIKit/Overflow.js
  app/containers/markdown/Table.js
  app/lib/methods/actions.js
  app/lib/methods/subscriptions/rooms.js
  app/lib/rocketchat.js
  app/notifications/inApp/index.js
  app/views/ModalBlockView.js
  app/views/RoomsListView/index.js
Labels: 👀 needs review, 🛠 fix

#1719 [FIX] Spotlight
  app/containers/SearchBox.js
  app/lib/rocketchat.js
  app/views/RoomsListView/Header/index.js
  app/views/RoomsListView/ListHeader/Directory.js
  app/views/RoomsListView/ListHeader/SearchBar.js
  app/views/RoomsListView/ListHeader/Sort.js
  app/views/RoomsListView/ListHeader/index.js
  app/views/RoomsListView/index.js
Labels: 👀 needs review, 🛠 fix

#1720 [FIX] Messages Overlapping (Android) and MessageBox Scroll (iOS)
  android/app/build.gradle
  android/app/src/main/java/chat/rocket/reactnative/MainApplication.java
  android/settings.gradle
  app/containers/MessageBox/EmojiKeyboard.js
  app/containers/MessageBox/LeftButtons.android.js
  app/containers/MessageBox/LeftButtons.js
  app/containers/MessageBox/RightButtons.android.js
  app/containers/MessageBox/RightButtons.js
  app/containers/MessageBox/buttons/ToggleEmojiButton.js
  app/containers/MessageBox/buttons/index.js
  app/containers/MessageBox/index.js
  app/containers/MessageBox/styles.js
  app/containers/message/index.js
  ios/Podfile.lock
  ios/Pods/Headers/Private/react-native-keyboard-input/Color+Interpolation.h
  ios/Pods/Headers/Private/react-native-keyboard-input/LNAnimator.h
  ios/Pods/Headers/Private/react-native-keyboard-input/LNInterpolable.h
  ios/Pods/Headers/Private/react-native-keyboard-input/LNInterpolation.h
  ios/Pods/Headers/Private/react-native-keyboard-input/NSValue+Interpolation.h
  ios/Pods/Headers/Private/react-native-keyboard-input/RCTCustomInputController.h
  ios/Pods/Headers/Private/react-native-keyboard-input/RCTCustomKeyboardViewController.h
  ios/Pods/Headers/Public/react-native-keyboard-input/Color+Interpolation.h
  ios/Pods/Headers/Public/react-native-keyboard-input/LNAnimator.h
  ios/Pods/Headers/Public/react-native-keyboard-input/LNInterpolable.h
  ios/Pods/Headers/Public/react-native-keyboard-input/LNInterpolation.h
  ios/Pods/Headers/Public/react-native-keyboard-input/NSValue+Interpolation.h
  ios/Pods/Headers/Public/react-native-keyboard-input/RCTCustomInputController.h
  ios/Pods/Headers/Public/react-native-keyboard-input/RCTCustomKeyboardViewController.h
  ios/Pods/Local Podspecs/RNSharedElement.podspec.json
  ios/Pods/Local Podspecs/react-native-keyboard-input.podspec.json
  ios/Pods/Local Podspecs/react-native-keyboard-tracking-view.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/react-native-keyboard-input/react-native-keyboard-input-dummy.m
  ios/Pods/Target Support Files/react-native-keyboard-input/react-native-keyboard-input-prefix.pch
  ios/Pods/Target Support Files/react-native-keyboard-input/react-native-keyboard-input.xcconfig
  package.json
  patches/react-native-keyboard-input+5.3.1.patch
  patches/react-native-keyboard-tracking-view+5.6.1.patch
  react-native.config.js
  yarn.lock
Labels: 👀 needs review, 🛠 fix

#1721 [REGRESSION] Remove @ and # from mention
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/markdown/AtMention.js
  app/containers/markdown/Hashtag.js
Labels: 👀 needs review, 🛠 fix

#1516 [NEW] Direct message from RoomInfo
  app/i18n/locales/en.js
  app/views/RoomInfoView/index.js
  app/views/RoomInfoView/styles.js
Labels: 🎉 feature

#1723 [FIX] Delete slash commands
  app/lib/methods/getSlashCommands.js
Labels: 👀 needs review, 🛠 fix

#1684 [IMPROVEMENT] User Can Copy Link On hold
  __mocks__/bugsnag-react-native.js
  __mocks__/react-native-firebase.js
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/markdown/Link.js
  app/containers/message/Urls.js
Labels: 👍 improvement, 🚨 needs changes

#1724 [FIX] Different sourcemaps generation for Hermes
  .circleci/config.yml
  package.json
  yarn.lock
Labels: 👀 needs review, 🚚 chore, 🛠 fix

#1738 [REVERT] Show emoji keyboard on Android
  android/app/build.gradle
  android/app/src/main/java/chat/rocket/reactnative/MainApplication.java
  android/settings.gradle
  app/containers/MessageBox/EmojiKeyboard.js
  app/containers/MessageBox/LeftButtons.android.js
  app/containers/MessageBox/LeftButtons.ios.js
  app/containers/MessageBox/RightButtons.android.js
  app/containers/MessageBox/RightButtons.ios.js
  app/containers/MessageBox/buttons/ToggleEmojiButton.js
  app/containers/MessageBox/buttons/index.js
  app/containers/MessageBox/index.js
  app/containers/MessageBox/styles.js
  app/containers/message/index.js
  ios/Podfile.lock
  ios/Pods/Headers/Private/react-native-keyboard-input/Color+Interpolation.h
  ios/Pods/Headers/Private/react-native-keyboard-input/LNAnimator.h
  ios/Pods/Headers/Private/react-native-keyboard-input/LNInterpolable.h
  ios/Pods/Headers/Private/react-native-keyboard-input/LNInterpolation.h
  ios/Pods/Headers/Private/react-native-keyboard-input/NSValue+Interpolation.h
  ios/Pods/Headers/Private/react-native-keyboard-input/RCTCustomInputController.h
  ios/Pods/Headers/Private/react-native-keyboard-input/RCTCustomKeyboardViewController.h
  ios/Pods/Headers/Public/react-native-keyboard-input/Color+Interpolation.h
  ios/Pods/Headers/Public/react-native-keyboard-input/LNAnimator.h
  ios/Pods/Headers/Public/react-native-keyboard-input/LNInterpolable.h
  ios/Pods/Headers/Public/react-native-keyboard-input/LNInterpolation.h
  ios/Pods/Headers/Public/react-native-keyboard-input/NSValue+Interpolation.h
  ios/Pods/Headers/Public/react-native-keyboard-input/RCTCustomInputController.h
  ios/Pods/Headers/Public/react-native-keyboard-input/RCTCustomKeyboardViewController.h
  ios/Pods/Local Podspecs/RNSharedElement.podspec.json
  ios/Pods/Local Podspecs/react-native-keyboard-input.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/react-native-keyboard-input/react-native-keyboard-input-dummy.m
  ios/Pods/Target Support Files/react-native-keyboard-input/react-native-keyboard-input-prefix.pch
  ios/Pods/Target Support Files/react-native-keyboard-input/react-native-keyboard-input.xcconfig
  package.json
  patches/react-native-keyboard-input+5.3.1.patch
  react-native.config.js
  yarn.lock
Labels: 👀 needs review, 🛠 fix

#1745 [FIX] Stop logging react-native-image-crop-picker
  app/containers/MessageBox/index.js
Labels: 👀 needs review, 🚚 chore

#1744 [FIX] Prevent toast ref error
  app/containers/Toast.js
Labels: 👀 needs review, 🛠 fix

#1741 [FIX] Add missing calls to user info
  app/containers/message/MessageAvatar.js
  app/containers/message/index.js
  app/views/MessagesView/index.js
  app/views/SearchMessagesView/index.js
Labels: 👀 needs review, 🛠 fix

#1742 [FIX] UIKit Modal: Weird behavior on Android Tablet
  app/index.js
  app/views/ModalBlockView.js
Labels: 👀 needs review, 🛠 fix

#1725 [IMPROVEMENT] Alert verify email when enabled
  app/constants/settings.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/views/RegisterView.js
Labels: 👍 improvement

#1746 [NEW] Jitsi JWT added to URL
  app/constants/settings.js
  app/lib/methods/callJitsi.js
  app/views/JitsiMeetView.js
  ios/Podfile.lock
  ios/Pods/Local Podspecs/react-native-jitsi-meet.podspec.json
  ios/Pods/Manifest.lock
  yarn.lock
Labels: 🎉 feature, 👀 needs review

#1748 [FIX] UIKit submit when connection lost
  app/lib/Navigation.js
  app/lib/methods/actions.js
  app/views/ModalBlockView.js
Labels: 👀 needs review, 🛠 fix

#1752 [NEW] Default browser
  README.md
  __mocks__/rn-user-defaults.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/index.js
  app/utils/openLink.js
  app/views/DefaultBrowserView.js
  app/views/SettingsView/index.js
  ios/RocketChatRN/Info.plist
Labels: 🎉 feature, 👀 needs review

#1753 [FIX] HTTP Basic Auth
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/Avatar.js
  app/lib/methods/actions.js
  app/lib/methods/sendFileMessage.js
  app/lib/rocketchat.js
  app/sagas/selectServer.js
  app/utils/fetch.js
  app/views/NewServerView.js
  package.json
  yarn.lock
Labels: 🚨 needs changes, 🛠 fix

#1687 [IMPROVEMENT] Honor profile fields edit settings
  app/constants/settings.js
  app/views/ProfileView/index.js
  app/views/ProfileView/styles.js
Labels: 👀 needs review, 👍 improvement

#1726 [IMPROVEMENT] Room announcements
  app/views/RoomView/index.js
  app/views/RoomView/styles.js
Labels: 👀 needs review, 👍 improvement

#1727 [IMPROVEMENT] Honor Register/Login settings
  app/constants/settings.js
  app/lib/methods/getSettings.js
  app/lib/rocketchat.js
  app/sagas/selectServer.js
  app/views/LoginSignupView.js
  app/views/LoginView.js
Labels: 👀 needs review, 👍 improvement

#1730 Make links clickable
  app/views/RoomInfoView/index.js
Labels: 👀 needs review, 👍 improvement

#1755 [NEW] Hide system messages
  app/constants/settings.js
  app/lib/database/model/Setting.js
  app/lib/database/model/migrations.js
  app/lib/database/schema/app.js
  app/lib/methods/getSettings.js
  app/lib/rocketchat.js
  app/views/RoomView/List.js
  app/views/RoomView/index.js
Labels: 🎉 feature, 👀 needs review

#1764 [IMPROVEMENT] Honor "Message_AudioRecorderEnabled"
  app/constants/settings.js
  app/containers/MessageBox/RightButtons.android.js
  app/containers/MessageBox/RightButtons.ios.js
  app/containers/MessageBox/index.js
Labels: 👀 needs review, 👍 improvement

#1765 [i18n] adds missing German strings
  app/i18n/locales/de.js
Labels: 🌎 i18n, 👀 needs review

#1728 [FIX] Redirect user to SetUsernameView
  app/sagas/init.js
  app/sagas/login.js
  app/views/RegisterView.js
  app/views/SetUsernameView.js
Labels: 👀 needs review, 🛠 fix

#1769 [FIX] Join Room
  app/sagas/createChannel.js
  app/views/RoomView/index.js
Labels: 👀 needs review, 🛠 fix

#1770 [FIX] Accept all media types using *
  app/utils/media.js
Labels: 👀 needs review, 🛠 fix

#1758 [FIX] Use RealName when necessary
  app/containers/markdown/AtMention.js
  app/containers/markdown/index.js
  app/containers/message/Content.js
  app/lib/methods/subscriptions/rooms.js
  app/presentation/RoomItem/LastMessage.js
  app/presentation/RoomItem/index.js
  app/views/RoomInfoView/index.js
  app/views/RoomView/index.js
  app/views/RoomsListView/index.js
  app/views/SidebarView/index.js
Labels: 👀 needs review, 🛠 fix

#1783 [FIX] Markdown Line Break
  yarn.lock
Labels: 👀 needs review, 🛠 fix

#1774 [IMPROVEMENT] Remove useMarkdown
  app/actions/actionsTypes.js
  app/actions/markdown.js
  app/containers/MessageBox/ReplyPreview.js
  app/containers/markdown/index.js
  app/containers/message/Attachments.js
  app/containers/message/Audio.js
  app/containers/message/Content.js
  app/containers/message/Image.js
  app/containers/message/Reply.js
  app/containers/message/Video.js
  app/containers/message/index.js
  app/i18n/locales/de.js
  app/i18n/locales/en.js
  app/i18n/locales/es-ES.js
  app/i18n/locales/it.js
  app/i18n/locales/nl.js
  app/i18n/locales/pt-BR.js
  app/i18n/locales/ru.js
  app/lib/rocketchat.js
  app/reducers/index.js
  app/reducers/markdown.js
  app/sagas/init.js
  app/views/RoomInfoView/index.js
  app/views/RoomView/index.js
  app/views/SettingsView/index.js
  e2e/14-setting.spec.js
Labels: 👀 needs review, 👍 improvement

#1788 [IMPROVEMENT] Open browser when try to Create Workspace
  app/views/OnboardingView/index.js
Labels: 👀 needs review, 👍 improvement

#1796 [IMPROVEMENT] Markdown perf
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/markdown/AtMention.js
  app/containers/markdown/Hashtag.js
  app/containers/markdown/Link.js
  app/containers/markdown/index.js
  app/containers/markdown/mergeTextNodes.js
  app/presentation/RoomItem/LastMessage.js
Labels: 👀 needs review, 👍 improvement

#1787 [FIX] Stop video when modal is closed
  app/views/AttachmentView.js
Labels: 👀 needs review, 🛠 fix

#1771 [FIX] Hide reply notification action when there are missing data
  android/app/src/main/java/chat/rocket/reactnative/CustomPushNotification.java
  android/app/src/main/java/chat/rocket/reactnative/Ejson.java
Labels: 👀 needs review, 🛠 fix

#1772 [FIX] Reset password error message
  app/views/ForgotPasswordView.js
Labels: 👀 needs review, 🛠 fix

#1773 [FIX] Close tablet modal
  app/index.js
Labels: 👀 needs review, 🛠 fix

#1775 [FIX] Setting not present
  app/lib/rocketchat.js
Labels: 👀 needs review, 🛠 fix

#1776 [FIX] Thread header
  app/views/RoomView/index.js
Labels: 👀 needs review, 🛠 fix

#1784 [FIX] Keyboard Tracking loses input ref
  app/containers/MessageBox/index.js
  app/views/RoomView/index.js
  ios/Podfile.lock
  ios/Pods/Local Podspecs/react-native-keyboard-input.podspec.json
  ios/Pods/Manifest.lock
  patches/react-native-keyboard-input+5.4.1.patch
  patches/react-native-keyboard-tracking-view+5.6.1.patch
  yarn.lock
Labels: 👀 needs review, 🛠 fix

#1785 [NEW] Mark message as unread
  app/containers/MessageActions.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/lib/rocketchat.js
  app/views/RoomView/index.js
Labels: 🎉 feature, 👀 needs review

#1786 [IMPROVEMENT] Log server version
  app/sagas/selectServer.js
  app/utils/log.js
Labels: 👍 improvement

#1798 [IMPROVEMENT] Add loading message on long running tasks
  app/actions/index.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/sagas/init.js
  app/sagas/login.js
  app/views/AuthLoadingView.js
  app/views/LanguageView/index.js
  app/views/SettingsView/index.js
Labels: 👀 needs review, 👍 improvement
