Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2020-07, with the labels that each got.

#2237 [FIX] Read receipt icon on action sheet
  app/containers/MessageActions/index.js
Labels: 👀 needs review, 🛠 fix

#2238 [FIX] Android crashing when restoring from background
  android/app/src/main/java/chat/rocket/reactnative/MainActivity.java
  app/views/RoomsListView/index.js
Labels: 🛠 fix

#2242 [FIX] Send thread attachment
  app/containers/MessageBox/index.js
  app/views/ShareView/Header.js
  app/views/ShareView/index.js
Labels: 👀 needs review, 🛠 fix

#2241 [FIX] Iframe auth Login Button
  app/selectors/login.js
Labels: 👀 needs review, 🛠 fix

#2240 [REGRESSION] Audio Recording
  app/containers/MessageBox/Recording.js
Labels: 👀 needs review, 🛠 fix

#2195 Audio-Enhancements: Expo-av audio recorder
  app/containers/MessageBox/RecordAudio.js
  app/containers/MessageBox/Recording.js
  app/containers/MessageBox/RightButtons.android.js
  app/containers/MessageBox/RightButtons.ios.js
  app/containers/MessageBox/buttons/AudioButton.js
  app/containers/MessageBox/buttons/index.js
  app/containers/MessageBox/index.js
  app/containers/MessageBox/styles.js
  app/containers/message/Audio.js
  ios/Podfile.lock
  ios/Pods/Headers/Private/RNAudio/AudioRecorderManager.h
  ios/Pods/Headers/Public/RNAudio/AudioRecorderManager.h
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/RNAudio/RNAudio-dummy.m
  ios/Pods/Target Support Files/RNAudio/RNAudio-prefix.pch
  ios/Pods/Target Support Files/RNAudio/RNAudio.xcconfig
  package.json
  yarn.lock
Labels: 👍 improvement, 🚨 needs changes

#2234 [IMPROVEMENT] Unified header UX
  app/constants/colors.js
  app/containers/DisclosureIndicator.js
  app/containers/Header/index.js
  app/containers/HeaderButton.js
  app/containers/SearchBox.js
  app/containers/StatusBar.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/views/RoomView/Header/Header.js
  app/views/RoomView/Header/Icon.js
  app/views/RoomView/Header/LeftButtons.js
  app/views/RoomView/Header/RightButtons.js
  app/views/RoomView/Header/index.js
  app/views/RoomView/index.js
  app/views/RoomsListView/Header/Header.ios.js
  app/views/RoomsListView/Header/Header.js
  app/views/RoomsListView/Header/index.js
  app/views/RoomsListView/ListHeader/SearchBar.js
  app/views/RoomsListView/ListHeader/index.js
  app/views/RoomsListView/index.js
  app/views/RoomsListView/styles.js
  e2e/helpers/app.js
  e2e/tests/assorted/02-broadcast.spec.js
  e2e/tests/assorted/05-joinpublicroom.spec.js
  e2e/tests/onboarding/06-roomslist.spec.js
  e2e/tests/room/02-room.spec.js
  e2e/tests/room/03-roomactions.spec.js
  e2e/tests/room/04-roominfo.spec.js
  patches/react-navigation-header-buttons+3.0.5.patch
Labels: 👀 needs review, 👍 improvement

#2230 [FIX] Check for UI_Use_Real_Name when sorting rooms
  app/views/RoomsListView/index.js
Labels: 🛠 fix

#2251 [FIX] Emoji keyboard not showing custom and frequently used emojis on Share Extension
  app/containers/MessageBox/EmojiKeyboard.js
  app/lib/database/index.js
  app/lib/rocketchat.js
Labels: 👀 needs review, 🛠 fix

#2252 [FIX] Scroll to top crashing when ref is undefined
  app/views/RoomView/index.js
  app/views/RoomsListView/index.js
Labels: 👀 needs review, 🛠 fix

#2253 [FIX] AttachmentView crashing during title decode
  app/views/AttachmentView.js
Labels: 👀 needs review, 🛠 fix

#2254 [FIX] Command previews crashing when API returns an error
  app/containers/MessageBox/index.js
Labels: 👀 needs review, 🛠 fix

#2255 [FIX] ThreadMessagesView throwing error when subscription wasn't found
  app/views/ThreadMessagesView/index.js
Labels: 👀 needs review, 🛠 fix

#2256 [FIX] Register crashing when error data is undefined
  app/views/RegisterView.js
Labels: 👀 needs review, 🛠 fix

#2257 [FIX] Get active route returning undefined
  app/utils/navigation/index.js
  app/views/SidebarView/index.js
Labels: 👀 needs review, 🛠 fix

#2261 [FIX] ImageViewer not recognising gestures after zoomed
  app/presentation/ImageViewer/ImageViewer.android.js
Labels: 👀 needs review, 🛠 fix

#2260 [FIX] Android stack animation throwing illegal node ID
  app/utils/navigation/animations.js
Labels: 👀 needs review, 🛠 fix

#2259 [FIX] Navigation object undefined when tapping sidebar's user header on tablet
  app/views/SidebarView/index.js
Labels: 👀 needs review, 🛠 fix

#2263 [FIX] Action sheet cutting emojis on the header
  app/containers/ActionSheet/styles.js
  app/containers/MessageActions/Header.js
  app/containers/MessageActions/index.js
Labels: 👀 needs review, 🛠 fix

#2264 [FIX] Mime type check crashing the app
  app/views/ShareView/index.js
Labels: 👀 needs review, 🛠 fix

#2262 [FIX] Notification preferences update crashing the app
  app/views/NotificationPreferencesView/index.js
Labels: 👀 needs review, 🛠 fix

#2265 [FIX] Create discussion not working from MessageActions
  app/containers/MessageActions/index.js
Labels: 👀 needs review, 🛠 fix

#2271 [FIX] getSettings not catching errors
  app/lib/methods/getSettings.js
Labels: 👀 needs review, 🛠 fix

#2277 [REGRESSION] Jitsi Call doesn't send message link
  app/lib/rocketchat.js
Labels: 👀 needs review, 🛠 fix

#2269 [CHORE] CircleCI Upgrades
  .circleci/config.yml
Labels: 👷 ci, 🚚 chore

#2282 [NEW] Sign in with Apple
  app/containers/LoginServices.js
  app/lib/rocketchat.js
  ios/Podfile.lock
  ios/Pods/Headers/Private/EXAppleAuthentication/EXAppleAuthentication.h
  ios/Pods/Headers/Private/EXAppleAuthentication/EXAppleAuthenticationButton.h
  ios/Pods/Headers/Private/EXAppleAuthentication/EXAppleAuthenticationMappings.h
  ios/Pods/Headers/Private/EXAppleAuthentication/EXAppleAuthenticationRequest.h
  ios/Pods/Headers/Public/EXAppleAuthentication/EXAppleAuthentication.h
  ios/Pods/Headers/Public/EXAppleAuthentication/EXAppleAuthenticationButton.h
  ios/Pods/Headers/Public/EXAppleAuthentication/EXAppleAuthenticationMappings.h
  ios/Pods/Headers/Public/EXAppleAuthentication/EXAppleAuthenticationRequest.h
  ios/Pods/Local Podspecs/EXAppleAuthentication.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/Target Support Files/EXAppleAuthentication/EXAppleAuthentication-dummy.m
  ios/Pods/Target Support Files/EXAppleAuthentication/EXAppleAuthentication-prefix.pch
  ios/Pods/Target Support Files/EXAppleAuthentication/EXAppleAuthentication.xcconfig
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.release.xcconfig
  ios/RocketChatRN.xcodeproj/project.pbxproj
  ios/RocketChatRN/RocketChatRN.entitlements
  package.json
  yarn.lock
Labels: 🎉 feature

#2283 [FIX] MessageBox not being shown on ShareView when Preview is a video
  app/containers/MessageBox/index.js
  app/views/ShareView/Preview.js
Labels: 👀 needs review, 🛠 fix

#2305 Bump version to 4.10.0
  android/app/build.gradle
  ios/RocketChatRN/Info.plist
  ios/ShareRocketChatRN/Info.plist
Labels: 🚚 chore

#2292 [FIX] Room Info actions doesn't check permissions/settings enabled
  app/views/RoomInfoView/index.js
Labels: 👀 needs review, 🛠 fix

#2297 [FIX] Read receipts on tablet
  app/containers/MessageActions/index.js
  app/stacks/MasterDetailStack/index.js
  app/views/ReadReceiptView/index.js
Labels: 🛠 fix

#2300 [IMPROVEMENT] Clear image cache when clear cache
  app/containers/Avatar.js
  app/containers/EmojiPicker/CustomEmoji.js
  app/containers/MessageBox/CommandsPreview/Item.js
  app/containers/UIKit/Image.js
  app/containers/UIKit/MultiSelect/Chips.js
  app/containers/UIKit/MultiSelect/Items.js
  app/containers/message/Image.js
  app/containers/message/Urls.js
  app/presentation/ImageViewer/ImageComponent.js
  app/presentation/ServerItem/index.js
  app/views/SettingsView/index.js
  app/views/WorkspaceView/ServerAvatar.js
  ios/Podfile.lock
  ios/Pods/Headers/Private/RNFastImage/FFFastImageSource.h
  ios/Pods/Headers/Private/RNFastImage/FFFastImageView.h
  ios/Pods/Headers/Private/RNFastImage/FFFastImageViewManager.h
  ios/Pods/Headers/Private/RNFastImage/RCTConvert+FFFastImage.h
  ios/Pods/Headers/Private/SDWebImage/SDWebImageTransitionInternal.h
  ios/Pods/Headers/Public/RNFastImage/FFFastImageSource.h
  ios/Pods/Headers/Public/RNFastImage/FFFastImageView.h
  ios/Pods/Headers/Public/RNFastImage/FFFastImageViewManager.h
  ios/Pods/Headers/Public/RNFastImage/RCTConvert+FFFastImage.h
  ios/Pods/Local Podspecs/RNBootSplash.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/SDWebImage/README.md
  ios/Pods/SDWebImage/SDWebImage/Core/SDAnimatedImageView.h
  ios/Pods/SDWebImage/SDWebImage/Core/SDAnimatedImageView.m
  ios/Pods/SDWebImage/SDWebImage/Core/SDImageCoder.h
  ios/Pods/SDWebImage/SDWebImage/Core/SDImageCoder.m
  ios/Pods/SDWebImage/SDWebImage/Core/SDImageIOAnimatedCoder.m
  ios/Pods/SDWebImage/SDWebImage/Core/SDImageIOCoder.m
  ios/Pods/SDWebImage/SDWebImage/Core/SDWebImageDefine.h
  ios/Pods/SDWebImage/SDWebImage/Core/SDWebImageDefine.m
  ios/Pods/SDWebImage/SDWebImage/Core/SDWebImageDownloaderDecryptor.h
  ios/Pods/SDWebImage/SDWebImage/Core/SDWebImageDownloaderOperation.m
  ios/Pods/SDWebImage/SDWebImage/Core/SDWebImageDownloaderRequestModifier.h
  ios/Pods/SDWebImage/SDWebImage/Core/SDWebImageDownloaderRequestModifier.m
  ios/Pods/SDWebImage/SDWebImage/Core/SDWebImageDownloaderResponseModifier.h
  ios/Pods/SDWebImage/SDWebImage/Core/SDWebImageDownloaderResponseModifier.m
  ios/Pods/SDWebImage/SDWebImage/Core/SDWebImageError.h
  ios/Pods/SDWebImage/SDWebImage/Core/SDWebImageManager.h
  ios/Pods/SDWebImage/SDWebImage/Core/SDWebImageManager.m
  ios/Pods/SDWebImage/SDWebImage/Core/SDWebImageTransition.h
  ios/Pods/SDWebImage/SDWebImage/Core/SDWebImageTransition.m
  ios/Pods/SDWebImage/SDWebImage/Core/UIView+WebCache.m
  ios/Pods/SDWebImage/SDWebImage/Private/SDWebImageTransitionInternal.h
  ios/Pods/SDWebImage/WebImage/SDWebImage.h
  ios/Pods/Target Support Files/RNFastImage/RNFastImage.xcconfig
  ios/RocketChatRN.xcodeproj/project.pbxproj
  package.json
  yarn.lock
Labels: 👀 needs review, 👍 improvement

#2302 [FIX] In-app notification tap when deep in the stack not redirecting to the room
  app/containers/InAppNotification/NotifierComponent.js
Labels: 👀 needs review, 🛠 fix

#2303 [FIX] Markdown preview causes app stuck
  app/containers/markdown/index.js
Labels: 👀 needs review, 🛠 fix

#2306 [CHORE] Update commonmark libs
  yarn.lock
Labels: 👀 needs review, 🚚 chore

#2307 [FIX] MessagesView duplicating content
  app/views/MessagesView/index.js
Labels: 🛠 fix

#2249 [IMPROVEMENT] Native sort and limit queries
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/lib/rocketchat.js
  app/presentation/RoomItem/index.js
  app/views/RoomView/List.js
  app/views/RoomView/index.js
  app/views/RoomsListView/index.js
  app/views/ShareListView/index.js
  package.json
  patches/@nozbe+watermelondb+0.16.2.patch
  storybook/stories/index.js
  yarn.lock
Labels: 👀 needs review, 👍 improvement, 🚀 performance

#2319 [FIX] Style not being applied on RoomsListView header subtitle
  app/views/RoomsListView/Header/Header.js
Labels: 👀 needs review, 🛠 fix

#2331 Revert "[CHORE] Update commonmark.js "
  yarn.lock
Labels: ⬆️ update dependencies, 🛠 fix

#2308 [TESTS] Idempotence for e2e tests
  .circleci/config.yml
  .gitignore
  e2e/data.js
  e2e/data/data.cloud.js
  e2e/data/data.docker.js
  e2e/helpers/app.js
  e2e/helpers/data_setup.js
  e2e/tests/assorted/01-changeserver.spec.js
  e2e/tests/assorted/02-broadcast.spec.js
  e2e/tests/assorted/03-profile.spec.js
  e2e/tests/assorted/04-setting.spec.js
  e2e/tests/assorted/05-joinpublicroom.spec.js
  e2e/tests/assorted/06-status.spec.js
  e2e/tests/init.js
  e2e/tests/onboarding/01-onboarding.spec.js
  e2e/tests/onboarding/02-legal.spec.js
  e2e/tests/onboarding/03-forgotpassword.spec.js
  e2e/tests/onboarding/04-createuser.spec.js
  e2e/tests/onboarding/05-login.spec.js
  e2e/tests/onboarding/06-roomslist.spec.js
  e2e/tests/room/01-createroom.spec.js
  e2e/tests/room/02-room.spec.js
  e2e/tests/room/03-roomactions.spec.js
  e2e/tests/room/04-roominfo.spec.js
  package.json
Labels: ✅ tests, 🚨 needs changes

#2169 [NEW] Log events from Onboarding, NewServer, Login and Register screens
  app/containers/LoginServices.js
  app/sagas/login.js
  app/utils/log/events.js
  app/utils/log/index.js
  app/views/LoginView.js
  app/views/NewServerView.js
  app/views/OnboardingView/index.js
  app/views/RegisterView.js
Labels: 👍 improvement, 🚨 needs changes

#2314 [FIX] Keyboard auto focus on TwoFactor component
  app/containers/TwoFactor/index.js
Labels: 🚨 needs changes, 🛠 fix

#2328 [IMPROVEMENT] TwoFactor component styling
  app/containers/TwoFactor/styles.js
Labels: 👍 improvement, 🚨 needs changes

#2330 [FIX] Admin panel not logging in automatically
  app/views/AdminPanelView/index.js
Labels: 👀 needs review, 🛠 fix

#2320 [CHORE] Skip waiting for build processing on TestFlight upload
  ios/fastlane/Fastfile
Labels: 👀 needs review, 👷 ci, 🚚 chore

#2338 [REGRESSION] Invite links stopped working after #2154
  app/sagas/deepLinking.js
  app/views/NewServerView.js
Labels: 👀 needs review, 🛠 fix

#2332 [TESTS] Fix some simple text
  e2e/data.js
  e2e/data/data.cloud.js
  e2e/data/data.docker.js
  e2e/docker/controlRCDemoEnv.sh
  e2e/tests/assorted/03-profile.spec.js
Labels: ✅ tests

#2294 [FIX] MessagesView title not working
  app/stacks/InsideStack.js
  app/stacks/MasterDetailStack/index.js
  app/views/MessagesView/index.js
Labels: 🚨 needs changes, 🛠 fix

#2318 [CHORE] Update icon names
  android/app/src/main/assets/fonts/custom.ttf
  app/containers/HeaderButton.js
  app/containers/InAppNotification/NotifierComponent.js
  app/containers/MessageActions/Header.js
  app/containers/MessageBox/CommandsPreview/Item.js
  app/containers/MessageBox/RecordAudio.js
  app/containers/MessageBox/ReplyPreview.js
  app/containers/MessageBox/buttons/ActionsButton.js
  app/containers/MessageBox/buttons/CancelEditingButton.js
  app/containers/MessageBox/buttons/SendButton.js
  app/containers/MessageBox/index.js
  app/containers/Passcode/Base/LockIcon.js
  app/containers/ReactionsModal.js
  app/containers/RoomTypeIcon.js
  app/containers/SearchBox.js
  app/containers/TextInput.js
  app/containers/UIKit/MultiSelect/Chips.js
  app/containers/UIKit/Overflow.js
  app/containers/message/Audio.js
  app/containers/message/Broadcast.js
  app/containers/message/CallButton.js
  app/containers/message/Discussion.js
  app/containers/message/Reactions.js
  app/containers/message/Video.js
  app/lib/selection.json
  app/presentation/RoomItem/Actions.js
  app/views/ChangePasscodeView.js
  app/views/DirectoryView/Options.js
  app/views/DirectoryView/index.js
  app/views/LivechatEditView.js
  app/views/NewMessageView.js
  app/views/RoomActionsView/index.js
  app/views/RoomView/Banner.js
  app/views/RoomView/Header/Icon.js
  app/views/RoomView/Header/RightButtons.js
  app/views/RoomView/UploadProgress.js
  app/views/RoomsListView/SortDropdown/index.js
  app/views/RoomsListView/index.js
  app/views/ShareListView/index.js
  app/views/ShareView/Header.js
  app/views/ShareView/Preview.js
  app/views/ShareView/Thumbs.js
  app/views/SidebarView/index.js
  ios/RocketChatRN.xcodeproj/project.pbxproj
  ios/custom.ttf
Labels: 👀 needs review, 🚚 chore

#2340 [CHORE] Move Detox to Github Actions
  .circleci/config.yml
  .github/workflows/ios_detox.yml
Labels: 👷 ci, 🚚 chore

#2213 [NEW] Push notification data privacy
  android/app/src/main/java/chat/rocket/reactnative/Callback.java
  android/app/src/main/java/chat/rocket/reactnative/CustomPushNotification.java
  android/app/src/main/java/chat/rocket/reactnative/Ejson.java
  android/app/src/main/java/chat/rocket/reactnative/LoadNotification.java
  ios/NotificationService/Info.plist
  ios/NotificationService/NotificationService.entitlements
  ios/NotificationService/NotificationService.swift
  ios/RocketChatRN.xcodeproj/project.pbxproj
  ios/RocketChatRN.xcodeproj/xcshareddata/xcschemes/NotificationService.xcscheme
  ios/fastlane/Fastfile
  package.json
  patches/react-native-notifications+2.1.7.patch
  yarn.lock
Labels: 👀 needs review, 👍 improvement

#2351 [IMPROVEMENT] Apply new mention colors
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/constants/colors.js
  app/containers/markdown/AtMention.js
  app/containers/markdown/Hashtag.js
  app/containers/markdown/styles.js
  app/lib/database/model/Subscription.js
  app/lib/database/model/migrations.js
  app/lib/database/schema/app.js
  app/presentation/RoomItem/UnreadBadge.js
  app/presentation/RoomItem/index.js
Labels: 👀 needs review, 👍 improvement

#2353 [FIX] Missing icons
  app/containers/MessageActions/index.js
  app/containers/MessageBox/index.js
  app/views/RoomMembersView/index.js
Labels: 👀 needs review, 🛠 fix

#2354 [FIX] Long press gestures not working properly on Android
  app/presentation/UserItem.js
  app/utils/longPress.js
  app/views/RoomsListView/ServerDropdown.js
Labels: 👀 needs review, 🛠 fix

#2345 [FIX] In-app notification showing while in a Jitsi call
  app/containers/InAppNotification/index.js
Labels: 🚨 needs changes, 🛠 fix

#2347 [CHORE] Only run Flipper in debug via MainApplication is debug
  android/app/src/debug/AndroidManifest.xml
  android/app/src/debug/java/chat/rocket/reactnative/MainDebugApplication.java
  android/app/src/debug/java/chat/rocket/reactnative/ReactNativeFlipper.java
  android/app/src/main/java/chat/rocket/reactnative/MainApplication.java
  android/gradle/wrapper/gradle-wrapper.properties
Labels: 🚚 chore

#2190 [NEW] Log events from RoomsList, SideDrawer and Profile
  app/containers/LoginServices.js
  app/sagas/createChannel.js
  app/sagas/createDiscussion.js
  app/sagas/login.js
  app/utils/log/events.js
  app/views/CreateChannelView.js
  app/views/CreateDiscussionView/index.js
  app/views/DirectoryView/index.js
  app/views/ForgotPasswordView.js
  app/views/LoginView.js
  app/views/NewMessageView.js
  app/views/NewServerView.js
  app/views/OnboardingView/index.js
  app/views/ProfileView/index.js
  app/views/RegisterView.js
  app/views/RoomsListView/Header/index.js
  app/views/RoomsListView/ServerDropdown.js
  app/views/RoomsListView/SortDropdown/index.js
  app/views/RoomsListView/index.js
  app/views/SelectedUsersView.js
  app/views/SidebarView/index.js
Labels: 👍 improvement, 🚨 needs changes

#2223 [IMPROVEMENT] Add deep link to Jitsi calls
  android/app/src/main/AndroidManifest.xml
  app/index.js
  app/lib/database/model/Server.js
  app/lib/database/model/serversMigrations.js
  app/lib/database/schema/servers.js
  app/lib/methods/callJitsi.js
  app/lib/methods/canOpenRoom.js
  app/lib/methods/getSettings.js
  app/notifications/push/index.js
  app/sagas/deepLinking.js
  ios/RocketChatRN/RocketChatRN.entitlements
Labels: 👍 improvement

#2359 [FIX] App hanging on splash screen when deep link params are wrong
  app/sagas/deepLinking.js
Labels: 👀 needs review, 🛠 fix

#2363 [FIX] Vertically centralize RoomItem when `Store_Last_Message` is disabled
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/Status/Status.js
  app/presentation/RoomItem/RoomItem.js
  app/presentation/RoomItem/Title.js
  app/presentation/RoomItem/UpdatedAt.js
  app/presentation/RoomItem/Wrapper.js
  app/presentation/RoomItem/index.js
  app/presentation/RoomItem/styles.js
  storybook/index.js
  storybook/stories/RoomItem.js
  storybook/stories/StoriesSeparator.js
  storybook/stories/index.js
Labels: 👀 needs review, 🛠 fix

#2352 [NEW] Omnichannel inquiry queue
  app/actions/actionsTypes.js
  app/actions/inquiry.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/lib/methods/subscriptions/inquiry.js
  app/lib/rocketchat.js
  app/presentation/RoomItem/RoomItem.js
  app/presentation/RoomItem/Touchable.js
  app/presentation/RoomItem/index.js
  app/presentation/RoomItem/styles.js
  app/presentation/UnreadBadge.js
  app/reducers/index.js
  app/reducers/inquiry.js
  app/sagas/index.js
  app/sagas/inquiry.js
  app/sagas/login.js
  app/sagas/selectServer.js
  app/selectors/inquiry.js
  app/stacks/InsideStack.js
  app/stacks/MasterDetailStack/index.js
  app/utils/log/events.js
  app/views/QueueListView.js
  app/views/RoomActionsView/index.js
  app/views/RoomInfoView/Livechat.js
  app/views/RoomInfoView/index.js
  app/views/RoomView/index.js
  app/views/RoomsListView/ListHeader/Queue.js
  app/views/RoomsListView/ListHeader/index.js
  app/views/RoomsListView/index.js
Labels: 🎉 feature, 👀 needs review

#2335 [FIX] Minor i18n issues
  app/i18n/locales/pt-BR.js
  app/views/AutoTranslateView/index.js
  app/views/CreateChannelView.js
  app/views/DefaultBrowserView.js
  app/views/InviteUsersEditView/index.js
  app/views/InviteUsersView/index.js
  app/views/LanguageView/index.js
  app/views/MarkdownTableView.js
  app/views/NewServerView.js
  app/views/NotificationPreferencesView/index.js
  app/views/RoomInfoEditView/index.js
  app/views/ScreenLockConfigView.js
  app/views/SelectServerView.js
  app/views/ThemeView.js
  app/views/WithoutServersView.js
  app/views/WorkspaceView/index.js
Labels: 🛠 fix
