Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2020-01, with the labels that each got.

#1525 [FIX] Draft messages not working with themed Messagebox
  app/containers/MessageBox/index.js
  app/views/RoomView/index.js
Labels: 👀 needs review, 🛠 fix

#1527 [FIX] Make SAML wait for idp token instead of creating it on client
  app/views/AuthenticationWebView.js
  app/views/LoginSignupView.js
Labels: 👀 needs review, 🛠 fix

#1508 [FIX] Server Test Push Notification
  android/app/src/main/java/chat/rocket/reactnative/CustomPushNotification.java
  android/app/src/main/java/chat/rocket/reactnative/Ejson.java
Labels: 👀 needs review, 🛠 fix

#1509 [CHORE] Update to new server response
  app/sagas/selectServer.js
Labels: 👀 needs review, 🚚 chore

#1529 [FIX] Insert messages with blank users
  app/lib/methods/helpers/normalizeMessage.js
Labels: 👀 needs review

#1585 [FIX] Add username block condition to prevent error
  app/presentation/RoomItem/LastMessage.js
Labels: 👀 needs review, 🛠 fix

#1586 [FIX] Channels doesn't load
  app/sagas/rooms.js
Labels: 👀 needs review, 🛠 fix

#1629 [FIX] Make SAML to work on Rocket.Chat < 2.3.0
  app/views/AuthenticationWebView.js
  app/views/LoginSignupView.js
Labels: 👀 needs review, 🛠 fix

#1534 [NEW] Invite links
  app/actions/actionsTypes.js
  app/actions/inviteLinks.js
  app/constants/settings.js
  app/i18n/locales/de.js
  app/i18n/locales/en.js
  app/i18n/locales/fr.js
  app/i18n/locales/pt-BR.js
  app/i18n/locales/pt-PT.js
  app/i18n/locales/ru.js
  app/i18n/locales/zh-CN.js
  app/index.js
  app/lib/rocketchat.js
  app/reducers/index.js
  app/reducers/inviteLinks.js
  app/sagas/deepLinking.js
  app/sagas/index.js
  app/sagas/inviteLinks.js
  app/sagas/login.js
  app/views/InviteUsersEditView/index.js
  app/views/InviteUsersEditView/styles.js
  app/views/InviteUsersView/index.js
  app/views/InviteUsersView/styles.js
  app/views/RoomActionsView/index.js
  app/views/RoomsListView/index.js
Labels: 🎉 feature, 👀 needs review

#1482 Set the http-agent to the form that Rocket.Chat requires for logging
  app/utils/fetch.js
Labels: 👀 needs review, 🛠 fix

#1625 [FIX] "Following thread" and "Unfollowed Thread" use i18n
  app/views/RoomView/index.js
Labels: 🛠 fix

#1569 [FIX] Disable reset button if form didn't changed
  app/views/RoomInfoEditView/index.js
Labels: 🛠 fix

#1623 [FIX] Not allow to send messages to archived room
  app/views/RoomView/index.js
Labels: 👀 needs review, 🛠 fix

#1502 [FIX] Profile fields automatically reset
  app/views/ProfileView/index.js
Labels: 👀 needs review, 🛠 fix

#1493 [FIX] Show attachment on ThreadMessagesView
  app/views/ThreadMessagesView/index.js
Labels: 👀 needs review, 🛠 fix

#1633 [NEW] Authentication via Wordpress
  README.md
  android/app/src/main/res/drawable-hdpi/icon_wordpress.png
  android/app/src/main/res/drawable-mdpi/icon_wordpress.png
  android/app/src/main/res/drawable-xhdpi/icon_wordpress.png
  android/app/src/main/res/drawable-xxhdpi/icon_wordpress.png
  android/app/src/main/res/drawable-xxxhdpi/icon_wordpress.png
  app/lib/rocketchat.js
  app/views/LoginSignupView.js
  ios/RocketChatRN/Images.xcassets/Icons/icon_wordpress.imageset/Contents.json
  ios/RocketChatRN/Images.xcassets/Icons/icon_wordpress.imageset/iconWordpress.png
  ios/RocketChatRN/Images.xcassets/Icons/icon_wordpress.imageset/iconWordpress@2x.png
  ios/RocketChatRN/Images.xcassets/Icons/icon_wordpress.imageset/iconWordpress@3x.png
Labels: 🎉 feature, 👀 needs review

#1639 [CHORE] Add Start Packager script
  ios/RocketChatRN.xcodeproj/project.pbxproj
Labels: 👀 needs review, 🚚 chore

#1638 [CHORE] Update RN to 0.61.5
  package.json
  patches/react-native+0.61.5.patch
  yarn.lock
Labels: ⬆️ update dependencies, 🚚 chore

#1640 [FIX] Change force logout rule
  app/sagas/login.js
Labels: 👀 needs review, 🛠 fix

#1575 [IMPROVEMENT] Use MessagingStyle on Android Notification
  android/app/src/main/java/chat/rocket/reactnative/CustomPushNotification.java
  android/app/src/main/java/chat/rocket/reactnative/Ejson.java
Labels: 👀 needs review, 👍 improvement
