Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2021-11, with the labels that each got.

#3445 Chore: Migrate InviteUsersEditView to TypeScript
  app/views/InviteUsersEditView/index.tsx
  app/views/InviteUsersEditView/styles.ts
Labels: 🚚 chore, 👀 needs review

#3446 Chore: Migrate LanguageView to TypeScript
  app/externalModules.d.ts
  app/views/LanguageView/index.tsx
Labels: 🚚 chore, 👀 needs review

#3448 Chore: Migrate NotificationPreferencesView to Typescript
  app/views/NotificationPreferencesView/index.tsx
  app/views/NotificationPreferencesView/options.ts
Labels: 🚚 chore, 👀 needs review

#3449 Chore: Migrate ProfileView to TypeScript
  .eslintrc.js
  app/containers/Avatar/interfaces.ts
  app/containers/TextInput.tsx
  app/externalModules.d.ts
  app/presentation/KeyboardView.tsx
  app/utils/scrollPersistTaps.js
  app/utils/scrollPersistTaps.ts
  app/views/ProfileView/index.tsx
  app/views/ProfileView/interfaces.ts
  app/views/ProfileView/styles.ts
Labels: 🚚 chore, 👀 needs review

#3451 Chore: Migrate ReadReceiptView to Typescript
  app/views/ReadReceiptView/index.tsx
  app/views/ReadReceiptView/styles.ts
Labels: 🚚 chore

#3457 Chore: Migrate SearchMessagesView to Typescript
  app/containers/message/interfaces.ts
  app/views/SearchMessagesView/index.tsx
  app/views/SearchMessagesView/styles.ts
Labels: 🚚 chore, 👀 needs review

#3477 Chore: Migrate UserPreserencesView to Typescript
  app/utils/log/events.js
  app/views/UserPreferencesView/index.tsx
Labels: 🚚 chore

#3471 Chore: Migrate AddChannelTeamView to Typescript
  app/views/AddChannelTeamView.tsx
Labels: 🚚 chore, 👀 needs review

#3478 Chore: Migrate SidebarView to Typescript
  app/containers/Status/Status.tsx
  app/views/SidebarView/SidebarItem.tsx
  app/views/SidebarView/index.tsx
  app/views/SidebarView/styles.ts
Labels: 🚚 chore, 👀 needs review

#3474 Chore: Migrate AddExistingChannelView to Typescript
  app/views/AddExistingChannelView.tsx
Labels: 🚚 chore, 👀 needs review

#3482 Chore: Migrate ChangePasscodeView to Typescript
  app/containers/Passcode/PasscodeChoose.tsx
  app/views/ChangePasscodeView.tsx
Labels: 🚚 chore

#3486 Chore: Migrate CreateChannelView to Typescript
  app/containers/FormContainer.tsx
  app/presentation/UserItem.tsx
  app/views/CreateChannelView.tsx
  app/views/CreateDiscussionView/index.tsx
Labels: 🚚 chore, 👀 needs review

#3470 [NEW] Preview or download attachments
  __tests__/Storyshots.test.js
  app/constants/colors.ts
  app/constants/localPath.ts
  app/containers/message/Reply.tsx
  app/containers/message/Video.tsx
  app/i18n/locales/en.json
  app/i18n/locales/pt-BR.json
  app/utils/fileDownload/index.ts
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: 🎉 feature

#3447 Chore: Migrate MessagesView to Typescript
  app/containers/ActionSheet/Provider.tsx
  app/views/MessagesView/index.tsx
  app/views/MessagesView/styles.ts
Labels: 🚚 chore

#3469 Chore: Migrate UserNotificationPreferencesView to Typescript
  app/views/UserNotificationPreferencesView/index.tsx
  app/views/UserNotificationPreferencesView/options.ts
Labels: 🚚 chore

#3481 Chore: Migrate ShareView to Typescript
  app/presentation/ImageViewer/ImageViewer.tsx
  app/presentation/ImageViewer/index.ts
  app/views/ShareView/Header.tsx
  app/views/ShareView/Preview.tsx
  app/views/ShareView/Thumbs.tsx
  app/views/ShareView/constants.ts
  app/views/ShareView/index.tsx
  app/views/ShareView/interfaces.ts
  app/views/ShareView/styles.ts
  app/views/ShareView/utils.js
  app/views/ShareView/utils.ts
Labels: 🚚 chore

#3488 Chore: Migrate DefaultBrowserView to Typescript
  app/views/DefaultBrowserView.tsx
Labels: 🚚 chore, 👀 needs review

#3501 Chore: Migrate PickerView to Typescript
  app/views/PickerView.tsx
Labels: 🚚 chore, 👀 needs review

#3483 Chore: Migrate AttachmentView to Typescript
  app/externalModules.d.ts
  app/presentation/ImageViewer/ImageComponent.ts
  app/presentation/ImageViewer/ImageViewer.tsx
  app/views/AttachmentView.tsx
Labels: 🚚 chore, 👀 needs review

#3500 Chore: Migrate MarkdownTableView to Typescript
  app/views/MarkdownTableView.tsx
Labels: 🚚 chore, 👀 needs review

#3489 Chore: Migrate E2EEncryptionSecurityView to Typescript
  app/views/E2EEncryptionSecurityView.tsx
Labels: 🚚 chore, 👀 needs review

#3490 Chore: Migrate E2EEnterYourPasswordView to Typescript
  app/presentation/KeyboardView.tsx
  app/views/E2EEnterYourPasswordView.tsx
Labels: 🚚 chore, 👀 needs review

#3492 Chore: Migrate E2EHowItWorksView to Typescript
  app/views/E2EHowItWorksView.tsx
Labels: 🚚 chore, 👀 needs review

#3493 Chore: Migrate E2ESaveYourPasswordView to Typescript
  app/views/E2ESaveYourPasswordView.tsx
Labels: 🚚 chore, 👀 needs review

#3496 Chore: Migrate ForgotPasswordView to Typescript
  app/views/ForgotPasswordView.tsx
Labels: 🚚 chore, 👀 needs review

#3497 Chore: Migrate ForwardLivechatView to Typescript
  app/containers/UIKit/MultiSelect/Input.tsx
  app/views/ForwardLivechatView.tsx
  app/views/definition/ILivechatDepartment.ts
Labels: 🚚 chore, 👀 needs review

#3498 Chore: Migrate JitsiMeetView to Typescript
  app/externalModules.d.ts
  app/views/JitsiMeetView.tsx
  package.json
  yarn.lock
Labels: 🚚 chore, 👀 needs review
