Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2021-07, with the labels that each got.

#2993 [CHORE] Subscribe to permissions
  app/actions/actionsTypes.js
  app/actions/permissions.js
  app/lib/methods/getPermissions.js
  app/lib/rocketchat.js
  app/reducers/permissions.js
Labels: 🚚 chore

#2992 [IMPROVE] Subscribe to roles
  app/actions/actionsTypes.js
  app/actions/roles.js
  app/lib/methods/getRoles.js
  app/lib/rocketchat.js
  app/reducers/index.js
  app/reducers/permissions.js
  app/reducers/roles.js
  app/sagas/login.js
  app/sagas/selectServer.js
  app/views/RoomInfoView/index.js
  app/views/RoomMembersView/index.js
Labels: 🚚 chore

#3222 [IMPROVE] Subscribe to settings
  app/actions/actionsTypes.js
  app/actions/settings.js
  app/lib/methods/getSettings.js
  app/lib/rocketchat.js
  app/reducers/settings.js
Labels: 👀 needs review, 🚚 chore

#3219 [FIX] App not showing proper alert on team delete
  app/actions/room.js
  app/i18n/locales/en.json
  app/i18n/locales/pt-BR.json
  app/reducers/room.js
  app/sagas/room.js
  app/views/RoomInfoEditView/index.js
Labels: 👀 needs review

#3223 [IMPROVE] Add Jitsi button to Teams
  app/constants/settings.js
  app/views/RoomActionsView/index.js
Labels: 👍 improvement, 🚨 needs changes

#3225 [FIX] Jump to message from in-app notification
  app/containers/InAppNotification/NotifierComponent.js
  app/views/RoomView/List/index.js
Labels: 👀 needs review, 🛠 fix

#3244 [FIX] Google OAuth triggering cookies logic
  app/actions/login.js
  app/lib/database/model/servers/User.js
  app/lib/database/model/servers/migrations.js
  app/lib/database/schema/servers.js
  app/lib/rocketchat.js
  app/sagas/deepLinking.js
  app/sagas/login.js
  app/views/SettingsView/index.js
Labels: 👀 needs review, 👍 improvement, 🚚 chore

#2981 [IMPROVE] Message body readability on dark themes
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/constants/colors.js
Labels: 👀 needs review, 🚚 chore

#3254 [FIX] Subscribe to settings making app to hang on login
  app/lib/methods/getSettings.js
  app/lib/rocketchat.js
  app/sagas/login.js
Labels: 🛠 fix

#3260 [FIX] Poor performance in messages list on Android 11
  patches/react-native+0.63.4.patch
Labels: 👀 needs review, 🚀 performance, 🛠 fix

#3248 [FIX] Create team crashing the app
  app/sagas/createChannel.js
Labels: 🛠 fix

#3249 [IMPROVE] Convert Team to Channel
  app/i18n/locales/en.json
  app/i18n/locales/pt-BR.json
  app/lib/methods/getPermissions.js
  app/lib/rocketchat.js
  app/utils/log/events.js
  app/views/RoomActionsView/index.js
  e2e/tests/team/03-moveconvert.spec.js
Labels: 🎉 feature, 🚨 needs changes

#3270 [IMPROVE] Set black as default dark theme
  app/index.js
  app/share.js
  app/views/ThemeView.js
Labels: 👍 improvement, 🚸 ux

#3265 [IMPROVE] Make `system default` the default browser
  app/utils/openLink.js
  app/views/DefaultBrowserView.js
Labels: 👍 improvement, 🚨 needs changes

#3271 [IMPROVE] Remove difference between public/private on "Group by type"
  app/i18n/locales/ar.json
  app/i18n/locales/de.json
  app/i18n/locales/en.json
  app/i18n/locales/es-ES.json
  app/i18n/locales/fr.json
  app/i18n/locales/it.json
  app/i18n/locales/ja.json
  app/i18n/locales/nl.json
  app/i18n/locales/pt-BR.json
  app/i18n/locales/pt-PT.json
  app/i18n/locales/ru.json
  app/i18n/locales/tr.json
  app/i18n/locales/zh-CN.json
  app/i18n/locales/zh-TW.json
  app/views/RoomsListView/index.js
Labels: 👀 needs review, 👍 improvement

#3277 [REGRESSION] Settings pagination not working
  app/lib/methods/getSettings.js
Labels: 🛠 fix

#3278 Regression: Markdown handlePress not working properly
  app/containers/markdown/Link.js
Labels: 🛠 fix

#3285 Chore: Improve QA workflow
  .circleci/config.yml
  android/fastlane/Fastfile
  android/fastlane/README.md
Labels: 👷 ci

#3291 Chore: Run lint and tests on staged files only
  package.json
Labels: 👀 needs review, 🚚 chore

#3290 [FIX] Conflicts not resolved properly on 4.18.0
  app/views/RoomsListView/Header/Header.js
Labels: 🛠 fix

#3300 Chore: Update Bugsnag
  .circleci/config.yml
  __mocks__/@bugsnag/react-native.js
  __mocks__/bugsnag-react-native.js
  android/app/src/play/java/chat/rocket/reactnative/MainPlayApplication.java
  app/utils/log/index.js
  config.js
  ios/Gemfile.lock
  ios/Podfile
  ios/Podfile.lock
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/Target Support Files/BugsnagReactNative/BugsnagReactNative.debug.xcconfig
  ios/Pods/Target Support Files/BugsnagReactNative/BugsnagReactNative.release.xcconfig
  ios/Pods/Target Support Files/Pods-NotificationService/Pods-NotificationService-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-NotificationService/Pods-NotificationService-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-NotificationService/Pods-NotificationService.debug.xcconfig
  ios/Pods/Target Support Files/Pods-NotificationService/Pods-NotificationService.release.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/Pods-defaults-Rocket.Chat/Pods-defaults-Rocket.Chat-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-defaults-Rocket.Chat/Pods-defaults-Rocket.Chat-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-defaults-Rocket.Chat/Pods-defaults-Rocket.Chat.debug.xcconfig
  ios/Pods/Target Support Files/Pods-defaults-Rocket.Chat/Pods-defaults-Rocket.Chat.release.xcconfig
  ios/Pods/Target Support Files/Pods-defaults-RocketChatRN/Pods-defaults-RocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-defaults-RocketChatRN/Pods-defaults-RocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-defaults-RocketChatRN/Pods-defaults-RocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-defaults-RocketChatRN/Pods-defaults-RocketChatRN.release.xcconfig
  ios/RocketChatRN.xcodeproj/project.pbxproj
  ios/RocketChatRN/AppDelegate.m
  ios/RocketChatRN/Info.plist
  ios/ShareRocketChatRN/Info.plist
  ios/ShareRocketChatRN/ShareRocketChatRN.m
  ios/fastlane/Fastfile
  ios/fastlane/Pluginfile
  package.json
  yarn.lock
Labels: ⬆️ update dependencies
