Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2021-04, with the labels that each got.

#3033 [FIX] Create discussion request being sent with null value on encryption param
  app/views/CreateDiscussionView/index.js
Labels: 🛠 fix

#3011 [CHORE] Use JSON files for i18n
  app/i18n/index.js
  app/i18n/locales/ar.js
  app/i18n/locales/ar.json
  app/i18n/locales/de.js
  app/i18n/locales/de.json
  app/i18n/locales/en.js
  app/i18n/locales/en.json
  app/i18n/locales/es-ES.js
  app/i18n/locales/es-ES.json
  app/i18n/locales/fr.js
  app/i18n/locales/fr.json
  app/i18n/locales/it.js
  app/i18n/locales/it.json
  app/i18n/locales/ja.js
  app/i18n/locales/ja.json
  app/i18n/locales/nl.js
  app/i18n/locales/nl.json
  app/i18n/locales/pt-BR.js
  app/i18n/locales/pt-BR.json
  app/i18n/locales/pt-PT.js
  app/i18n/locales/pt-PT.json
  app/i18n/locales/ru.js
  app/i18n/locales/ru.json
  app/i18n/locales/tr.js
  app/i18n/locales/tr.json
  app/i18n/locales/zh-CN.js
  app/i18n/locales/zh-CN.json
  app/i18n/locales/zh-TW.js
  app/i18n/locales/zh-TW.json
Labels: ♻️ refactor, 🌎 i18n, 👀 needs review, 🚚 chore

#3014 [IMPROVEMENT] Load only i18n files needed
  app/i18n/index.js
  app/sagas/login.js
Labels: ♻️ refactor, 👀 needs review, 🚀 performance

#3007 [REGRESSION] Clear local server cache not loading rooms
  app/lib/rocketchat.js
  app/presentation/RoomItem/Actions.js
  app/presentation/RoomItem/Touchable.js
  app/views/SettingsView/index.js
  e2e/tests/assorted/04-setting.spec.js
Labels: 🐛 bug, 👀 needs review

#3020 [FIX] Custom OAuth and iframe login attempts being called multiple times
  app/views/AuthenticationWebView.js
Labels: 👀 needs review, 🛠 fix

#3021 [FIX] App crashing when attachment color is an invalid HEX
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/message/Reply.js
  storybook/stories/Message.js
Labels: 👀 needs review, 🛠 fix

#3029 [IMPROVEMENT] Add "Message" option to Room Info
  app/views/RoomInfoView/index.js
  app/views/RoomInfoView/styles.js
Labels: 👀 needs review, 🚚 chore

#3018 [FIX] Can't change status
  app/views/StatusView.js
Labels: 👀 needs review, 🛠 fix

#3012 [FIX] Search input not using the whole space
  app/containers/Header/index.js
  app/views/RoomsListView/index.js
Labels: 👀 needs review, 🛠 fix

#2972 [FIX] E2EE password hiding automatically
  app/sagas/encryption.js
  e2e/data.js
  e2e/data/data.cloud.js
  e2e/data/data.docker.js
  e2e/tests/assorted/01-e2eencryption.spec.js
  e2e/tests/assorted/07-changeserver.spec.js
  e2e/tests/assorted/10-deleteserver.spec.js
Labels: 👀 needs review, 🛠 fix

#2965 [TESTS] Move threads tests to its own file
  e2e/tests/room/02-room.spec.js
  e2e/tests/room/05-threads.spec.js
  e2e/tests/room/06-createdmgroup.spec.js
  e2e/tests/room/07-markasunread.spec.js
  e2e/tests/room/08-roominfo.spec.js
Labels: ✅ tests, 👀 needs review

#2928 [FIX] Regex typo on markdown
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/markdown/index.js
  storybook/stories/Message.js
Labels: ✅ needs tests, 🛠 fix

#2927 [FIX] Make attachment validation compatible with web client
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/message/Attachments.js
  storybook/stories/Message.js
Labels: ✅ needs tests, 🛠 fix

#2902 [FIX] Non-reply attachments displaying time
  app/containers/message/Reply.js
  storybook/stories/Message.js
Labels: ✅ needs tests, 🛠 fix

#3036 [FIX] Revert #2927
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/message/Attachments.js
  storybook/stories/Message.js
Labels: 🛠 fix

#3037 Bump version to 4.16.0
  android/app/build.gradle
  ios/RocketChatRN.xcodeproj/project.pbxproj
  ios/RocketChatRN/Info.plist
  ios/ShareRocketChatRN/Info.plist
  package.json
Labels: 💎 release

#3016 [NEW] Basic support to Teams
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/BackgroundContainer/index.js
  app/containers/BackgroundContainer/index.stories.js
  app/containers/RoomHeader/RoomHeader.js
  app/containers/RoomHeader/RoomHeader.stories.js
  app/containers/RoomHeader/index.js
  app/containers/RoomTypeIcon.js
  app/i18n/locales/en.json
  app/i18n/locales/pt-BR.json
  app/lib/database/model/Subscription.js
  app/lib/database/model/migrations.js
  app/lib/database/schema/app.js
  app/lib/methods/helpers/mergeSubscriptionsRooms.js
  app/lib/rocketchat.js
  app/presentation/RoomItem/RoomItem.js
  app/presentation/RoomItem/TypeIcon.js
  app/presentation/RoomItem/index.js
  app/sagas/rooms.js
  app/stacks/InsideStack.js
  app/stacks/MasterDetailStack/index.js
  app/utils/goRoom.js
  app/utils/log/events.js
  app/views/NewMessageView.js
  app/views/RoomActionsView/index.js
  app/views/RoomInfoView/index.js
  app/views/RoomView/LeftButtons.js
  app/views/RoomView/RightButtons.js
  app/views/RoomView/index.js
  app/views/RoomsListView/index.js
  app/views/TeamChannelsView.js
  app/views/ThreadMessagesView/index.js
  e2e/tests/assorted/02-broadcast.spec.js
  e2e/tests/assorted/05-joinpublicroom.spec.js
  e2e/tests/assorted/08-joinprotectedroom.spec.js
  e2e/tests/room/02-room.spec.js
  e2e/tests/room/03-roomactions.spec.js
  e2e/tests/room/04-discussion.spec.js
  e2e/tests/room/05-threads.spec.js
  e2e/tests/room/08-roominfo.spec.js
  storybook/stories/RoomViewHeader.js
  storybook/stories/index.js
Labels: 🎉 feature, 🚧 wip

#2997 [CHORE] Refactor mention tracking logic
  app/containers/MessageBox/Mentions/index.js
  app/containers/MessageBox/constants.js
  app/containers/MessageBox/index.js
  app/lib/rocketchat.js
  app/utils/avatar.js
  app/views/RoomsListView/index.js
  e2e/helpers/app.js
  e2e/tests/assorted/01-e2eencryption.spec.js
  e2e/tests/assorted/02-broadcast.spec.js
  e2e/tests/assorted/04-setting.spec.js
  e2e/tests/assorted/05-joinpublicroom.spec.js
  e2e/tests/assorted/08-joinprotectedroom.spec.js
  e2e/tests/onboarding/06-roomslist.spec.js
  e2e/tests/room/02-room.spec.js
  e2e/tests/room/03-roomactions.spec.js
  e2e/tests/room/04-discussion.spec.js
  e2e/tests/room/05-threads.spec.js
  e2e/tests/room/07-markasunread.spec.js
  e2e/tests/room/08-roominfo.spec.js
Labels: ♻️ refactor, 🚚 chore, 🚨 needs changes

#3041 [FIX] Status text not being updated on sidebar
  app/views/StatusView.js
Labels: 👀 needs review, 🛠 fix

#3039 [FIX] Unable to search non-latin alphabet names on members list
  app/views/RoomMembersView/index.js
Labels: 👀 needs review, 🛠 fix

#3044 [FIX] Team's channel search not working properly
  app/views/TeamChannelsView.js
Labels: 🛠 fix

#3050 [CHORE] Add job to upload Experimental to Google Play production
  .circleci/config.yml
  android/fastlane/Fastfile
Labels: 👷 ci, 🚚 chore

#3060 [REGRESSION] SAML stopped working after #2978
  app/views/AuthenticationWebView.js
Labels: 🛠 fix

#3072 [REGRESSION] Fallback language stopped working
  app/i18n/index.js
Labels: 🛠 fix

#3065 Merge 4.16.1 into single-server
  .circleci/config.yml
  android/app/build.gradle
  android/fastlane/Fastfile
  app/containers/RoomHeader/RoomHeader.js
  app/i18n/index.js
  app/sagas/init.js
  app/views/AuthenticationWebView.js
  app/views/RoomActionsView/index.js
  ios/RocketChatRN.xcodeproj/project.pbxproj
  ios/RocketChatRN/Info.plist
  ios/ShareRocketChatRN/Info.plist
  package.json
Labels: 💎 release

#3064 Merge 4.16.1 into master
  .circleci/config.yml
  android/app/build.gradle
  android/fastlane/Fastfile
  app/containers/RoomHeader/RoomHeader.js
  app/i18n/index.js
  app/views/AuthenticationWebView.js
  ios/RocketChatRN.xcodeproj/project.pbxproj
  ios/RocketChatRN/Info.plist
  ios/ShareRocketChatRN/Info.plist
  package.json
Labels: 💎 release

#3052 [CHORE] Update Detox to 18.10.0
  app/containers/MessageBox/index.js
  app/utils/log/events.js
  app/views/RoomActionsView/index.js
  app/views/StatusView.js
  e2e/data.js
  e2e/helpers/app.js
  e2e/helpers/data_setup.js
  e2e/tests/assorted/01-e2eencryption.spec.js
  e2e/tests/assorted/02-broadcast.spec.js
  e2e/tests/assorted/03-profile.spec.js
  e2e/tests/assorted/04-setting.spec.js
  e2e/tests/assorted/05-joinpublicroom.spec.js
  e2e/tests/assorted/06-status.spec.js
  e2e/tests/assorted/07-changeserver.spec.js
  e2e/tests/assorted/08-joinprotectedroom.spec.js
  e2e/tests/assorted/10-deleteserver.spec.js
  e2e/tests/assorted/11-deeplinking.spec.js
  e2e/tests/onboarding/01-onboarding.spec.js
  e2e/tests/onboarding/03-forgotpassword.spec.js
  e2e/tests/onboarding/07-server-history.spec.js
  e2e/tests/room/01-createroom.spec.js
  e2e/tests/room/02-room.spec.js
  e2e/tests/room/03-roomactions.spec.js
  e2e/tests/room/05-threads.spec.js
  e2e/tests/room/07-markasunread.spec.js
  e2e/tests/room/08-roominfo.spec.js
  ios/RocketChatRN.xcodeproj/project.pbxproj
  package.json
  yarn.lock
Labels: ✅ tests, 🚚 chore

#3048 [FIX] Message author touchable taking whole space available
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/message/User.js
Labels: 🛠 fix

#3091 [REGRESSION] Fallback not working when device's language is available
  app/i18n/index.js
  app/i18n/locales/nl.json
  e2e/tests/assorted/04-setting.spec.js
  e2e/tests/assorted/12-i18n.spec.js
Labels: 🛠 fix
