Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2021-08, with the labels that each got.

#3237 [FIX] Unarchive permission not honored
  app/views/RoomInfoEditView/index.js
Labels: 👀 needs review, 🛠 fix

#3255 [FIX] Hardcoded backdrop opacity on loading component
  app/containers/Loading.js
Labels: 🛠 fix

#3310 [FIX] Share extension not working on iOS
  ios/Podfile
  ios/Podfile.lock
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/Target Support Files/Pods-NotificationService/Pods-NotificationService-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-NotificationService/Pods-NotificationService-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-NotificationService/Pods-NotificationService.debug.xcconfig
  ios/Pods/Target Support Files/Pods-NotificationService/Pods-NotificationService.release.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.release.xcconfig
  ios/RocketChatRN.xcodeproj/project.pbxproj
Labels: 👀 needs review, 🛠 fix

#3288 [FIX] Reactive footer when agents take chats
  app/views/RoomView/index.js
Labels: 🛠 fix

#3295 [FIX] Omnichannel custom fields are not rendered properly
  app/views/LivechatEditView.js
Labels: 👀 needs review, 🛠 fix

#3289 [FIX] Wrong message when room is closed by the Guest
  app/views/RoomView/index.js
Labels: 👀 needs review, 🛠 fix

#3298 [FIX] Dealing well with pre-configured tags in Omnichannel
  app/containers/UIKit/MultiSelect/index.js
  app/views/LivechatEditView.js
Labels: 🛠 fix

#3335 [FIX] Enabled and disable the report to bugsnag and analytics
  app/actions/actionsTypes.js
  app/actions/crashReport.js
  app/index.js
  app/reducers/crashReport.js
  app/reducers/index.js
  app/sagas/init.js
  app/utils/log/index.js
  app/views/SecurityPrivacyView.js
Labels: 👀 needs review, 🛠 fix

#3292 Chore: Update Jitsi to 3.6.0
  android/build.gradle
  app/views/JitsiMeetView.js
  ios/Podfile.lock
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/Target Support Files/JitsiMeetSDK/JitsiMeetSDK.debug.xcconfig
  ios/Pods/Target Support Files/JitsiMeetSDK/JitsiMeetSDK.release.xcconfig
  ios/Pods/Target Support Files/Pods-defaults-Rocket.Chat/Pods-defaults-Rocket.Chat-frameworks.sh
  ios/Pods/Target Support Files/Pods-defaults-Rocket.Chat/Pods-defaults-Rocket.Chat.debug.xcconfig
  ios/Pods/Target Support Files/Pods-defaults-Rocket.Chat/Pods-defaults-Rocket.Chat.release.xcconfig
  ios/Pods/Target Support Files/Pods-defaults-RocketChatRN/Pods-defaults-RocketChatRN-frameworks.sh
  ios/Pods/Target Support Files/Pods-defaults-RocketChatRN/Pods-defaults-RocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-defaults-RocketChatRN/Pods-defaults-RocketChatRN.release.xcconfig
  ios/Pods/Target Support Files/react-native-jitsi-meet/react-native-jitsi-meet.debug.xcconfig
  ios/Pods/Target Support Files/react-native-jitsi-meet/react-native-jitsi-meet.release.xcconfig
  ios/RocketChatRN.xcodeproj/project.pbxproj
  package.json
  yarn.lock
Labels: ⬆️ update dependencies
