Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2021-10, with the labels that each got.

#3341 Chore: Update Reanimated to 2.2.2
  android/app/src/main/java/chat/rocket/reactnative/MainApplication.java
  app/containers/ActionSheet/ActionSheet.tsx
  app/presentation/ImageViewer/ImageViewer.android.tsx
  babel.config.js
  ios/Podfile.lock
  package.json
  patches/react-native-reanimated+2.2.2.patch
  yarn.lock
Labels: 🚚 chore

#3404 [FIX] Toggle password visibility button not working
  app/containers/TextInput.tsx
Labels: 🛠 fix

#3407 [FIX] Searching for Online and All users for server's version less than 3.16.0
  app/views/RoomMembersView/index.js
Labels: 🛠 fix

#3424 Chore: Migrate AuthLoadingView to Typescript
  app/views/AuthLoadingView.tsx
Labels: 🚚 chore

#3212 [IMPROVE] Add pagination to search messages And Fix the search for encrypted room
  app/lib/rocketchat.js
  app/views/RoomView/RightButtons.js
  app/views/RoomView/index.js
  app/views/SearchMessagesView/index.js
Labels: 🐛 bug, 🛠 fix

#3233 [IMPROVE] Check permission to create a room
  app/lib/methods/getPermissions.js
  app/lib/rocketchat.js
  app/views/CreateChannelView.js
  app/views/NewMessageView.js
  app/views/RoomsListView/index.js
Labels: 👍 improvement, 🚨 needs changes

#3318 [NEW] Display preferences screen
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/actions/actionsTypes.js
  app/actions/rooms.js
  app/constants/constantDisplayMode.js
  app/containers/Avatar/Avatar.tsx
  app/ee/omnichannel/views/QueueListView.js
  app/i18n/locales/ar.json
  app/i18n/locales/de.json
  app/i18n/locales/en.json
  app/i18n/locales/es-ES.json
  app/i18n/locales/fr.json
  app/i18n/locales/it.json
  app/i18n/locales/ja.json
  app/i18n/locales/nl.json
  app/i18n/locales/pt-BR.json
  app/i18n/locales/pt-PT.json
  app/i18n/locales/ru.json
  app/i18n/locales/tr.json
  app/i18n/locales/zh-CN.json
  app/i18n/locales/zh-TW.json
  app/presentation/RoomItem/Actions.tsx
  app/presentation/RoomItem/IconOrAvatar.js
  app/presentation/RoomItem/LastMessage.tsx
  app/presentation/RoomItem/RoomItem.tsx
  app/presentation/RoomItem/Touchable.tsx
  app/presentation/RoomItem/TypeIcon.tsx
  app/presentation/RoomItem/Wrapper.tsx
  app/presentation/RoomItem/index.tsx
  app/presentation/RoomItem/styles.ts
  app/reducers/rooms.js
  app/reducers/sortPreferences.js
  app/stacks/InsideStack.js
  app/stacks/MasterDetailStack/index.js
  app/utils/log/events.js
  app/views/DisplayPrefsView.js
  app/views/RoomsListView/Header/index.js
  app/views/RoomsListView/ListHeader/index.js
  app/views/RoomsListView/SortDropdown/index.js
  app/views/RoomsListView/index.js
  app/views/SettingsView/index.js
  app/views/SidebarView/index.js
  app/views/TeamChannelsView.js
  e2e/tests/assorted/13-display-pref.spec.js
  storybook/stories/RoomItem.js
Labels: 🎉 feature
