Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2021-12, with the labels that each got.

#3502 Chore: Migrate NewMessageView to Typescript
  app/presentation/UserItem.tsx
  app/views/NewMessageView.tsx
Labels: 🚚 chore, 👀 needs review

#3517 Chore: Migrate ScreenLockConfigView to Typescript
  app/views/ScreenLockConfigView.tsx
Labels: 🚚 chore, 👀 needs review

#3518 Chore: Migrate SecurityPrivacyView to Typescript
  app/views/SecurityPrivacyView.tsx
Labels: 🚚 chore, 👀 needs review

#3519 Chore: Migrate SelectListView to Typescript
  app/views/SelectListView.tsx
Labels: 🚚 chore, 👀 needs review

#3521 Chore: Migrate SelectServerView to Typescript
  app/views/SelectServerView.tsx
Labels: 🚚 chore, 👀 needs review

#3526 Chore: Migrate SetUsernameView to Typescript
  app/presentation/KeyboardView.tsx
  app/views/SetUsernameView.tsx
Labels: 🚚 chore, 👀 needs review

#3522 Chore: Migrate ThemeView to Typescript
  app/views/ThemeView.tsx
Labels: 🚚 chore, 👀 needs review

#3527 Chore: Migrate StatusView to Typescript
  app/containers/Status/Status.tsx
  app/views/StatusView.tsx
Labels: 🚚 chore, 👀 needs review

#3532 Chore: Migrate TeamChannelsView to Typescript
  app/containers/HeaderButton/HeaderButtonContainer.tsx
  app/views/TeamChannelsView.tsx
Labels: 🚚 chore, 👀 needs review

#3537 [FIX] Certificate stops working after app update on iOS
  app/utils/sslPinning.js
Labels: 👀 needs review, 🛠 fix

#3505 [NEW] Permission for uploading files
  app/containers/MessageBox/RecordAudio.tsx
  app/containers/MessageBox/index.tsx
  app/i18n/locales/en.json
  app/lib/methods/getPermissions.js
  app/utils/media.js
  app/views/ShareView/index.tsx
Labels: 🎉 feature

#3541 [FIX] Files screen stopped listing content on server 4.2
  app/lib/rocketchat.js
Labels: 🛠 fix

#3503 Chore: Migrate ModalBlockView to Typescript
  app/views/ModalBlockView.tsx
Labels: 🚚 chore, 👀 needs review

#3520 Chore: Migrate SelectedUsersView to Typescript
  app/presentation/UserItem.tsx
  app/views/SelectedUsersView.tsx
Labels: 🚚 chore

#3534 [IMPROVE] Remove visitor's navigation history
  app/i18n/locales/ar.json
  app/i18n/locales/de.json
  app/i18n/locales/en.json
  app/i18n/locales/fr.json
  app/i18n/locales/it.json
  app/i18n/locales/nl.json
  app/i18n/locales/pt-BR.json
  app/i18n/locales/pt-PT.json
  app/i18n/locales/ru.json
  app/i18n/locales/tr.json
  app/i18n/locales/zh-CN.json
  app/i18n/locales/zh-TW.json
  app/lib/rocketchat.js
  app/stacks/InsideStack.tsx
  app/stacks/MasterDetailStack/index.tsx
  app/stacks/MasterDetailStack/types.ts
  app/stacks/types.ts
  app/utils/log/events.js
  app/views/RoomActionsView/index.js
  app/views/VisitorNavigationView.js
Labels: 🛠 fix
