Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2021-09, with the labels that each got.

#3370 [IMPROVE] Show full image when available
  app/views/AttachmentView.js
Labels: 🎉 feature

#3382 Fix: lint-staged not working properly
  package.json
Labels: 🚚 chore, 🛠 fix

#3377 Chore: Migrate AdminPanelView to Typescript
  app/views/AdminPanelView/index.tsx
Labels: 🚚 chore, 👀 needs review

#3380 Chore: Migrate AutoTranslateView to Typescript
  .eslintrc.js
  app/views/AutoTranslateView/index.tsx
Labels: 🚚 chore, 👀 needs review

#3384 Fix: @rocketchat/sdk not fetching correct commit
  yarn.lock
Labels: 🚚 chore, 🛠 fix

#3378 Chore: Migrate CreateDiscussionView to Typescript
  app/containers/HeaderButton/Common.tsx
  app/containers/UIKit/MultiSelect/index.tsx
  app/views/CreateDiscussionView/SelectChannel.tsx
  app/views/CreateDiscussionView/SelectUsers.tsx
  app/views/CreateDiscussionView/index.tsx
  app/views/CreateDiscussionView/interfaces.ts
  app/views/CreateDiscussionView/styles.ts
Labels: 🚚 chore, 👀 needs review

#3379 Chore: Migrate DirectoryView to Typescript
  app/presentation/DirectoryItem/index.tsx
  app/utils/log/events.js
  app/views/DirectoryView/Options.tsx
  app/views/DirectoryView/index.tsx
  app/views/DirectoryView/styles.ts
Labels: 🚚 chore, 👀 needs review

#3351 [IMPROVE] Fetch members from API endpoint
  app/lib/rocketchat.js
  app/views/RoomMembersView/index.js
Labels: 🎉 feature, 👀 needs review

#3355 [NEW] Canned responses
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/constants/settings.ts
  app/containers/MessageBox/Mentions/MentionHeaderList.js
  app/containers/MessageBox/Mentions/MentionItem.tsx
  app/containers/MessageBox/Mentions/index.tsx
  app/containers/MessageBox/constants.ts
  app/containers/MessageBox/index.tsx
  app/containers/MessageBox/styles.ts
  app/containers/SearchHeader.js
  app/containers/UIKit/MultiSelect/Input.tsx
  app/containers/UIKit/MultiSelect/index.tsx
  app/i18n/locales/en.json
  app/i18n/locales/pt-BR.json
  app/lib/methods/getPermissions.js
  app/lib/rocketchat.js
  app/stacks/InsideStack.js
  app/stacks/MasterDetailStack/index.js
  app/views/CannedResponseDetail.js
  app/views/CannedResponsesListView/CannedResponseItem.js
  app/views/CannedResponsesListView/CannedResponseItem.stories.js
  app/views/CannedResponsesListView/Dropdown/DropdownItem.js
  app/views/CannedResponsesListView/Dropdown/DropdownItemFilter.js
  app/views/CannedResponsesListView/Dropdown/DropdownItemHeader.js
  app/views/CannedResponsesListView/Dropdown/index.js
  app/views/CannedResponsesListView/index.js
  app/views/CannedResponsesListView/styles.js
  app/views/RoomActionsView/index.js
  app/views/RoomView/index.js
  app/views/TeamChannelsView.js
  app/views/ThreadMessagesView/index.js
  storybook/stories/index.js
Labels: 🎉 feature, 👀 needs review

#3387 [IMPROVE] Onboarding changes
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/AppContainer.tsx
  app/actions/app.js
  app/containers/Button/index.tsx
  app/reducers/server.js
  app/sagas/deepLinking.js
  app/sagas/login.js
  app/stacks/OutsideStack.js
  app/utils/log/events.js
  app/utils/scaling.js
  app/views/NewServerView/ServerInput/index.js
  app/views/NewServerView/index.js
  app/views/OnboardingView/index.js
  app/views/OnboardingView/styles.js
  app/views/RoomsListView/ServerDropdown.js
  app/views/RoomsListView/index.js
  app/views/RoomsListView/styles.js
  app/views/WorkspaceView/index.js
  e2e/helpers/app.js
  e2e/tests/assorted/07-changeserver.spec.js
  e2e/tests/assorted/12-i18n.spec.js
  e2e/tests/onboarding/01-onboarding.spec.js
  e2e/tests/onboarding/07-server-history.spec.js
Labels: 👀 needs review, 🛠 fix

#3400 [FIX] Canned Responses minor fixes
  app/containers/MessageBox/index.tsx
  app/views/CannedResponsesListView/index.js
Labels: 🛠 fix

#3399 [FIX] Room Actions buttons not showing after taking a channel from Omnichannel Queue
  app/views/RoomActionsView/index.js
  app/views/RoomView/index.js
Labels: 🛠 fix

#3403 [FIX] Fetch members on RoomMembersView
  app/lib/rocketchat.js
  app/views/RoomMembersView/index.js
Labels: 🛠 fix
