Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2021-02, with the labels that each got.

#2845 [FIX] Share extension memory issues on iOS
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/Passcode/Base/Dots.js
  app/containers/Passcode/Base/index.js
  app/containers/TwoFactor/index.js
  app/lib/methods/enterpriseModules.js
  app/lib/methods/getCustomEmojis.js
  app/lib/methods/getPermissions.js
  app/lib/methods/getUsersPresence.js
  app/lib/rocketchat.js
  app/presentation/RoomItem/LastMessage.js
  app/sagas/selectServer.js
  app/selectors/login.js
  app/utils/avatar.js
  app/views/ChangePasscodeView.js
  app/views/NewMessageView.js
  app/views/ProfileView/index.js
  app/views/RoomActionsView/index.js
  app/views/RoomInfoEditView/index.js
  app/views/RoomInfoView/index.js
  app/views/ScreenLockedView.js
  app/views/SelectServerView.js
  app/views/SelectedUsersView.js
  app/views/ShareListView/index.js
  app/views/ShareView/Preview.js
  app/views/ShareView/Thumbs.js
  app/views/ShareView/index.js
  ios/Podfile
  ios/Podfile.lock
  ios/Pods/Local Podspecs/EXVideoThumbnails.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-resources.sh
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.release.xcconfig
  ios/RocketChatRN.xcodeproj/project.pbxproj
  package.json
  yarn.lock
Labels: 🛠 fix

#2859 Bump version to 4.14.1
  android/app/build.gradle
  ios/RocketChatRN.xcodeproj/project.pbxproj
  ios/RocketChatRN/Info.plist
  ios/ShareRocketChatRN/Info.plist
Labels: 💎 release

#2892 Merge 4.14.1 into single-server
  __tests__/__snapshots__/Storyshots.test.js.snap
  android/app/build.gradle
  app/containers/Passcode/Base/Dots.js
  app/containers/Passcode/Base/index.js
  app/containers/TwoFactor/index.js
  app/lib/methods/enterpriseModules.js
  app/lib/methods/getCustomEmojis.js
  app/lib/methods/getPermissions.js
  app/lib/methods/getUsersPresence.js
  app/lib/rocketchat.js
  app/presentation/RoomItem/LastMessage.js
  app/sagas/login.js
  app/sagas/selectServer.js
  app/selectors/login.js
  app/stacks/OutsideStack.js
  app/utils/avatar.js
  app/views/ChangePasscodeView.js
  app/views/NewMessageView.js
  app/views/ProfileView/index.js
  app/views/RoomActionsView/index.js
  app/views/RoomInfoEditView/index.js
  app/views/RoomInfoView/index.js
  app/views/ScreenLockedView.js
  app/views/SelectServerView.js
  app/views/SelectedUsersView.js
  app/views/ShareListView/index.js
  app/views/ShareView/Preview.js
  app/views/ShareView/Thumbs.js
  app/views/ShareView/index.js
  ios/Podfile
  ios/Podfile.lock
  ios/Pods/Local Podspecs/EXVideoThumbnails.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-resources.sh
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.release.xcconfig
  ios/RocketChatRN.xcodeproj/project.pbxproj
  ios/RocketChatRN/Info.plist
  ios/ShareRocketChatRN/Info.plist
  package.json
  yarn.lock
Labels: 💎 release

#2891 Merge 4.14.1 into master
  __tests__/__snapshots__/Storyshots.test.js.snap
  android/app/build.gradle
  app/containers/Passcode/Base/Dots.js
  app/containers/Passcode/Base/index.js
  app/containers/TwoFactor/index.js
  app/lib/methods/enterpriseModules.js
  app/lib/methods/getCustomEmojis.js
  app/lib/methods/getPermissions.js
  app/lib/methods/getUsersPresence.js
  app/lib/rocketchat.js
  app/presentation/RoomItem/LastMessage.js
  app/sagas/selectServer.js
  app/selectors/login.js
  app/utils/avatar.js
  app/views/ChangePasscodeView.js
  app/views/NewMessageView.js
  app/views/ProfileView/index.js
  app/views/RoomActionsView/index.js
  app/views/RoomInfoEditView/index.js
  app/views/RoomInfoView/index.js
  app/views/ScreenLockedView.js
  app/views/SelectServerView.js
  app/views/SelectedUsersView.js
  app/views/ShareListView/index.js
  app/views/ShareView/Preview.js
  app/views/ShareView/Thumbs.js
  app/views/ShareView/index.js
  ios/Podfile
  ios/Podfile.lock
  ios/Pods/Local Podspecs/EXVideoThumbnails.podspec.json
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN-resources.sh
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-ShareRocketChatRN/Pods-ShareRocketChatRN.release.xcconfig
  ios/RocketChatRN.xcodeproj/project.pbxproj
  ios/RocketChatRN/Info.plist
  ios/ShareRocketChatRN/Info.plist
  package.json
  yarn.lock
Labels: 💎 release

#2857 [IMPROVEMENT] Check for focused rooms on in-app notifications
  app/containers/InAppNotification/index.js
  app/views/RoomView/index.js
Labels: 👍 improvement

#2838 [FIX] Real name being ignored in SearchMessagesView
  app/views/SearchMessagesView/index.js
Labels: 🛠 fix

#2861 [CHORE] Remove unnecessary share reducer calls
  app/views/CreateDiscussionView/index.js
  app/views/RoomInfoEditView/index.js
Labels: 🚚 chore

#2862 [FIX] Breadcrumbs exceeding characters limit
  app/sagas/createChannel.js
  app/sagas/createDiscussion.js
  app/utils/log/events.js
  app/views/CreateChannelView.js
  app/views/CreateDiscussionView/index.js
  app/views/NewServerView/index.js
  app/views/ProfileView/index.js
Labels: 🛠 fix

#2915 [FIX] Video quality and size on iOS
  app/containers/MessageBox/index.js
Labels: 👀 needs review, 🛠 fix

#2908 [FIX] Real name setting ignored on reply preview
  app/containers/MessageBox/ReplyPreview.js
Labels: 🛠 fix

#2863 [CHORE] BackdropOpacity based on themes
  app/constants/colors.js
  app/containers/ActionSheet/ActionSheet.js
  app/containers/ReactionsModal.js
  app/containers/UIKit/MultiSelect/index.js
  app/containers/UIKit/MultiSelect/styles.js
  app/stacks/InsideStack.js
  app/views/DirectoryView/Options.js
  app/views/RoomView/ReactionPicker.js
  app/views/RoomView/index.js
  app/views/RoomsListView/ServerDropdown.js
  app/views/RoomsListView/SortDropdown/index.js
  app/views/ThreadMessagesView/Dropdown/index.js
Labels: 👀 needs review, 🚚 chore

#2905 [FIX] Support Jitsi_URL_Room_Hash
  app/constants/settings.js
  app/lib/methods/callJitsi.js
  app/lib/methods/canOpenRoom.js
  app/sagas/deepLinking.js
  app/views/RoomActionsView/index.js
  app/views/RoomInfoView/index.js
  app/views/RoomView/index.js
Labels: 🛠 fix

#2871 [FIX] Temp attachment files not being flushed after saved to gallery
  app/views/AttachmentView.js
Labels: 👀 needs review, 🛠 fix

#2869 [FIX] Thread showing typing indicator from main room
  app/views/RoomView/Header/Header.js
Labels: 👀 needs review, 🛠 fix

#2878 [FIX] DM rooms show typing status from last group room
  app/lib/methods/subscriptions/room.js
Labels: 👀 needs review, 🛠 fix

#2885 [FIX] Can't copy or edit media's description
  app/containers/MessageActions/index.js
  app/views/RoomView/index.js
Labels: 👀 needs review, 🛠 fix

#2899 [FIX] RightButtonsContainer re-render check not returning default value
  app/views/RoomView/Header/RightButtons.js
Labels: 👀 needs review, 🛠 fix

#2906 [CHORE] Remove InteractionManager blocks
  app/lib/methods/getCustomEmojis.js
  app/lib/methods/getPermissions.js
  app/lib/methods/getRoles.js
  app/lib/methods/getSlashCommands.js
  app/lib/methods/loadThreadMessages.js
  app/views/ThreadMessagesView/index.js
Labels: 👀 needs review, 🛠 fix

#2909 [FIX] App not sending second argument for EventEmitter.removeListener on some places
  app/containers/Toast.js
  app/containers/TwoFactor/index.js
  app/views/ChangePasscodeView.js
  app/views/ScreenLockedView.js
Labels: 👀 needs review, 🛠 fix

#2919 [FIX] Temp message ignoring real name
  app/lib/methods/sendMessage.js
Labels: 👀 needs review, 🛠 fix

#2888 [FIX] System message of e2e encryption missing
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/message/utils.js
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  storybook/stories/Message.js
Labels: 👀 needs review, 🛠 fix

#2914 [CHORE] Add permissions to Redux
  app/actions/actionsTypes.js
  app/actions/permissions.js
  app/containers/MessageActions/index.js
  app/lib/methods/getPermissions.js
  app/lib/rocketchat.js
  app/reducers/index.js
  app/reducers/permissions.js
  app/sagas/selectServer.js
  app/utils/isReadOnly.js
  app/views/RoomActionsView/index.js
  app/views/RoomInfoEditView/index.js
  app/views/RoomInfoView/index.js
  app/views/RoomMembersView/index.js
  app/views/RoomView/index.js
  app/views/SidebarView/index.js
Labels: ♻️ refactor, 👀 needs review, 🚚 chore

#2943 [CHORE] Add hold step for ios and android build experimental
  .circleci/config.yml
Labels: 👀 needs review, 🚚 chore

#2932 [CHORE] Use shortcut syntax for get collections
  app/containers/Avatar/index.js
  app/containers/EmojiPicker/index.js
  app/containers/MessageActions/Header.js
  app/containers/MessageActions/index.js
  app/containers/MessageBox/index.js
  app/containers/MessageErrorActions.js
  app/lib/encryption/encryption.js
  app/lib/encryption/room.js
  app/lib/methods/canOpenRoom.js
  app/lib/methods/enterpriseModules.js
  app/lib/methods/getCustomEmojis.js
  app/lib/methods/getPermissions.js
  app/lib/methods/getRoles.js
  app/lib/methods/getSettings.js
  app/lib/methods/getSlashCommands.js
  app/lib/methods/getUsersPresence.js
  app/lib/methods/helpers/findSubscriptionsRooms.js
  app/lib/methods/loadMissedMessages.js
  app/lib/methods/loadThreadMessages.js
  app/lib/methods/logout.js
  app/lib/methods/readMessages.js
  app/lib/methods/sendFileMessage.js
  app/lib/methods/sendMessage.js
  app/lib/methods/subscriptions/room.js
  app/lib/methods/subscriptions/rooms.js
  app/lib/methods/updateMessages.js
  app/lib/rocketchat.js
  app/sagas/createChannel.js
  app/sagas/createDiscussion.js
  app/sagas/deepLinking.js
  app/sagas/encryption.js
  app/sagas/init.js
  app/sagas/login.js
  app/sagas/messages.js
  app/sagas/rooms.js
  app/sagas/selectServer.js
  app/utils/localAuthentication.js
  app/views/CreateDiscussionView/SelectUsers.js
  app/views/LanguageView/index.js
  app/views/NewServerView/index.js
  app/views/RoomInfoEditView/index.js
  app/views/RoomInfoView/index.js
  app/views/RoomMembersView/index.js
  app/views/RoomView/Header/RightButtons.js
  app/views/RoomView/index.js
  app/views/RoomsListView/index.js
  app/views/ScreenLockConfigView.js
  app/views/SearchMessagesView/index.js
  app/views/SelectServerView.js
  app/views/SettingsView/index.js
  app/views/ShareListView/index.js
  app/views/ShareView/index.js
  app/views/ThreadMessagesView/index.js
Labels: 👀 needs review, 🚚 chore

#2931 [FIX] Use List.Separator in all places
  app/views/CreateChannelView.js
  app/views/DirectoryView/index.js
  app/views/NewMessageView.js
  app/views/ReadReceiptView/index.js
  app/views/RoomMembersView/index.js
  app/views/RoomsListView/ServerDropdown.js
  app/views/SelectedUsersView.js
Labels: 👀 needs review, 🛠 fix

#2947 [FIX] Limit new message list query size to 50
  app/views/NewMessageView.js
Labels: 🛠 fix

#2934 [FIX] Support chats order for older versions of the server
  app/lib/methods/helpers/mergeSubscriptionsRooms.js
Labels: 👀 needs review, 🛠 fix

#2949 [FIX] Reactions modal's backdrop color too light
  app/containers/ReactionsModal.js
Labels: 👀 needs review, 🛠 fix
