Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2021-01, with the labels that each got.

#2694 [FIX] Generate Jitsi access token when making a call
  app/sagas/deepLinking.js
Labels: 👀 needs review, 🛠 fix

#2668 [FIX] Jitsi notification delay
  ios/Shared/Models/MessageType.swift
Labels: 🚨 needs changes, 🛠 fix

#2763 [FIX] Channels list not following the same sorting logic from web client
  app/lib/methods/helpers/mergeSubscriptionsRooms.js
Labels: 🛠 fix

#2764 [FIX] Pods lost on Official target
  ios/Podfile
  ios/Podfile.lock
  ios/Pods/Manifest.lock
  ios/Pods/Pods.xcodeproj/project.pbxproj
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN-dummy.m
  ios/Pods/Target Support Files/Pods-RocketChatRN/Pods-RocketChatRN.modulemap
  ios/Pods/Target Support Files/Pods-defaults-Rocket.Chat/Pods-defaults-Rocket.Chat-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-defaults-Rocket.Chat/Pods-defaults-Rocket.Chat-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-defaults-Rocket.Chat/Pods-defaults-Rocket.Chat-dummy.m
  ios/Pods/Target Support Files/Pods-defaults-Rocket.Chat/Pods-defaults-Rocket.Chat-frameworks.sh
  ios/Pods/Target Support Files/Pods-defaults-Rocket.Chat/Pods-defaults-Rocket.Chat-resources.sh
  ios/Pods/Target Support Files/Pods-defaults-Rocket.Chat/Pods-defaults-Rocket.Chat-umbrella.h
  ios/Pods/Target Support Files/Pods-defaults-Rocket.Chat/Pods-defaults-Rocket.Chat.debug.xcconfig
  ios/Pods/Target Support Files/Pods-defaults-Rocket.Chat/Pods-defaults-Rocket.Chat.modulemap
  ios/Pods/Target Support Files/Pods-defaults-Rocket.Chat/Pods-defaults-Rocket.Chat.release.xcconfig
  ios/Pods/Target Support Files/Pods-defaults-RocketChatRN/Pods-defaults-RocketChatRN-acknowledgements.markdown
  ios/Pods/Target Support Files/Pods-defaults-RocketChatRN/Pods-defaults-RocketChatRN-acknowledgements.plist
  ios/Pods/Target Support Files/Pods-defaults-RocketChatRN/Pods-defaults-RocketChatRN-dummy.m
  ios/Pods/Target Support Files/Pods-defaults-RocketChatRN/Pods-defaults-RocketChatRN-frameworks.sh
  ios/Pods/Target Support Files/Pods-defaults-RocketChatRN/Pods-defaults-RocketChatRN-resources.sh
  ios/Pods/Target Support Files/Pods-defaults-RocketChatRN/Pods-defaults-RocketChatRN-umbrella.h
  ios/Pods/Target Support Files/Pods-defaults-RocketChatRN/Pods-defaults-RocketChatRN.debug.xcconfig
  ios/Pods/Target Support Files/Pods-defaults-RocketChatRN/Pods-defaults-RocketChatRN.modulemap
  ios/Pods/Target Support Files/Pods-defaults-RocketChatRN/Pods-defaults-RocketChatRN.release.xcconfig
  ios/RocketChatRN.xcodeproj/project.pbxproj
Labels: 🛠 fix

#2774 [FIX] Server autocomplete text breaking line
  app/views/NewServerView/ServerInput/Item.js
Labels: 👀 needs review, 🛠 fix

#2775 [FIX] ServerDropdown flashing bigger server icon
  android/app/src/main/res/drawable-hdpi/logo.png
  android/app/src/main/res/drawable-mdpi/logo.png
  android/app/src/main/res/drawable-xhdpi/logo.png
  android/app/src/main/res/drawable-xxhdpi/logo.png
  android/app/src/main/res/drawable-xxxhdpi/logo.png
  app/presentation/ServerItem/index.js
  app/static/images/logo.png
  app/views/OnboardingView/index.js
  app/views/OnboardingView/styles.js
  app/views/RoomsListView/ServerDropdown.js
  ios/RocketChatRN/Images.xcassets/logo.imageset/Contents.json
  ios/RocketChatRN/Images.xcassets/logo.imageset/icon.png
  ios/RocketChatRN/Images.xcassets/logo.imageset/icon@2x.png
  ios/RocketChatRN/Images.xcassets/logo.imageset/icon@3x.png
Labels: 👀 needs review, 🛠 fix

#2765 [FIX] Rooms list not being updated on some cases
  app/actions/server.js
  app/reducers/server.js
  app/sagas/rooms.js
  app/views/RoomsListView/ServerDropdown.js
  app/views/RoomsListView/index.js
Labels: 🐛 bug, 👀 needs review

#2686 [IMPROVEMENT] Threads layout tweaks
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/ThreadDetails.js
  app/containers/message/Thread.js
  app/containers/message/styles.js
  app/views/ThreadMessagesView/Item.js
  app/views/ThreadMessagesView/index.js
  storybook/stories/Message.js
Labels: 👀 needs review, 👍 improvement

#2792 [CHORE] Remove some migrations
  android/app/src/main/java/chat/rocket/reactnative/MainActivity.java
  app/lib/encryption/constants.js
  app/lib/userPreferences.js
  app/sagas/login.js
  ios/RocketChatRN/AppDelegate.m
Labels: 🚚 chore

#2804 [FIX] Back button closing activity when on root stack screen
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/chat/rocket/reactnative/MainActivity.java
  app/AppContainer.js
  app/actions/app.js
  app/views/OnboardingView/index.js
  app/views/RoomsListView/index.js
Labels: 🛠 fix

#2715 [i18n] Add missing German strings
  app/i18n/locales/de.js
Labels: 🌎 i18n, 👀 needs review

#2813 [NEW] Encrypted Discussions
  app/actions/actionsTypes.js
  app/actions/encryption.js
  app/i18n/locales/ar.js
  app/i18n/locales/de.js
  app/i18n/locales/en.js
  app/i18n/locales/fr.js
  app/i18n/locales/it.js
  app/i18n/locales/pt-BR.js
  app/i18n/locales/ru.js
  app/i18n/locales/zh-CN.js
  app/i18n/locales/zh-TW.js
  app/lib/encryption/encryption.js
  app/lib/rocketchat.js
  app/reducers/encryption.js
  app/sagas/encryption.js
  app/utils/log/events.js
  app/views/CreateChannelView.js
  app/views/CreateDiscussionView/SelectChannel.js
  app/views/CreateDiscussionView/index.js
  app/views/E2EEncryptionSecurityView.js
  app/views/RoomActionsView/index.js
  app/views/RoomInfoEditView/index.js
Labels: 🎉 feature, 🚨 needs changes

#2786 [FIX] Messagebox missing style for text color
  app/containers/MessageBox/index.js
Labels: 🚨 needs changes, 🛠 fix

#2696 [i18n] Update arabic
  app/i18n/locales/ar.js
Labels: 🌎 i18n

#2689 [FIX] Workspace input without i18n
  app/i18n/locales/en.js
  app/i18n/locales/pt-BR.js
  app/views/NewServerView/ServerInput/index.js
Labels: 🚨 needs changes, 🛠 fix

#2805 [FIX] Spotlight returning duplicated entries
  app/lib/rocketchat.js
  e2e/tests/assorted/05-joinpublicroom.spec.js
  e2e/tests/assorted/08-joinprotectedroom.spec.js
  e2e/tests/onboarding/06-roomslist.spec.js
  e2e/tests/room/01-createroom.spec.js
  e2e/tests/room/03-roomactions.spec.js
  e2e/tests/room/04-roominfo.spec.js
  package.json
Labels: 🚨 needs changes, 🛠 fix

#2778 [CHORE] Refactor ServerItem
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/presentation/ServerItem/index.js
  app/presentation/ServerItem/styles.js
  app/views/RoomsListView/ServerDropdown.js
  app/views/SelectServerView.js
  storybook/stories/ServerItem.js
  storybook/stories/index.js
Labels: ♻️ refactor, 👀 needs review, 🚚 chore

#2802 [DOCS] Updated Quick Start docs link in e2e/readme
  e2e/README.md
Labels: 📝 docs

#2793 [I18N] Add Turkish
  app/i18n/index.js
  app/i18n/locales/tr.js
Labels: 🌎 i18n

#2818 [FIX] Lint on #2793
  app/i18n/locales/tr.js
Labels: 🛠 fix

#2817 [I18N] Add missing italian strings
  app/i18n/locales/it.js
Labels: 🌎 i18n, 👀 needs review

#2821 [FIX] Server version becoming null on server change
  app/views/RoomsListView/ServerDropdown.js
Labels: 🛠 fix

#2767 [FIX] Wrong styling on E2E encryption banner
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/constants/colors.js
  app/containers/List/ListItem.js
  app/ee/omnichannel/containers/OmnichannelStatus.js
  app/utils/touch.js
  app/views/RoomsListView/ListHeader/Encryption.js
  app/views/RoomsListView/ListHeader/Sort.js
  app/views/RoomsListView/ListHeader/index.js
  app/views/RoomsListView/SortDropdown/Item.js
  app/views/RoomsListView/SortDropdown/index.js
  app/views/RoomsListView/styles.js
  storybook/stories/List.js
Labels: 👀 needs review, 🛠 fix

#2826 [FIX] App Store using Experimental's app id
  app/constants/links.js
Labels: 🛠 fix

#2825 [FIX] Wrong username on push notifications
  android/app/src/play/java/chat/rocket/reactnative/CustomPushNotification.java
Labels: 🛠 fix
