Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2021-03, with the labels that each got.

#2963 [FIX] Share extension not working correctly on Official app
  .circleci/config.yml
  ios/NotificationService/Info.plist
  ios/ShareRocketChatRN/Info.plist
Labels: 👷 ci, 🛠 fix

#2966 [FIX] Cannot read property 'some' of undefined on hasPermission
  app/lib/rocketchat.js
Labels: ✅ needs tests, 🛠 fix

#2894 [FIX] Deep linking and other connectivity issues
  android/app/src/main/AndroidManifest.xml
  app/containers/InAppNotification/index.js
  app/index.js
  app/lib/methods/subscriptions/rooms.js
  app/lib/rocketchat.js
  app/sagas/deepLinking.js
  app/sagas/state.js
  app/utils/localAuthentication.js
  app/views/RoomsListView/index.js
  ios/ReplyNotification.swift
  ios/RocketChatRN-Bridging-Header.h
  package.json
  yarn.lock
Labels: 👀 needs review, 🛠 fix

#2968 [FIX] Messagebox's placeholder color is too bright
  app/containers/MessageBox/index.js
Labels: 🛠 fix

#2860 [IMPROVEMENT] Message attachment colors
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/message/Reply.js
  package.json
  storybook/stories/Message.js
  yarn.lock
Labels: 👍 improvement

#2798 [FIX] App forgetting workspace when server is not finished added
  app/lib/methods/logout.js
  app/sagas/init.js
  app/sagas/login.js
  app/share.js
  app/views/RoomsListView/Header/Header.js
  e2e/tests/assorted/07-changeserver.spec.js
Labels: 🛠 fix

#2960 [TESTS] Add E2E tests to draft message
  e2e/tests/room/02-room.spec.js
Labels: ✅ tests

#2961 [TESTS] Add E2E tests to group DM
  e2e/tests/room/05-createdmgroup.spec.js
Labels: ✅ tests

#2964 [TESTS] Add E2E tests to directory
  app/views/DirectoryView/index.js
  e2e/tests/assorted/09-joinfromdirectory.spec.js
Labels: ✅ tests

#2922 [CHORE] Simplify server version comparison
  app/lib/methods/enterpriseModules.js
  app/lib/methods/getCustomEmojis.js
  app/lib/methods/getPermissions.js
  app/lib/methods/getUsersPresence.js
  app/lib/methods/helpers/mergeSubscriptionsRooms.js
  app/lib/rocketchat.js
  app/lib/utils.js
  app/utils/avatar.js
  app/views/RoomActionsView/index.js
  app/views/RoomInfoEditView/index.js
Labels: 👀 needs review, 🚚 chore

#2970 [TESTS] Add E2E tests to discussions
  app/containers/UIKit/MultiSelect/Items.js
  app/containers/UIKit/MultiSelect/index.js
  app/presentation/RoomItem/index.js
  app/views/CreateDiscussionView/index.js
  app/views/RoomsListView/index.js
  e2e/tests/room/04-discussion.spec.js
  e2e/tests/room/05-roominfo.spec.js
Labels: ✅ tests

#2924 [FIX] Attachment not rendering markdown
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/message/Reply.js
  storybook/stories/Message.js
Labels: 🛠 fix

#2953 [TESTS] Add e2e tests for mark message as unread
  __tests__/__snapshots__/Storyshots.test.js.snap
  e2e/helpers/data_setup.js
  e2e/tests/room/02-room.spec.js
  e2e/tests/room/06-markasunread.spec.js
Labels: ✅ tests, 👀 needs review

#2954 [TESTS] Add E2E tests to delete server
  e2e/tests/assorted/10-deleteserver.spec.js
Labels: ✅ tests, 👀 needs review

#2872 [CHORE] Refactor RoomActionsView permissions
  app/views/RoomActionsView/index.js
Labels: 👀 needs review, 🛠 fix

#2989 [CHORE] Add status and teams icons
  android/app/src/main/assets/fonts/custom.ttf
  app/lib/selection.json
  ios/custom.ttf
Labels: 👀 needs review, 🚚 chore

#2978 [FIX] SSO not working with 2FA (TOTP)
  app/lib/rocketchat.js
  app/views/AuthenticationWebView.js
Labels: 🛠 fix

#2991 [IMPROVEMENT] User status icons
  __tests__/__snapshots__/Storyshots.test.js.snap
  android/app/src/main/assets/fonts/custom.ttf
  app/constants/colors.js
  app/containers/RoomTypeIcon.js
  app/containers/Status/Status.js
  app/containers/Status/index.js
  app/lib/methods/getUsersPresence.js
  app/lib/selection.json
  app/presentation/RoomItem/RoomItem.js
  app/presentation/RoomItem/TypeIcon.js
  app/presentation/RoomItem/index.js
  app/presentation/RoomItem/styles.js
  app/views/RoomActionsView/index.js
  app/views/RoomInfoView/index.js
  app/views/RoomInfoView/styles.js
  app/views/RoomView/Header/Header.js
  app/views/RoomView/Header/Icon.js
  app/views/RoomView/Header/index.js
  app/views/RoomView/index.js
  app/views/SidebarView/index.js
  app/views/SidebarView/styles.js
  app/views/StatusView.js
  app/views/Styles.js
  ios/custom.ttf
  storybook/stories/Avatar.js
  storybook/stories/RoomItem.js
Labels: 👍 improvement

#3015 [REGRESSION] Auth via deep linking not working
  app/sagas/deepLinking.js
  e2e/data/data.docker.js
  e2e/helpers/app.js
  e2e/helpers/data_setup.js
  e2e/tests/assorted/07-changeserver.spec.js
  e2e/tests/assorted/10-deleteserver.spec.js
  e2e/tests/assorted/11-deeplinking.spec.js
Labels: ✅ tests, 👀 needs review, 🛠 fix
