Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2021-06, with the labels that each got.

#3164 [NEW] Convert/Move Channel to Team
  app/containers/RoomHeader/index.js
  app/i18n/locales/en.json
  app/lib/methods/getPermissions.js
  app/lib/rocketchat.js
  app/views/RoomActionsView/index.js
  app/views/RoomView/RightButtons.js
  app/views/RoomView/index.js
  app/views/SelectListView.js
Labels: 🎉 feature, 👀 needs review

#3178 [TEST] E2E Tests for Teams
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/ActionSheet/Item.js
  app/containers/List/ListIcon.js
  app/i18n/locales/en.json
  app/presentation/RoomItem/RoomItem.js
  app/presentation/RoomItem/Tag.js
  app/views/AddChannelTeamView.js
  app/views/AddExistingChannelView.js
  app/views/CreateChannelView.js
  app/views/RoomActionsView/index.js
  app/views/RoomMembersView/index.js
  app/views/SelectListView.js
  app/views/TeamChannelsView.js
  e2e/data/data.cloud.js
  e2e/data/data.docker.js
  e2e/helpers/app.js
  e2e/tests/assorted/05-joinpublicroom.spec.js
  e2e/tests/room/02-room.spec.js
  e2e/tests/room/03-roomactions.spec.js
  e2e/tests/room/04-discussion.spec.js
  e2e/tests/team/01-createteam.spec.js
  e2e/tests/team/02-team.spec.js
  e2e/tests/team/03-moveconvert.spec.js
Labels: ✅ tests, 👀 needs review

#3181 [NEW] Teams Directory
  app/i18n/locales/en.json
  app/lib/rocketchat.js
  app/presentation/DirectoryItem/index.js
  app/views/DirectoryView/Options.js
  app/views/DirectoryView/index.js
  e2e/tests/assorted/09-joinfromdirectory.spec.js
Labels: 🎉 feature, 👀 needs review

#3182 [CHORE] logEvents for Teams
  app/utils/log/events.js
  app/views/AddExistingChannelView.js
  app/views/RoomActionsView/index.js
  app/views/RoomInfoEditView/index.js
  app/views/TeamChannelsView.js
Labels: 👀 needs review, 🚚 chore

#3187 [FIX] Item not animating on tap on team's channels view
  app/views/TeamChannelsView.js
Labels: 👀 needs review, 🛠 fix

#3161 [FIX] App not showing proper alert on team leave
  app/actions/room.js
  app/i18n/locales/en.json
  app/reducers/room.js
  app/sagas/room.js
  app/views/RoomActionsView/index.js
Labels: 🚨 needs changes, 🛠 fix

#3134 [NEW] Support Google OAuth from external browser
  app/containers/LoginServices.js
  app/sagas/deepLinking.js
Labels: 🎉 feature, 👀 needs review

#3199 [FIX] RoomItem's long press crashing the app if prop is missing
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/presentation/RoomItem/index.js
  storybook/stories/RoomItem.js
Labels: 👀 needs review, 🛠 fix

#3204 [FIX] Crashing on link press
  app/containers/markdown/Link.js
Labels: 🛠 fix

#3195 [FIX] Don't show Block Button inside Group DM Actions
  app/views/RoomActionsView/index.js
Labels: 👀 needs review, 🛠 fix

#3202 [TEST] E2E for Jump to Message
  app/containers/Loading.js
  app/views/RoomView/List/NavBottomFAB.js
  app/views/SidebarView/index.js
  e2e/docker/docker-entrypoint-initdb.d/rocketchat_message.js
  e2e/docker/docker-entrypoint-initdb.d/rocketchat_room.js
  e2e/docker/docker-entrypoint-initdb.d/rocketchat_settings.js
  e2e/docker/docker-entrypoint-initdb.d/rocketchat_subscription.js
  e2e/tests/room/09-jumptomessage.spec.js
Labels: ✅ tests, 🚨 needs changes
