Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2021-05, with the labels that each got.

#3062 [FIX] App making calls to DDP after socket was killed by OS
  app/lib/rocketchat.js
Labels: 👀 needs review, 🛠 fix

#3082 [NEW] Create Team
  app/definition/ITeam.js
  app/i18n/locales/en.json
  app/lib/rocketchat.js
  app/sagas/createChannel.js
  app/utils/log/events.js
  app/utils/room.js
  app/views/CreateChannelView.js
  app/views/NewMessageView.js
  app/views/RoomView/RightButtons.js
  app/views/RoomView/index.js
  app/views/SelectedUsersView.js
  e2e/data.js
  e2e/helpers/data_setup.js
  e2e/tests/team/01-createteam.spec.js
Labels: 🎉 feature, 🚨 needs changes

#3090 [NEW] Add/Create/Remove channel on a team
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/ActionSheet/Item.js
  app/containers/ActionSheet/styles.js
  app/containers/RoomTypeIcon.js
  app/i18n/locales/en.json
  app/lib/methods/getPermissions.js
  app/lib/rocketchat.js
  app/presentation/RoomItem/RoomItem.js
  app/presentation/RoomItem/Tag.js
  app/presentation/RoomItem/Touchable.js
  app/presentation/RoomItem/index.js
  app/presentation/RoomItem/styles.js
  app/sagas/createChannel.js
  app/stacks/InsideStack.js
  app/stacks/MasterDetailStack/index.js
  app/utils/log/events.js
  app/views/AddChannelTeamView.js
  app/views/AddExistingChannelView.js
  app/views/CreateChannelView.js
  app/views/NewMessageView.js
  app/views/TeamChannelsView.js
  storybook/stories/RoomItem.js
Labels: 🎉 feature, 👀 needs review

#3147 [FIX] Tests not working by ES6 import
  e2e/helpers/data_setup.js
Labels: 👀 needs review, 🛠 fix

#3116 [NEW] Leave Teams
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/containers/List/ListIcon.js
  app/containers/List/ListItem.js
  app/containers/List/constants.js
  app/i18n/locales/en.json
  app/lib/rocketchat.js
  app/stacks/InsideStack.js
  app/stacks/MasterDetailStack/index.js
  app/views/RoomActionsView/index.js
  app/views/SelectListView.js
  storybook/stories/List.js
Labels: 🎉 feature, 👀 needs review

#3099 [NEW] Jump to message
  __tests__/__snapshots__/Storyshots.test.js.snap
  app/constants/messageTypeLoad.js
  app/containers/markdown/Link.js
  app/containers/markdown/index.js
  app/containers/message/Content.js
  app/containers/message/Message.js
  app/containers/message/RepliedThread.js
  app/containers/message/Reply.js
  app/containers/message/Urls.js
  app/containers/message/index.js
  app/i18n/locales/en.json
  app/lib/database/model/Message.js
  app/lib/database/model/Subscription.js
  app/lib/database/model/Thread.js
  app/lib/database/model/ThreadMessage.js
  app/lib/database/services/Message.js
  app/lib/database/services/Subscription.js
  app/lib/database/services/Thread.js
  app/lib/database/services/ThreadMessage.js
  app/lib/methods/getRoomInfo.js
  app/lib/methods/getSingleMessage.js
  app/lib/methods/getThreadName.js
  app/lib/methods/loadMessagesForRoom.js
  app/lib/methods/loadNextMessages.js
  app/lib/methods/loadSurroundingMessages.js
  app/lib/methods/loadThreadMessages.js
  app/lib/methods/updateMessages.js
  app/lib/rocketchat.js
  app/lib/utils.js
  app/notifications/push/index.js
  app/sagas/deepLinking.js
  app/utils/goRoom.js
  app/views/MessagesView/index.js
  app/views/RoomActionsView/index.js
  app/views/RoomView/List/List.js
  app/views/RoomView/List/NavBottomFAB.js
  app/views/RoomView/List/index.js
  app/views/RoomView/LoadMore/LoadMore.stories.js
  app/views/RoomView/LoadMore/index.js
  app/views/RoomView/RightButtons.js
  app/views/RoomView/index.js
  app/views/RoomView/services/getMessageInfo.js
  app/views/RoomView/services/getMessages.js
  app/views/RoomView/services/getMoreMessages.js
  app/views/RoomView/services/getThreadMessages.js
  app/views/RoomView/services/index.js
  app/views/RoomView/services/readMessages.js
  app/views/RoomView/styles.js
  app/views/SearchMessagesView/index.js
  storybook/stories/Message.js
  storybook/stories/index.js
Labels: 🎉 feature, 🚧 wip

#3159 [FIX] Method calls not sending date params as EJSON
  app/lib/rocketchat.js
Labels: 🛠 fix

#3117 [NEW] Remove member from team
  app/i18n/locales/en.json
  app/lib/methods/getPermissions.js
  app/lib/rocketchat.js
  app/views/RoomActionsView/index.js
  app/views/RoomMembersView/index.js
  app/views/SelectListView.js
Labels: 🎉 feature, 👀 needs review

#3151 [FIX] Add Existing Channel screen showing discussions and channels without permission
  app/views/AddExistingChannelView.js
Labels: 🚨 needs changes, 🛠 fix

#3129 [FIX] Member search not trimming search text
  app/views/RoomMembersView/index.js
Labels: 🚨 needs changes, 🛠 fix

#3155 [FIX] Check permissions on team channels action sheet
  app/views/TeamChannelsView.js
Labels: 🛠 fix

#3137 [IMPROVEMENT] Allow discussions to be edited
  app/views/RoomInfoView/index.js
  e2e/tests/room/04-discussion.spec.js
Labels: ✅ needs tests, 🚨 needs changes, 🛠 fix

#3123 [NEW] Delete Teams
  app/i18n/locales/en.json
  app/lib/methods/getPermissions.js
  app/lib/rocketchat.js
  app/views/RoomInfoEditView/index.js
  app/views/TeamChannelsView.js
Labels: 🎉 feature, 🚨 needs changes

#3171 [FIX] Check for old servers for Teams
  app/views/NewMessageView.js
Labels: 👀 needs review, 🛠 fix
