Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2022-06, with the labels that each got.

#4120 Chore: upgrade react navigation to 6.0.10 version
  android/build.gradle
  app/containers/Header/index.tsx
  app/containers/RoomHeader/__snapshots__/RoomHeader.stories.storyshot
  app/lib/navigation/appNavigation.ts
  app/lib/navigation/shareNavigation.ts
  app/stacks/InsideStack.tsx
  app/stacks/MasterDetailStack/index.tsx
  app/stacks/OutsideStack.tsx
  app/utils/navigation/index.ts
  app/views/AttachmentView.tsx
  app/views/CannedResponsesListView/index.tsx
  app/views/DiscussionsView/index.tsx
  app/views/RoomView/LeftButtons.tsx
  app/views/RoomView/index.tsx
  app/views/RoomsListView/Header/Header.tsx
  app/views/TeamChannelsView.tsx
  app/views/ThreadMessagesView/index.tsx
  ios/Podfile.lock
  package.json
  storybook/stories/__snapshots__/HeaderButtons.storyshot
  yarn.lock
Labels: 👍 improvement, 🚚 chore, 👀 needs review

#4220 [FIX] Form re-rendering on RoomInfoEditView when app receives newer data from stream
  app/views/RoomInfoEditView/index.tsx
Labels: 🛠 fix

#4060 [NEW] Call to Action buttons for Omnichannel
  app/containers/MessageBox/index.tsx
  app/definitions/IRoom.ts
  app/i18n/locales/ar.json
  app/i18n/locales/de.json
  app/i18n/locales/en.json
  app/i18n/locales/fr.json
  app/i18n/locales/it.json
  app/i18n/locales/nl.json
  app/i18n/locales/pt-BR.json
  app/i18n/locales/ru.json
  app/i18n/locales/tr.json
  app/i18n/locales/zh-CN.json
  app/i18n/locales/zh-TW.json
  app/lib/methods/helpers/log/events.ts
  app/stacks/MasterDetailStack/types.ts
  app/stacks/types.ts
  app/views/RoomActionsView/index.tsx
  app/views/RoomView/RightButtons.tsx
  app/views/RoomView/index.tsx
Labels: 🎉 feature, 👀 needs review, ♻️ refactor

#4267 [FIX] Searching for users when creating Discussions
  app/views/CreateDiscussionView/SelectUsers.tsx
Labels: 🛠 fix

#4265 [NEW] Option to show mentions badge
  app/containers/RoomItem/RoomItem.tsx
  app/containers/RoomItem/index.tsx
  app/containers/RoomItem/interfaces.ts
  app/containers/UnreadBadge/index.tsx
  app/definitions/ISubscription.ts
  app/i18n/locales/ar.json
  app/i18n/locales/de.json
  app/i18n/locales/en.json
  app/i18n/locales/es-ES.json
  app/i18n/locales/fr.json
  app/i18n/locales/it.json
  app/i18n/locales/ja.json
  app/i18n/locales/nl.json
  app/i18n/locales/pt-BR.json
  app/i18n/locales/ru.json
  app/i18n/locales/tr.json
  app/i18n/locales/zh-CN.json
  app/i18n/locales/zh-TW.json
  app/lib/database/model/Subscription.js
  app/lib/database/model/migrations.js
  app/lib/database/schema/app.js
  app/lib/methods/helpers/mergeSubscriptionsRooms.ts
  app/lib/methods/subscriptions/rooms.ts
  app/views/NotificationPreferencesView/index.tsx
  e2e/tests/room/03-roomactions.spec.js
Labels: 🎉 feature

#4200 Chore: Hooks - migrate RoomHeader to hook
  app/containers/RoomHeader/RoomHeader.stories.js
  app/containers/RoomHeader/RoomHeader.tsx
  app/containers/RoomHeader/index.tsx
  app/views/RoomView/index.tsx
Labels: 🚚 chore

#4285 [FIX] Avatar pixel size
  app/lib/methods/helpers/getAvatarUrl.ts
  app/views/DiscussionsView/__snapshots__/Item.stories.storyshot
  app/views/RoomView/LoadMore/__snapshots__/LoadMore.stories.storyshot
  app/views/ThreadMessagesView/__snapshots__/Item.stories.storyshot
  storybook/stories/__snapshots__/Avatar.storyshot
  storybook/stories/__snapshots__/Message.storyshot
Labels: 🛠 fix

#4286 [FIX] Remove servers offline from server list
  app/lib/methods/logout.ts
Labels: 🛠 fix

#4216 Chore: Migrate LoginServices to Hooks
  app/containers/LoginServices.tsx
  app/containers/LoginServices/ButtonService.tsx
  app/containers/LoginServices/LoginServices.stories.js
  app/containers/LoginServices/Service.tsx
  app/containers/LoginServices/ServicesSeparator.tsx
  app/containers/LoginServices/__snapshots__/LoginServices.stories.storyshot
  app/containers/LoginServices/index.tsx
  app/containers/LoginServices/interfaces.ts
  app/containers/LoginServices/serviceLogin.ts
  app/containers/LoginServices/styles.ts
  app/views/LoginView.tsx
  app/views/RegisterView.tsx
  storybook/stories/index.js
Labels: 🚚 chore

#4305 [FIX] Announcement field triggers password suggestion
  app/views/RoomInfoEditView/index.tsx
Labels: 🛠 fix

#4256 Chore: Migration to Hooks - FormTextInput
  app/containers/MessageBox/index.tsx
  app/containers/SearchBox/__snapshots__/SearchBox.stories.storyshot
  app/containers/SearchBox/index.tsx
  app/containers/SearchHeader.tsx
  app/containers/TextInput/FormTextInput.test.tsx
  app/containers/TextInput/FormTextInput.tsx
  app/containers/TextInput/TextInput.stories.js
  app/containers/TextInput/TextInput.tsx
  app/containers/TextInput/index.ts
  app/containers/TextInput/index.tsx
  app/containers/TwoFactor/index.tsx
  app/containers/UIKit/MultiSelect/index.tsx
  app/containers/UIKit/index.tsx
  app/lib/constants/defaultSettings.ts
  app/lib/services/restApi.ts
  app/views/CreateChannelView.tsx
  app/views/CreateDiscussionView/index.tsx
  app/views/E2EEncryptionSecurityView.tsx
  app/views/E2EEnterYourPasswordView.tsx
  app/views/ForgotPasswordView.tsx
  app/views/InviteUsersView/index.tsx
  app/views/LivechatEditView.tsx
  app/views/LoginView.tsx
  app/views/NewServerView/ServerInput/index.tsx
  app/views/ProfileView/components/DeleteAccountActionSheetContent/index.tsx
  app/views/ProfileView/index.tsx
  app/views/RegisterView.tsx
  app/views/RoomInfoEditView/index.tsx
  app/views/RoomView/JoinCode.tsx
  app/views/RoomsListView/Header/Header.tsx
  app/views/SearchMessagesView/index.tsx
  app/views/SendEmailConfirmationView.tsx
  app/views/SetUsernameView.tsx
  app/views/ShareListView/Header/Header.tsx
  app/views/ShareListView/Header/SearchBox.tsx
  app/views/ShareView/index.tsx
  app/views/StatusView/index.tsx
Labels: 🚚 chore

#4300 [IMPROVE] Migrate away from react-native-prompt-android to action sheet
  app/actions/actionsTypes.ts
  app/actions/room.ts
  app/containers/ActionSheet/ActionSheetContentWithInputAndSubmit/index.tsx
  app/containers/ActionSheet/FooterButtons.tsx
  app/containers/ActionSheet/styles.ts
  app/ee/omnichannel/containers/CloseLivechatSheet/index.tsx
  app/externalModules.d.ts
  app/lib/methods/helpers/closeLivechat.ts
  app/lib/services/restApi.ts
  app/reducers/room.test.ts
  app/sagas/room.js
  app/stacks/MasterDetailStack/index.tsx
  app/views/ProfileView/components/DeleteAccountActionSheetContent/index.tsx
  app/views/ProfileView/index.tsx
  app/views/RoomActionsView/index.tsx
  app/views/RoomView/RightButtons.tsx
  package.json
  yarn.lock
Labels: 👍 improvement

#4264 Chore: Migration to Hooks - Markdown
  app/containers/Avatar/Avatar.tsx
  app/containers/EmojiPicker/CustomEmoji.tsx
  app/containers/UIKit/index.tsx
  app/containers/markdown/AtMention.tsx
  app/containers/markdown/BlockQuote.tsx
  app/containers/markdown/Emoji.tsx
  app/containers/markdown/Hashtag.tsx
  app/containers/markdown/Link.tsx
  app/containers/markdown/ListItem.tsx
  app/containers/markdown/Table.tsx
  app/containers/markdown/TableCell.tsx
  app/containers/markdown/TableRow.tsx
  app/containers/markdown/index.tsx
  app/containers/markdown/markdown.test.tsx
  app/containers/markdown/new/Code.tsx
  app/containers/markdown/new/Emoji.tsx
  app/containers/markdown/new/Heading.tsx
  app/containers/markdown/new/Image.tsx
  app/containers/markdown/new/Inline.tsx
  app/containers/markdown/new/InlineCode.tsx
  app/containers/markdown/new/Link.tsx
  app/containers/markdown/new/OrderedList.tsx
  app/containers/markdown/new/Paragraph.tsx
  app/containers/markdown/new/Plain.tsx
  app/containers/markdown/new/Quote.tsx
  app/containers/markdown/new/TaskList.tsx
  app/containers/markdown/new/UnorderedList.tsx
  app/containers/message/Audio.tsx
  app/containers/message/Components/CollapsibleQuote/index.tsx
  app/containers/message/Content.tsx
  app/containers/message/Image.tsx
  app/containers/message/Reply.tsx
  app/containers/message/Video.tsx
  app/definitions/IEmoji.ts
  app/views/CannedResponseDetail.tsx
  app/views/E2EHowItWorksView.tsx
  app/views/InviteUsersView/index.tsx
  app/views/RoomInfoView/Item.tsx
  app/views/RoomView/Banner.tsx
  app/views/RoomView/LoadMore/LoadMore.stories.js
  app/views/SearchMessagesView/index.tsx
  storybook/stories/Markdown.tsx
  storybook/stories/__snapshots__/Avatar.storyshot
  storybook/stories/__snapshots__/Markdown.storyshot
  storybook/stories/__snapshots__/Message.storyshot
  storybook/stories/__snapshots__/NewMarkdown.storyshot
Labels: 🚚 chore
