Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2022-02, with the labels that each got.

#3627 Chore: Migrate redux module server to TypeScript
  app/actions/server.js
  app/actions/server.ts
  app/definitions/redux/index.ts
  app/reducers/server.test.ts
  app/reducers/server.ts
Labels: 🚚 chore, 👀 needs review

#3652 Chore: Change console.log to console.error on log()
  app/utils/log/index.ts
Labels: 🚚 chore

#3632 [FIX] Remove Non-null assertion operator in ThreadMessagesView
  app/definitions/redux/index.ts
  app/views/ThreadMessagesView/index.tsx
Labels: 🚚 chore

#3499 Chore: Migrate LivechatEditView to Typescript
  app/containers/SearchBox.tsx
  app/containers/TextInput.tsx
  app/containers/UIKit/MultiSelect/index.tsx
  app/definitions/ITagsOmnichannel.ts
  app/definitions/IVisitor.ts
  app/presentation/TextInput.tsx
  app/views/E2EEnterYourPasswordView.tsx
  app/views/LivechatEditView.tsx
Labels: 🚚 chore

#3680 Regression: Message press navigating to empty RoomView
  app/containers/message/index.tsx
Labels: 👀 needs review, 🛠 fix

#3637 Chore: Migrate lib/utils to TypeScript
  app/containers/Avatar/interfaces.ts
  app/containers/message/Reply.tsx
  app/containers/message/Video.tsx
  app/lib/methods/enterpriseModules.js
  app/lib/methods/getCustomEmojis.js
  app/lib/methods/getPermissions.js
  app/lib/methods/getUsersPresence.js
  app/lib/methods/helpers/mergeSubscriptionsRooms.js
  app/lib/rocketchat.js
  app/lib/utils.js
  app/lib/utils.ts
  app/utils/avatar.ts
  app/views/AttachmentView.tsx
  app/views/NewMessageView.tsx
  app/views/RoomActionsView/index.js
  app/views/RoomInfoEditView/index.js
  app/views/RoomView/List/index.js
  app/views/SearchMessagesView/index.tsx
  package.json
  yarn.lock
Labels: 🚚 chore, 👀 needs review

#3669 Chore: Migrate readMessages to TS
  app/definitions/IRocketChat.ts
  app/lib/methods/readMessages.ts
Labels: 🚚 chore, 👀 needs review

#3606 [NEW] Stream to get individual presence updates
  app/actions/actionsTypes.ts
  app/actions/activeUsers.ts
  app/lib/methods/getUsersPresence.js
  app/lib/rocketchat.js
  app/reducers/activeUsers.test.ts
  app/reducers/activeUsers.ts
  app/sagas/login.js
  app/sagas/selectServer.js
  package.json
  yarn.lock
Labels: 👍 improvement

#3687 [IMPROVE] Add support for ephemeral messages inside threads
  app/lib/methods/subscriptions/rooms.js
Labels: 👍 improvement

#3700 Chore: Migrate methods/getSingleMessage to TS
  app/lib/methods/getSingleMessage.ts
Labels: 🚚 chore, 👀 needs review

#3702 Chore: Migrate methods/getRooms to TS
  app/lib/methods/getRooms.js
  app/lib/methods/getRooms.ts
Labels: 🚚 chore, 👀 needs review

#3731 Chore: Migrate selector/login to TS
  app/selectors/login.js
  app/selectors/login.ts
  app/views/UserPreferencesView/index.tsx
Labels: 🚚 chore, 👀 needs review

#3742 Chore: Migrate methods/helpers/parseQuery to Typescript
  app/lib/methods/helpers/parseQuery.js
  app/lib/methods/helpers/parseQuery.ts
Labels: 🚚 chore

#3697 Chore: Migrate app/commands to typescript
  app/commands.ts
Labels: 🚚 chore

#3639 Chore: Migrate lib/encryption folder to TypeScript
  app/definitions/IMessage.ts
  app/definitions/ISubscription.ts
  app/definitions/IThread.ts
  app/definitions/IThreadMessage.ts
  app/definitions/IUser.ts
  app/lib/encryption/constants.ts
  app/lib/encryption/encryption.ts
  app/lib/encryption/index.ts
  app/lib/encryption/room.ts
  app/lib/encryption/utils.ts
  app/utils/base64-js/index.ts
  app/utils/deferred.js
  app/utils/deferred.ts
  package.json
  yarn.lock
Labels: 🚚 chore, 👀 needs review

#3698 Chore: Migrate redux actions/enterpriseModules to TS
  app/actions/enterpriseModules.js
  app/actions/enterpriseModules.ts
  app/definitions/redux/index.ts
  app/reducers/enterpriseModules.js
  app/reducers/enterpriseModules.test.ts
  app/reducers/enterpriseModules.ts
Labels: 🚚 chore

#3708 Chore: Migrate database/services and database/utils to TS
  app/lib/database/services/Message.ts
  app/lib/database/services/Thread.ts
  app/lib/database/services/ThreadMessage.ts
  app/lib/database/utils.js
  app/lib/database/utils.test.ts
  app/lib/database/utils.ts
Labels: 🚚 chore

#3732 Chore: Migrate buildMessage to TS
  app/containers/MessageActions/index.tsx
  app/definitions/IMessage.ts
  app/definitions/IThread.ts
  app/definitions/IThreadMessage.ts
  app/lib/encryption/encryption.ts
  app/lib/methods/helpers/buildMessage.ts
  app/lib/methods/updateMessages.ts
  app/lib/rocketchat/methods/getPermalinkMessage.ts
Labels: 🚚 chore, 👀 needs review

#3621 [FIX] Add search and fix pagination for omnichannels departments
  app/lib/rocketchat/rocketchat.js
  app/lib/rocketchat/services/restApi.ts
  app/stacks/types.ts
  app/views/ForwardLivechatView.tsx
  app/views/PickerView.tsx
Labels: 🛠 fix

#3558 Chore: Migrate Markdown to Typescript
  app/containers/Avatar/Avatar.tsx
  app/containers/Avatar/interfaces.ts
  app/containers/EmojiPicker/CustomEmoji.tsx
  app/containers/EmojiPicker/EmojiCategory.tsx
  app/containers/EmojiPicker/index.tsx
  app/containers/MessageActions/Header.tsx
  app/containers/MessageBox/Mentions/MentionEmoji.tsx
  app/containers/MessageBox/Mentions/MentionItem.tsx
  app/containers/MessageBox/ReplyPreview.tsx
  app/containers/MessageBox/index.tsx
  app/containers/ReactionsModal.tsx
  app/containers/RoomHeader/RoomHeader.tsx
  app/containers/UIKit/index.tsx
  app/containers/markdown/AtMention.tsx
  app/containers/markdown/Emoji.tsx
  app/containers/markdown/Hashtag.tsx
  app/containers/markdown/Link.tsx
  app/containers/markdown/List.tsx
  app/containers/markdown/Preview.tsx
  app/containers/markdown/formatHyperlink.test.ts
  app/containers/markdown/formatHyperlink.ts
  app/containers/markdown/formatText.test.ts
  app/containers/markdown/formatText.ts
  app/containers/markdown/index.tsx
  app/containers/markdown/interfaces.ts
  app/containers/markdown/new/MarkdownContext.ts
  app/containers/markdown/new/index.tsx
  app/containers/message/Audio.tsx
  app/containers/message/Content.tsx
  app/containers/message/Image.tsx
  app/containers/message/Reactions.tsx
  app/containers/message/RepliedThread.tsx
  app/containers/message/Reply.tsx
  app/containers/message/Video.tsx
  app/containers/message/index.tsx
  app/containers/message/interfaces.ts
  app/containers/message/utils.ts
  app/definitions/IEmoji.ts
  app/definitions/IMessage.ts
  app/presentation/RoomItem/LastMessage.tsx
  app/views/DiscussionsView/Item.tsx
  app/views/E2EHowItWorksView.tsx
  app/views/InviteUsersView/index.tsx
  app/views/MessagesView/index.tsx
  app/views/RoomActionsView/index.js
  app/views/RoomInfoView/index.js
  app/views/RoomView/Banner.js
  app/views/RoomView/LoadMore/__snapshots__/LoadMore.stories.storyshot
  app/views/SearchMessagesView/index.tsx
  app/views/ThreadMessagesView/Item.tsx
  app/views/ThreadMessagesView/index.tsx
  storybook/stories/Markdown.tsx
  storybook/stories/__snapshots__/Message.storyshot
Labels: 🚚 chore

#3724 Chore: Migrate getCustomEmojis to TS
  app/definitions/ICustomEmoji.ts
  app/definitions/rest/v1/emojiCustom.ts
  app/lib/methods/getCustomEmojis.ts
Labels: 🚚 chore, 👀 needs review

#3711 Chore: Migrate getSlashCommands to TS
  app/definitions/ISlashCommand.ts
  app/lib/methods/getSlashCommands.js
  app/lib/methods/getSlashCommands.ts
Labels: 🚚 chore, 👀 needs review

#3741 Chore: Migrate methods/getRoles to Typescript
  app/lib/methods/getRoles.ts
Labels: 🚚 chore, 👀 needs review

#3701 Chore: Migrate methods/loadMessagesForRoom to Typescript
  app/definitions/IRoom.ts
  app/lib/methods/loadMessagesForRoom.ts
  app/lib/methods/updateMessages.ts
Labels: 🚚 chore, 👀 needs review

#3683 Chore: Migrate methods/sendFileMessage to typescript
  app/containers/MessageBox/index.tsx
  app/definitions/ILoggedUser.ts
  app/definitions/IRocketChatRecord.ts
  app/definitions/IUpload.ts
  app/definitions/IUser.ts
  app/lib/methods/sendFileMessage.ts
  app/utils/fileUpload/index.ios.ts
  app/utils/fileUpload/interfaces.ts
  app/views/ShareView/index.tsx
Labels: 🚚 chore

#3667 [FIX] Differ to Last Session Authenticated
  app/lib/rocketchat/services/getServerTimeSync.ts
  app/utils/localAuthentication.ts
Labels: 🛠 fix

#3719 Chore: Migrate methods/loadNextMessages to typescript
  app/lib/methods/loadNextMessages.ts
Labels: 🚚 chore, 👀 needs review

#3734 Chore: Migrate methods/getFileUrlFromMessage to typescript
  app/lib/methods/helpers/getFileUrlFromMessage.ts
  app/views/MessagesView/index.tsx
Labels: 🚚 chore, 👀 needs review

#3712 Chore: Migrate sendMessage to TS
  app/definitions/ISubscription.ts
  app/definitions/IThread.ts
  app/lib/methods/sendMessage.ts
  app/lib/methods/updateMessages.ts
  app/utils/room.ts
  app/views/ShareView/index.tsx
Labels: 🚚 chore, 👀 needs review

#3706 Chore: Migrate methods/enterpriseModules to TS
  app/definitions/IServer.ts
  app/lib/methods/enterpriseModules.ts
  app/lib/utils.ts
  app/reducers/enterpriseModules.ts
Labels: 🚚 chore

#3773 Chore: Remove unused function getTeamInfo
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore, 👀 needs review

#3758 Chore: Migrate views/RoomListView to typescript
  app/commands.ts
  app/containers/List/ListItem.tsx
  app/definitions/ISubscription.ts
  app/lib/methods/getUsersPresence.ts
  app/stacks/types.ts
  app/utils/debounce.ts
  app/utils/events.ts
  app/utils/goRoom.ts
  app/views/RoomsListView/Header/Header.tsx
  app/views/RoomsListView/Header/index.tsx
  app/views/RoomsListView/ListHeader/index.tsx
  app/views/RoomsListView/ServerDropdown.tsx
  app/views/RoomsListView/index.tsx
  app/views/RoomsListView/styles.ts
Labels: 🚚 chore, 👀 needs review
