Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2022-01, with the labels that each got.

#3581 [FIX] Download video/quicktime in iOS
  app/views/AttachmentView.tsx
Labels: 🛠 fix

#3564 Chore: Migrate Model's folder to Typescript
  app/containers/message/Reply.tsx
  app/containers/message/Video.tsx
  app/definitions/IAttachment.ts
  app/definitions/ICustomEmoji.ts
  app/definitions/IFrequentlyUsedEmoji.ts
  app/definitions/ILoggedUser.ts
  app/definitions/IMessage.ts
  app/definitions/IPermission.ts
  app/definitions/IReaction.ts
  app/definitions/IRocketChatRecord.ts
  app/definitions/IRole.ts
  app/definitions/IRoom.ts
  app/definitions/IServedBy.ts
  app/definitions/IServer.ts
  app/definitions/IServerHistory.ts
  app/definitions/ISettings.ts
  app/definitions/ISlashCommand.ts
  app/definitions/ISubscription.ts
  app/definitions/IThread.ts
  app/definitions/IThreadMessage.ts
  app/definitions/IUpload.ts
  app/definitions/IUser.ts
  app/navigationTypes.ts
  app/stacks/MasterDetailStack/types.ts
  app/stacks/types.ts
  app/views/AutoTranslateView/index.tsx
  app/views/MessagesView/index.tsx
  app/views/NewServerView/ServerInput/Item.tsx
  app/views/NewServerView/ServerInput/index.tsx
  app/views/NewServerView/index.tsx
  app/views/SearchMessagesView/index.tsx
  app/views/ShareView/index.tsx
Labels: 🚧 wip, 🚚 chore

#3560 Chore: Update React Native Device Info to 8.4.8
  package.json
  yarn.lock
Labels: 🐛 bug

#3589 [FIX] Roles rendering on dark theme
  app/views/RoomInfoView/Direct.js
Labels: 🛠 fix

#3573 fix: add height verification to fix modal dimension
  app/stacks/MasterDetailStack/ModalContainer.tsx
Labels: 🐛 bug

#3555 Chore: Migrate DisplayPrefsView to Typescript
  app/constants/constantDisplayMode.js
  app/constants/constantDisplayMode.ts
  app/presentation/RoomItem/Actions.tsx
  app/presentation/RoomItem/IconOrAvatar.js
  app/presentation/RoomItem/RoomItem.tsx
  app/presentation/RoomItem/Wrapper.tsx
  app/reducers/sortPreferences.js
  app/views/DisplayPrefsView.tsx
  app/views/RoomsListView/index.js
  storybook/stories/RoomItem.js
Labels: 🚚 chore, 👀 needs review

#3538 Chore: Migrate ThreadMessagesView to Typescript
  app/definitions/IMention.ts
  app/definitions/IUrl.ts
  app/stacks/types.ts
  app/views/ThreadMessagesView/Dropdown/DropdownItem.tsx
  app/views/ThreadMessagesView/Dropdown/DropdownItemFilter.tsx
  app/views/ThreadMessagesView/Dropdown/DropdownItemHeader.tsx
  app/views/ThreadMessagesView/Dropdown/index.tsx
  app/views/ThreadMessagesView/Item.tsx
  app/views/ThreadMessagesView/filters.js
  app/views/ThreadMessagesView/filters.ts
  app/views/ThreadMessagesView/index.tsx
  app/views/ThreadMessagesView/styles.ts
Labels: 🚚 chore

#3576 [FIX] Message parser switch not updating field properly
  app/views/UserPreferencesView/index.tsx
Labels: 👀 needs review, 🛠 fix

#3587 Chore: Migrate notification/push to Typescript
  app/definitions/INotification.ts
  app/definitions/index.ts
  app/notifications/push/index.js
  app/notifications/push/index.ts
  app/notifications/push/push.android.js
  app/notifications/push/push.ios.js
  app/notifications/push/push.ios.ts
  app/notifications/push/push.ts
  package.json
  yarn.lock
Labels: 🚚 chore

#3579 [FIX] App crashes when entering server after applying certificate (Android)
  android/app/src/main/java/chat/rocket/reactnative/networking/SSLPinningModule.java
Labels: 🐛 bug, 👀 needs review

#3628 [FIX] makeThreadName asserting undefined as non-null
  app/utils/room.ts
Labels: 🛠 fix

#3631 [FIX] Threads' pagination not working
  app/views/ThreadMessagesView/index.tsx
Labels: 🛠 fix
