Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2022-05, with the labels that each got.

#4130 Chore: Evaluate DirectoryView - TypeScript
  app/containers/DirectoryItem/index.tsx
  app/definitions/IRoom.ts
  app/views/DirectoryView/index.tsx
Labels: 🚚 chore

#4126 Chore: Evaluate ForwardLivechatView - TypeScript
  app/stacks/InsideStack.tsx
  app/stacks/MasterDetailStack/index.tsx
  app/views/ForwardLivechatView.tsx
Labels: 🚚 chore

#4127 Chore: Evaluate DisplayPrefsView - TypeScript
  app/views/DisplayPrefsView.tsx
Labels: 🚚 chore

#4129 Chore: Evaluate DiscussionsView - TypeScript
  app/views/DiscussionsView/DiscussionDetails.tsx
  app/views/DiscussionsView/Item.stories.js
  app/views/DiscussionsView/Item.tsx
  app/views/DiscussionsView/index.tsx
Labels: 🚚 chore

#4119 Chore: Evaluate SelectListView - TypeScript
  app/definitions/IDataSelect.ts
  app/stacks/types.ts
  app/views/RoomActionsView/index.tsx
  app/views/SelectListView.tsx
Labels: 🚚 chore

#4121 Chore: Evaluate SelectedUsersView - TypeScript
  app/views/SelectedUsersView.tsx
Labels: 🚚 chore

#4123 Chore: Evaluate ReadReceiptView - TypeScript
  app/views/ReadReceiptView/index.tsx
Labels: 🚚 chore

#4145 Chore: Evaluate AutoTranslate- TypeScript
  app/views/AutoTranslateView/index.tsx
Labels: 🚚 chore, 👀 needs review

#4144 Chore: Evaluate Create Channel - TypeScript
  app/reducers/createChannel.ts
  app/views/CreateChannelView.tsx
Labels: 🚚 chore, 👀 needs review

#4099 Chore: Evaluate NotificationPreferencesView - Typescript
  app/definitions/IRoom.ts
  app/stacks/types.ts
  app/views/NotificationPreferencesView/index.tsx
Labels: 🚚 chore, 👀 needs review

#4133 Chore: Evaluate CreateDiscussionView - TypeScript
  app/actions/createDiscussion.ts
  app/definitions/ISearch.ts
  app/views/CreateDiscussionView/SelectChannel.tsx
  app/views/CreateDiscussionView/SelectUsers.tsx
  app/views/CreateDiscussionView/index.tsx
  app/views/CreateDiscussionView/interfaces.ts
Labels: 🚚 chore

#4134 Chore: Evaluate RoomView - TypeScript
  app/containers/ActionSheet/Provider.tsx
  app/containers/MessageActions/index.tsx
  app/containers/MessageBox/index.tsx
  app/containers/MessageErrorActions.tsx
  app/views/RoomView/JoinCode.tsx
  app/views/RoomView/List/List.tsx
  app/views/RoomView/List/index.tsx
  app/views/RoomView/index.tsx
Labels: 🚚 chore

#4148 Chore: Evaluate RoomActionsView - TypeScript
  app/definitions/IRoom.ts
  app/views/RoomActionsView/index.tsx
Labels: 🚚 chore

#4150 Chore: Evaluate CannedResponseDetail - TypeScript
  app/views/CannedResponseDetail.tsx
Labels: 🚚 chore

#4149 Chore: Evaluate CannedResponsesListView - TypeScript
  app/definitions/ICannedResponse.ts
  app/definitions/ILivechatDepartment.ts
  app/views/CannedResponsesListView/Dropdown/DropdownItemFilter.tsx
  app/views/CannedResponsesListView/Dropdown/DropdownItemHeader.tsx
  app/views/CannedResponsesListView/Dropdown/index.tsx
  app/views/CannedResponsesListView/index.tsx
Labels: 🚚 chore

#4116 Chore: Evaluate RoomMembersView - TypeScript
  app/containers/ActionSheet/Item.tsx
  app/containers/ActionSheet/Provider.tsx
  app/lib/methods/helpers.ts
  app/stacks/MasterDetailStack/types.ts
  app/views/LivechatEditView.tsx
  app/views/RoomInfoEditView/index.tsx
  app/views/RoomMembersView/index.tsx
Labels: 🚚 chore

#4117 Chore: Evaluate ShareListView - TypeScript
  app/definitions/navigationTypes.ts
  app/views/ShareListView/index.tsx
Labels: 🚚 chore

#4118 Chore: Evaluate SelectServerView - TypeScript
  app/views/SelectServerView.tsx
Labels: 🚚 chore

#4125 Chore: Evaluate LivechatEditView - TypeScript
  app/views/LivechatEditView.tsx
Labels: 🚚 chore

#4077 Chore: Evaluate WorkspaceView - TypeScript
  app/definitions/IAssetsFavicon512.ts
  app/reducers/settings.ts
  app/views/WorkspaceView/index.tsx
Labels: 🚚 chore

#4078 Chore: Evaluate UserPreferencesView - TypeScript
  app/views/UserPreferencesView/index.tsx
Labels: 🚚 chore

#4079 Chore: Evaluate UserNotificationPreferencesView - TypeScript
  app/views/UserNotificationPreferencesView/index.tsx
Labels: 🚚 chore

#4082 Chore: Evaluate SetUsernameView - TypeScript
  app/views/SetUsernameView.tsx
Labels: 🚚 chore

#4092 Chore: Evaluate SecurityPrivacyView - TypeScript
  app/views/SecurityPrivacyView.tsx
Labels: 🚚 chore

#4094 Chore: Evaluate ScreenLockConfigView - TypeScript
  app/views/ScreenLockConfigView.tsx
Labels: 🚚 chore

#4114 Chore: Evaluate RegisterView - TypeScript
  app/views/RegisterView.tsx
Labels: 🚚 chore

#4115 Chore: Evaluate NewMessageView - TypeScript
  app/stacks/types.ts
  app/views/NewMessageView.tsx
Labels: 🚚 chore

#4047 Chore: Unsupported system messages
  app/containers/message/index.tsx
  app/containers/message/interfaces.ts
  app/containers/message/utils.ts
  app/i18n/locales/en.json
  app/views/RoomView/index.tsx
Labels: 🚚 chore, 👀 needs review

#4096 Chore: evaluate `PickerView`
  app/views/PickerView.tsx
Labels: 🚚 chore, 👀 needs review

#4101 Chore: evaluate `NewServerView`
  app/views/NewServerView/index.tsx
Labels: 🚚 chore, 👀 needs review

#4098 Chore: evaluate `LoginView`
  app/views/LoginView.tsx
Labels: 🚚 chore, 👀 needs review

#4102 Chore: evaluate `AuthLoadingView`
  app/views/AuthLoadingView.tsx
Labels: 🚚 chore, 👀 needs review

#4106 Chore: evaluate `ForgotPasswordView`
  app/views/ForgotPasswordView.tsx
Labels: 🚚 chore, 👀 needs review

#4103 Chore: evaluate `JitsiMeetView`
  app/views/JitsiMeetView.tsx
Labels: 🚚 chore, 👀 needs review

#4065 [FIX] Messages showing URL preview on Room Actions
  app/views/MessagesView/index.tsx
  app/views/SearchMessagesView/index.tsx
Labels: 🛠 fix

#4086 Chore: evaluate `ThemeView`
  app/stacks/InsideStack.tsx
  app/stacks/MasterDetailStack/index.tsx
  app/theme.tsx
  app/views/ThemeView.tsx
Labels: 🚚 chore, 👀 needs review

#4069 Chore: Evaluate emoji picker - TypeScript
  app/actions/customEmojis.ts
  app/containers/EmojiPicker/CustomEmoji.tsx
  app/containers/EmojiPicker/EmojiCategory.tsx
  app/containers/EmojiPicker/TabBar.tsx
  app/containers/EmojiPicker/emojis.ts
  app/containers/EmojiPicker/index.tsx
  app/containers/MessageActions/Header.tsx
  app/containers/MessageBox/EmojiKeyboard.tsx
  app/containers/MessageBox/index.tsx
  app/containers/message/index.tsx
  app/definitions/ICustomEmoji.ts
  app/definitions/IEmoji.ts
  app/definitions/IFrequentlyUsedEmoji.ts
  app/definitions/index.ts
  app/lib/methods/getCustomEmojis.ts
  app/reducers/customEmojis.test.ts
  app/reducers/customEmojis.ts
  app/views/MessagesView/index.tsx
  app/views/RoomView/ReactionPicker.tsx
  app/views/RoomView/index.tsx
Labels: 🚚 chore, 👀 needs review

#4089 Chore: Evaluate SidebarView - Typescript
  app/stacks/InsideStack.tsx
  app/views/SettingsView/index.tsx
  app/views/SidebarView/index.tsx
Labels: 🚚 chore, 👀 needs review

#4091 Chore: Evaluate ProfileView - Typescript
  app/definitions/IProfile.ts
  app/definitions/IProfileViewInterfaces.ts
  app/definitions/index.ts
  app/definitions/rest/v1/users.ts
  app/lib/services/restApi.ts
  app/views/ProfileView/index.tsx
  app/views/RoomInfoEditView/index.tsx
Labels: 🚚 chore, 👀 needs review

#4084 Chore: Evaluate ThreadMessagesView - TypeScript
  app/views/ThreadMessagesView/Dropdown/DropdownItem.tsx
  app/views/ThreadMessagesView/Dropdown/index.tsx
  app/views/ThreadMessagesView/Item.tsx
  app/views/ThreadMessagesView/index.tsx
Labels: 🚚 chore, 👀 needs review

#4088 Chore: evaluate `TeamChannelsView`
  app/stacks/MasterDetailStack/types.ts
  app/stacks/types.ts
  app/views/RoomView/RightButtons.tsx
  app/views/TeamChannelsView.tsx
Labels: 🚚 chore, 👀 needs review

#4090 Chore: evaluate SettingsView
  app/utils/log/events.ts
  app/views/SettingsView/index.tsx
Labels: 🚚 chore, 👀 needs review

#4097 Chore: evaluate `LegalView`
  app/stacks/OutsideStack.tsx
  app/views/LegalView.tsx
Labels: 🚚 chore, 👀 needs review

#4095 Chore: evaluate `RoomInfoEditView`
  app/definitions/IRoom.ts
  app/views/RoomInfoEditView/index.tsx
Labels: 🚚 chore, 👀 needs review

#4113 Chore: Evaluate MessagesView - TypeScript
  app/definitions/IMessage.ts
  app/lib/services/restApi.ts
  app/views/MessagesView/index.tsx
Labels: 🚚 chore, 👀 needs review

#4056 [IMPROVE] Automatically release Experimental Android to Production on develop branch CI
  .circleci/config.yml
Labels: 👷 ci, 👀 needs review

#4162 Chore: Evaluate TypeScript and migrate to hooks AdminPanelView
  app/stacks/InsideStack.tsx
  app/stacks/MasterDetailStack/index.tsx
  app/views/AdminPanelView/index.tsx
Labels: 🚚 chore

#4158 Chore: Evaluate AuthenticationWebView - TypeScript
  app/definitions/ICredentials.ts
  app/views/AuthenticationWebView.tsx
Labels: 🚚 chore

#4169 Chore: Evaluate AddExistingChannelView - TypeScript
  app/views/AddExistingChannelView.tsx
Labels: 🚚 chore

#4087 Chore: Evaluate ShareView - TypeScript
  app/containers/MessageBox/index.tsx
  app/definitions/IAttachment.ts
  app/stacks/types.ts
  app/utils/media.ts
  app/views/ShareView/Header.tsx
  app/views/ShareView/Preview.tsx
  app/views/ShareView/Thumbs.tsx
  app/views/ShareView/index.tsx
  app/views/ShareView/interfaces.ts
Labels: 🚚 chore

#4107 Chore: Evaluate RoomInfoView - TypeScript
  app/definitions/ILivechatVisitor.ts
  app/views/RoomInfoView/CustomFields.tsx
  app/views/RoomInfoView/Direct.tsx
  app/views/RoomInfoView/index.tsx
Labels: 🚚 chore

#4104 Chore: evaluate `MarkdownTableView`
  app/stacks/InsideStack.tsx
  app/stacks/MasterDetailStack/index.tsx
  app/views/MarkdownTableView.tsx
Labels: 🚚 chore, 👀 needs review

#4100 Chore: evaluate `InviteUsersView`
  app/stacks/InsideStack.tsx
  app/stacks/MasterDetailStack/index.tsx
  app/views/InviteUsersView/index.tsx
Labels: 🚚 chore, 👀 needs review

#4177 [IMPROVE] Place time after username on message
  app/containers/message/Reply.tsx
  app/containers/message/User.tsx
  app/views/RoomView/LoadMore/__snapshots__/LoadMore.stories.storyshot
  app/views/RoomView/Separator.tsx
  ios/Podfile.lock
  storybook/stories/__snapshots__/Message.storyshot
Labels: 👍 improvement

#4196 Regression: Android Official lane on CI removed from develop branch
  .circleci/config.yml
Labels: 🐛 bug, 👷 ci

#4124 Chore: Evaluate ModalBlockView - TypeScript
  app/views/ModalBlockView.tsx
Labels: 🚚 chore

#4170 Chore: Evaluate TypeScript and migrate to hooks AddChannelTeamView
  app/views/AddChannelTeamView.tsx
Labels: 🚚 chore

#4181 Chore: Evaluate TextInput component
  app/containers/MessageBox/index.tsx
  app/containers/SearchBox.tsx
  app/containers/SearchHeader.tsx
  app/containers/TextInput/FormTextInput.tsx
  app/containers/TextInput/TextInput.stories.js
  app/containers/TextInput/__snapshots__/TextInput.stories.storyshot
  app/containers/TextInput/index.tsx
  app/containers/TwoFactor/index.tsx
  app/containers/UIKit/MultiSelect/index.tsx
  app/containers/UIKit/index.tsx
  app/views/CreateChannelView.tsx
  app/views/CreateDiscussionView/index.tsx
  app/views/E2EEncryptionSecurityView.tsx
  app/views/E2EEnterYourPasswordView.tsx
  app/views/ForgotPasswordView.tsx
  app/views/InviteUsersView/index.tsx
  app/views/LivechatEditView.tsx
  app/views/LoginView.tsx
  app/views/NewServerView/ServerInput/index.tsx
  app/views/ProfileView/index.tsx
  app/views/RegisterView.tsx
  app/views/RoomInfoEditView/index.tsx
  app/views/RoomView/JoinCode.tsx
  app/views/RoomsListView/Header/Header.tsx
  app/views/SearchMessagesView/index.tsx
  app/views/SendEmailConfirmationView.tsx
  app/views/SetUsernameView.tsx
  app/views/ShareListView/Header/Header.tsx
  app/views/ShareView/index.tsx
  app/views/StatusView/index.tsx
  storybook/stories/index.js
Labels: 🚚 chore, 👀 needs review

#4142 Chore: Evaluate e2e screens - TypeScript
  app/views/E2EEncryptionSecurityView.tsx
  app/views/E2EHowItWorksView.tsx
  app/views/E2ESaveYourPasswordView.tsx
Labels: 🚚 chore

#4172 Chore: Upgrade react-native-document-picker from 5.2.0 to 8.1.0
  app/containers/MessageBox/index.tsx
  app/utils/sslPinning.ts
  ios/Podfile.lock
  package.json
  yarn.lock
Labels: 🚚 chore, 👀 needs review

#4176 Chore: Update @react-native-slider from 3.0.3 to 4.2.2
  ios/Podfile.lock
  package.json
  storybook/stories/__snapshots__/Message.storyshot
  yarn.lock
Labels: 🚚 chore, 👀 needs review

#4206 Regression: "Join call" button not showing
  app/containers/message/index.tsx
Labels: 🛠 fix

#4122 Chore: Evaluate SearchMessagesView - TypeScript
  app/views/SearchMessagesView/index.tsx
Labels: 🚚 chore

#4203 Chore: update @rocket.chat/ui-kit to 0.31.11
  app/containers/UIKit/Actions.tsx
  app/containers/UIKit/Context.tsx
  app/containers/UIKit/DatePicker.tsx
  app/containers/UIKit/Image.tsx
  app/containers/UIKit/Input.tsx
  app/containers/UIKit/MultiSelect/index.tsx
  app/containers/UIKit/Section.tsx
  app/containers/UIKit/index.tsx
  app/containers/UIKit/interfaces.ts
  app/containers/UIKit/utils.ts
  app/externalModules.d.ts
  app/views/CreateDiscussionView/SelectUsers.tsx
  app/views/LivechatEditView.tsx
  app/views/RoomInfoEditView/index.tsx
  package.json
  yarn.lock
Labels: 🚚 chore

#4215 Chore: Update tests Detox for Beta 4.28.0
  app/containers/ActionSheet/BottomSheetContent.tsx
  app/containers/CustomIcon/index.tsx
  app/containers/message/Edited.tsx
  app/containers/message/Message.tsx
  e2e/helpers/app.js
  e2e/tests/onboarding/04-createuser.spec.js
  e2e/tests/onboarding/05-login.spec.js
  e2e/tests/onboarding/06-roomslist.spec.js
  e2e/tests/room/01-createroom.spec.js
  e2e/tests/room/02-room.spec.js
  e2e/tests/room/09-jumptomessage.spec.js
  e2e/tests/team/02-team.spec.js
  package.json
  storybook/stories/__snapshots__/Message.storyshot
  yarn.lock
Labels: 🚚 chore

#4222 [FIX] Navigate to MarkdownTableView using tablets
  app/containers/markdown/Table.tsx
  storybook/stories/Markdown.tsx
  storybook/stories/index.js
Labels: 🛠 fix

#4214 Regression: Fix problem to load starred, mentions, pinned and files messages
  app/views/MessagesView/index.tsx
Labels: 🐛 bug

#4224 Regression: right icons overlapping when users name is long
  app/containers/message/Components/RightIcons/Edited.tsx
  app/containers/message/Components/RightIcons/Encrypted.tsx
  app/containers/message/Components/RightIcons/MessageError.tsx
  app/containers/message/Components/RightIcons/ReadReceipt.tsx
  app/containers/message/Components/RightIcons/index.tsx
  app/containers/message/Content.tsx
  app/containers/message/Encrypted.tsx
  app/containers/message/Message.tsx
  app/containers/message/User.tsx
  app/containers/message/interfaces.ts
  app/containers/message/styles.ts
  app/views/RoomView/LoadMore/__snapshots__/LoadMore.stories.storyshot
  ios/Podfile.lock
  storybook/stories/Message.js
  storybook/stories/__snapshots__/Message.storyshot
Labels: 🐛 bug

#3961 [FIX] User status update
  app/views/SidebarView/index.tsx
  e2e/tests/assorted/06-status.spec.js
Labels: 👀 needs review, 🛠 fix
