Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2022-04, with the labels that each got.

#3926 Chore: Clean ReactionsModal - TypeScript
  app/containers/ReactionsModal.tsx
  app/stacks/types.ts
  app/views/MessagesView/index.tsx
  app/views/RoomView/index.tsx
Labels: 🚚 chore, 👀 needs review

#3997 Chore: upgrade Xcode version to 13.3.0 on CircleCI
  .circleci/config.yml
Labels: 🚚 chore, 👷 ci

#3944 Chore: Evaluate Message - TypeScript
  app/actions/messages.ts
  app/containers/markdown/interfaces.ts
  app/containers/message/Attachments.tsx
  app/containers/message/Audio.tsx
  app/containers/message/Blocks.ts
  app/containers/message/Broadcast.tsx
  app/containers/message/CallButton.tsx
  app/containers/message/Content.tsx
  app/containers/message/Discussion.tsx
  app/containers/message/Encrypted.tsx
  app/containers/message/Image.tsx
  app/containers/message/Message.tsx
  app/containers/message/MessageError.tsx
  app/containers/message/Reactions.tsx
  app/containers/message/ReadReceipt.tsx
  app/containers/message/RepliedThread.tsx
  app/containers/message/Reply.tsx
  app/containers/message/Thread.tsx
  app/containers/message/Urls.tsx
  app/containers/message/User.tsx
  app/containers/message/Video.tsx
  app/containers/message/index.tsx
  app/containers/message/interfaces.ts
  app/definitions/IAttachment.ts
  app/definitions/IMessage.ts
  app/definitions/IUrl.ts
  app/stacks/types.ts
  app/views/MessagesView/index.tsx
  app/views/RoomView/index.tsx
  app/views/SearchMessagesView/index.tsx
Labels: 🚚 chore, 👀 needs review

#4013 Chore: evaluate getUserSelector
  app/definitions/ILoggedUser.ts
  app/definitions/IProfileViewInterfaces.ts
  app/definitions/IUser.ts
  app/selectors/login.ts
  app/views/CreateChannelView.tsx
  app/views/E2EEncryptionSecurityView.tsx
  app/views/JitsiMeetView.tsx
  app/views/LanguageView/index.tsx
  app/views/ProfileView/index.tsx
  app/views/SelectedUsersView.tsx
  app/views/SettingsView/index.tsx
  app/views/SidebarView/index.tsx
  app/views/StatusView.tsx
  app/views/UserNotificationPreferencesView/index.tsx
Labels: 🚚 chore

#4015 Chore: evaluate ServerItem - TypeScript Migration
  app/containers/ServerItem/index.tsx
  app/containers/ServerItem/styles.ts
  app/definitions/IServer.ts
  app/presentation/ServerItem/index.tsx
  app/views/RoomsListView/ServerDropdown.tsx
  app/views/SelectServerView.tsx
  app/views/ShareListView/index.tsx
  storybook/stories/ServerItem.js
Labels: 🚚 chore, 👀 needs review

#4016 Chore: TypeScript Migration - evaluate DirectoryItem
  app/containers/DirectoryItem/index.tsx
  app/containers/DirectoryItem/styles.ts
  app/presentation/DirectoryItem/index.tsx
  app/views/DirectoryView/index.tsx
  app/views/ShareListView/index.tsx
Labels: 🚚 chore, 👀 needs review

#4031 [FIX] Queue Omnichannel rooms shouldn't show header buttons
  app/views/RoomView/index.tsx
Labels: 🚚 chore, 👀 needs review

#4026 Chore: Upgrade @types/react-native to 0.64.2
  app/containers/LoginServices.tsx
  app/containers/MessageBox/RecordAudio.tsx
  app/containers/MessageBox/buttons/BaseButton.tsx
  app/containers/message/Reply.tsx
  app/views/CannedResponsesListView/index.tsx
  app/views/DiscussionsView/index.tsx
  app/views/RoomInfoEditView/index.tsx
  app/views/ThreadMessagesView/index.tsx
  package.json
  storybook/stories/__snapshots__/Message.storyshot
  yarn.lock
Labels: 🚚 chore

#4003 [FIX] Create a discussion from NewMessageView
  app/containers/UIKit/MultiSelect/Items.tsx
  app/containers/UIKit/MultiSelect/index.tsx
  app/views/CreateDiscussionView/SelectChannel.tsx
  app/views/CreateDiscussionView/index.tsx
Labels: 🛠 fix

#4021 Chore: add eslint-plugin-react-hooks lib
  .eslintrc.js
  app/AppContainer.tsx
  app/containers/Avatar/Avatar.tsx
  app/containers/MessageBox/CommandsPreview/index.tsx
  app/containers/MessageBox/Mentions/index.tsx
  app/containers/MessageBox/ReplyPreview.tsx
  app/containers/UIKit/index.tsx
  app/containers/markdown/Preview.tsx
  app/containers/message/Attachments.tsx
  app/containers/message/Components/CollapsibleQuote/index.tsx
  app/containers/message/Content.tsx
  app/containers/message/Encrypted.tsx
  app/containers/message/Message.tsx
  app/containers/message/MessageError.tsx
  app/containers/message/RepliedThread.tsx
  app/containers/message/Reply.tsx
  app/containers/message/Thread.tsx
  app/containers/message/Urls.tsx
  app/containers/message/User.tsx
  app/containers/message/index.tsx
  app/ee/omnichannel/containers/OmnichannelStatus.tsx
  app/lib/methods/logout.ts
  app/lib/services/restApi.ts
  app/lib/services/sdk.ts
  app/sagas/inviteLinks.js
  app/utils/url.ts
  app/views/MessagesView/index.tsx
  app/views/RoomView/LeftButtons.tsx
  app/views/RoomView/index.tsx
  app/views/RoomsListView/ListHeader/index.tsx
  package.json
  yarn.lock
Labels: 🚚 chore, 👀 needs review

#4034 [FIX] Searching for users when creating discussions not returning data correctly
  app/views/CreateDiscussionView/SelectUsers.tsx
Labels: 🚚 chore, 👀 needs review, 🛠 fix

#3999 Chore: TypeScript migration - move `notifications/push` to `lib/notifications`
  app/index.tsx
  app/lib/methods/logout.ts
  app/lib/notifications/index.ts
  app/lib/notifications/push.ts
  app/lib/services/restApi.ts
  app/sagas/state.js
Labels: 🚚 chore, 👀 needs review

#4014 Chore: Evaluate KeyboardView - TypeScript
  app/containers/FormContainer.tsx
  app/containers/KeyboardView.tsx
  app/presentation/KeyboardView.tsx
  app/views/CreateChannelView.tsx
  app/views/CreateDiscussionView/index.tsx
  app/views/E2EEnterYourPasswordView.tsx
  app/views/LivechatEditView.tsx
  app/views/ProfileView/index.tsx
  app/views/RoomInfoEditView/index.tsx
  app/views/SetUsernameView.tsx
Labels: 🚚 chore

#4020 Chore: Migrate REST API - getSupportedLanguagesAutoTranslate to Typescript
  app/lib/services/restApi.ts
Labels: 🚚 chore

#4053 [FIX] Send upload inside a thread
  app/containers/MessageBox/index.tsx
Labels: 🛠 fix

#3988 Chore: Migrate i18n to Typescript
  app/containers/List/ListItem.tsx
  app/containers/MessageBox/buttons/BaseButton.tsx
  app/containers/MessageBox/index.tsx
  app/containers/Passcode/Base/index.tsx
  app/containers/Passcode/PasscodeChoose.tsx
  app/containers/markdown/index.tsx
  app/containers/message/utils.ts
  app/i18n/index.ts
  app/i18n/isRTL.ts
  app/views/NotificationPreferencesView/index.tsx
  app/views/RoomInfoView/Channel.tsx
  app/views/UserNotificationPreferencesView/index.tsx
  package.json
  tsconfig.json
  yarn.lock
Labels: 🚚 chore

#3959 [IMPROVE] Support Omnichannel icons
  android/app/build.gradle
  android/app/src/main/assets/fonts/custom.ttf
  app/containers/RoomHeader/RoomHeader.stories.js
  app/containers/RoomHeader/RoomHeader.tsx
  app/containers/RoomHeader/__snapshots__/RoomHeader.stories.storyshot
  app/containers/RoomHeader/index.tsx
  app/containers/RoomTypeIcon/OmnichannelRoomIcon.tsx
  app/containers/RoomTypeIcon/index.tsx
  app/definitions/IRoom.ts
  app/definitions/ISubscription.ts
  app/lib/database/model/Subscription.js
  app/lib/database/model/migrations.js
  app/lib/database/schema/app.js
  app/lib/methods/helpers/mergeSubscriptionsRooms.ts
  app/lib/selection.json
  app/presentation/RoomItem/IconOrAvatar.js
  app/presentation/RoomItem/RoomItem.tsx
  app/presentation/RoomItem/TypeIcon.tsx
  app/presentation/RoomItem/Wrapper.tsx
  app/presentation/RoomItem/index.tsx
  app/views/RoomActionsView/index.tsx
  app/views/RoomInfoView/index.tsx
  app/views/RoomView/index.tsx
  ios/Podfile.lock
  ios/RocketChatRN.xcodeproj/project.pbxproj
  ios/custom.ttf
  package.json
  storybook/stories/RoomItem.js
  storybook/stories/__snapshots__/RoomItem.storyshot
  yarn.lock
Labels: 🎉 feature

#4018 Chore: Evaluate UnreadBadge to Typescript
  app/containers/HeaderButton/HeaderButtonItemBadge.tsx
  app/containers/UnreadBadge/getUnreadStyle.test.js
  app/containers/UnreadBadge/getUnreadStyle.ts
  app/containers/UnreadBadge/index.tsx
  app/ee/omnichannel/containers/OmnichannelStatus.tsx
  app/presentation/RoomItem/RoomItem.tsx
  storybook/stories/UnreadBadge.js
Labels: 🚚 chore

#4039 [IMPROVE] Visibility of the “incoming chats” in queue
  app/containers/List/ListIcon.tsx
  app/containers/List/ListItem.tsx
  app/containers/UnreadBadge/index.tsx
  app/ee/omnichannel/containers/OmnichannelHeader/OmnichannelQueue.tsx
  app/ee/omnichannel/containers/OmnichannelHeader/index.tsx
  app/ee/omnichannel/containers/OmnichannelHeader/styles.ts
  app/ee/omnichannel/containers/OmnichannelStatus.tsx
  app/i18n/locales/ar.json
  app/i18n/locales/de.json
  app/i18n/locales/en.json
  app/i18n/locales/fr.json
  app/i18n/locales/it.json
  app/i18n/locales/nl.json
  app/i18n/locales/pt-BR.json
  app/i18n/locales/ru.json
  app/i18n/locales/tr.json
  app/i18n/locales/zh-CN.json
  app/i18n/locales/zh-TW.json
  app/views/RoomsListView/ListHeader/index.tsx
  app/views/RoomsListView/index.tsx
  app/views/RoomsListView/styles.ts
  storybook/stories/__snapshots__/List.storyshot
Labels: 🎉 feature

#4002 [IMPROVE] Accept user avatar url from external provider
  app/containers/Avatar/Avatar.tsx
  app/containers/Avatar/index.tsx
  app/containers/Avatar/interfaces.ts
  app/lib/constants/defaultSettings.ts
  app/utils/avatar.ts
Labels: 🎉 feature

#4051 [NEW] On-Hold chats for Omnichannel
  app/containers/message/index.tsx
  app/containers/message/interfaces.ts
  app/containers/message/utils.ts
  app/definitions/IMessage.ts
  app/definitions/IRoom.ts
  app/definitions/ISubscription.ts
  app/ee/omnichannel/lib/index.ts
  app/i18n/locales/ar.json
  app/i18n/locales/de.json
  app/i18n/locales/en.json
  app/i18n/locales/fr.json
  app/i18n/locales/it.json
  app/i18n/locales/nl.json
  app/i18n/locales/pt-BR.json
  app/i18n/locales/pt-PT.json
  app/i18n/locales/ru.json
  app/i18n/locales/tr.json
  app/i18n/locales/zh-CN.json
  app/i18n/locales/zh-TW.json
  app/lib/constants/defaultSettings.ts
  app/lib/database/model/Message.js
  app/lib/database/model/Subscription.js
  app/lib/database/model/migrations.js
  app/lib/database/schema/app.js
  app/lib/methods/subscriptions/rooms.ts
  app/lib/services/restApi.ts
  app/utils/log/events.ts
  app/views/RoomActionsView/index.tsx
  app/views/RoomView/index.tsx
  app/views/RoomsListView/index.tsx
Labels: 🎉 feature

#4042 [FIX] Avatar's size on display mode change
  app/containers/Avatar/index.tsx
  app/presentation/RoomItem/Actions.tsx
  app/presentation/RoomItem/RoomItem.tsx
  app/presentation/RoomItem/Wrapper.tsx
  app/presentation/RoomItem/index.tsx
  app/presentation/RoomItem/styles.ts
  storybook/stories/__snapshots__/RoomItem.storyshot
Labels: 👀 needs review, 🛠 fix

#4054 [CHORE] Change circleci to cimg
  .circleci/config.yml
Labels: 🚚 chore, 👷 ci

#4023 Chore: evaluate `RoomItem`
  app/containers/InAppNotification/NotifierComponent.tsx
  app/containers/RoomItem/Actions.tsx
  app/containers/RoomItem/IconOrAvatar.js
  app/containers/RoomItem/LastMessage.tsx
  app/containers/RoomItem/RoomItem.tsx
  app/containers/RoomItem/Tag.tsx
  app/containers/RoomItem/Title.tsx
  app/containers/RoomItem/Touchable.tsx
  app/containers/RoomItem/TypeIcon.tsx
  app/containers/RoomItem/UpdatedAt.tsx
  app/containers/RoomItem/Wrapper.tsx
  app/containers/RoomItem/index.tsx
  app/containers/RoomItem/interfaces.ts
  app/containers/RoomItem/styles.ts
  app/definitions/IMessage.ts
  app/ee/omnichannel/views/QueueListView.tsx
  app/views/RoomsListView/index.tsx
  app/views/TeamChannelsView.tsx
  storybook/stories/RoomItem.js
  storybook/stories/__snapshots__/RoomItem.storyshot
Labels: 🚚 chore, 👀 needs review

#4112 Regression: Users search on `CreateDiscussionView`
  app/views/CreateDiscussionView/SelectUsers.tsx
Labels: 👀 needs review, 🛠 fix
