Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2022-03, with the labels that each got.

#3801 Chore: Migrate REST API - markAsUnread to TS
  app/definitions/rest/v1/index.ts
  app/definitions/rest/v1/subscriptions.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore, 👀 needs review

#3792 Chore: Migrate REST API - convertChannelToTeam to TS
  app/definitions/rest/v1/channels.ts
  app/definitions/rest/v1/groups.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore, 👀 needs review

#3794 Chore: Migrate REST API - getRoutingConfig to Typescript
  app/lib/rocketchat/services/restApi.ts
  app/views/RoomActionsView/index.tsx
Labels: 🚚 chore

#3793 Chore: Migrate REST API - e2eGetUsersOfRoomWithoutKey to Typescript
  app/definitions/rest/v1/e2e.ts
  app/lib/encryption/room.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore

#3796 Chore: Migrate REST API - register to TS
  app/definitions/IUser.ts
  app/definitions/rest/v1/user.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore, 👀 needs review

#3788 Chore: Migrate REST API - createTeam to TS
  app/definitions/rest/v1/teams.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore, 👀 needs review

#3797 Chore: Migrate REST API - addRoomsToTeam to TS
  app/definitions/rest/v1/teams.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore, 👀 needs review

#3799 Chore: Migrate REST API - removeTeamMember to TS
  app/definitions/rest/v1/teams.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore, 👀 needs review

#3791 Chore: Migrate REST API - toggleArchiveRoom to Typescript
  app/definitions/rest/v1/channels.ts
  app/definitions/rest/v1/groups.ts
  app/lib/rocketchat/methods/roomTypeToApiType.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore

#3800 Chore: Migrate REST API - convertTeamToChannel to TS
  app/definitions/rest/v1/teams.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore, 👀 needs review

#3802 Chore: Migrate REST API - deleteMessage to TS
  app/definitions/rest/v1/chat.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore, 👀 needs review

#3781 Chore: Server API types - user.setPreferences
  app/definitions/IUser.ts
  app/definitions/rest/v1/user.ts
  app/lib/rocketchat/services/restApi.ts
  app/views/UserNotificationPreferencesView/index.tsx
Labels: 🚚 chore, 👀 needs review

#3774 Chore: Server API types - teams.updateRoom
  app/definitions/ITeam.ts
  app/definitions/rest/v1/teams.ts
  app/lib/methods/logout.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore, 👀 needs review

#3805 Chore: Migrate REST API - teamListRoomsOfUser to TS
  app/definitions/rest/v1/teams.ts
  app/lib/rocketchat/services/restApi.ts
  app/views/RoomActionsView/index.tsx
  app/views/RoomMembersView/index.tsx
Labels: 🚚 chore, 👀 needs review

#3808 Chore: Migrate REST API - toggleBlockUser to Typescript
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore

#3787 Chore: Migrate REST API - saveRoomSettings to Typescript
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore

#3812 Fix: fix the command to run detox on android
  package.json
Labels: 📝 docs, 👀 needs review

#3748 Chore: Migrate subscriptions/rooms to TS
  app/definitions/IDDPMessage.ts
  app/definitions/IRoom.ts
  app/lib/methods/helpers/buildMessage.ts
  app/lib/methods/helpers/mergeSubscriptionsRooms.ts
  app/lib/methods/subscriptions/rooms.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore, 👀 needs review

#3752 Chore: Migrate subscriptions/room to TS
  app/definitions/ISubscription.ts
  app/lib/methods/loadMissedMessages.ts
  app/lib/methods/subscriptions/room.ts
Labels: 🚚 chore, 👀 needs review

#3827 Chore: Migrate REST API - merge v1/user in v1/users
  app/definitions/rest/v1/index.ts
  app/definitions/rest/v1/user.ts
  app/definitions/rest/v1/users.ts
Labels: 🚚 chore, 👀 needs review

#3822 Chore: Migrate REST API - updateJitsiTimeout to Typescript
  app/definitions/rest/v1/index.ts
  app/definitions/rest/v1/videoConference.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore, 👀 needs review

#3824 Chore: Migrate REST API - toggleStarMessage to Typescript
  app/definitions/rest/v1/chat.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore, 👀 needs review

#3825 Chore: Migrate REST API - togglePinMessage to Typescript
  app/definitions/rest/v1/chat.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore, 👀 needs review

#3829 Chore: Migrate REST API - setReaction to Typescript
  app/definitions/rest/v1/chat.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore, 👀 needs review

#3826 Chore: Migrate REST API - reportMessage to Typescript
  app/definitions/rest/v1/chat.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore, 👀 needs review

#3850 Chore: Migrate REST API - ignoreUser to Typescript
  app/definitions/rest/v1/chat.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore, 👀 needs review

#3828 Chore: Migrate REST API - setUserStatus to Typescript
  app/definitions/IUser.ts
  app/definitions/rest/v1/users.ts
  app/lib/rocketchat/services/restApi.ts
  app/views/StatusView.tsx
Labels: 🚚 chore, 👀 needs review

#3821 Chore: Migrate REST API - spotlight to Typescript
  app/definitions/ISpotlight.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore

#3845 Chore: Migrate REST API - usersAutoComplete to Typescript
  app/views/ForwardLivechatView.tsx
Labels: 🚚 chore

#3847 Chore: Migrate REST API - toggleRoomOwner to Typescript
  app/definitions/rest/v1/channels.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore, 👀 needs review

#3848 Chore: Migrate REST API - toggleRoomLeader to Typescript
  app/definitions/rest/v1/channels.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore, 👀 needs review

#3843 Chore: Migrate REST API - returnLivechat to Typescript
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore

#3842 Chore: Migrate REST API - getRoomCounters to Typescript
  app/definitions/rest/v1/channels.ts
  app/definitions/rest/v1/groups.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore

#3831 [FIX] Condensed layout cutting text on smaller text sizes
  app/presentation/RoomItem/Wrapper.tsx
  app/presentation/RoomItem/styles.ts
  storybook/stories/__snapshots__/RoomItem.storyshot
Labels: 🛠 fix

#3809 [FIX] Hardcoded E2E password for Detox workflow
  .gitignore
  e2e/README.md
  e2e/data.js
  e2e/data/data.cloud.js
  e2e/e2e_account.example.js
Labels: 🛠 fix

#3743 Chore: Migrate normalizeMessage to TS
  app/definitions/IMessage.ts
  app/definitions/ISubscription.ts
  app/definitions/IThread.ts
  app/lib/database/services/Message.ts
  app/lib/methods/helpers/buildMessage.ts
  app/lib/methods/helpers/normalizeMessage.ts
  app/lib/methods/sendMessage.ts
  app/lib/methods/subscriptions/rooms.ts
Labels: 🚚 chore, 👀 needs review

#3776 Chore: Server API types - chat.getDiscussions
  app/definitions/IMessage.ts
  app/definitions/rest/v1/chat.ts
  app/views/DiscussionsView/DiscussionDetails.tsx
  app/views/DiscussionsView/Item.tsx
  app/views/DiscussionsView/index.tsx
Labels: 🚚 chore, 👀 needs review

#3840 Chore: Migrate REST API - getTeamListRoom to TS
  app/definitions/rest/v1/teams.ts
  app/lib/rocketchat/services/restApi.ts
  app/views/TeamChannelsView.tsx
Labels: 🚚 chore, 👀 needs review

#3759 Chore: Dehydrate login methods from rocketchat.js
  app/containers/LoginServices.tsx
  app/containers/MessageBox/index.tsx
  app/definitions/ICredentials.ts
  app/definitions/ILoggedUser.ts
  app/definitions/IRocketChat.ts
  app/definitions/index.ts
  app/lib/methods/logout.ts
  app/lib/rocketchat/rocketchat.js
  app/lib/rocketchat/services/connect.ts
Labels: 🚚 chore, 👀 needs review

#3865 Chore: Migrate REST API - saveNotificationSettings to Typescript
  app/definitions/IRoom.ts
  app/definitions/IUser.ts
  app/definitions/rest/v1/rooms.ts
  app/lib/rocketchat/services/restApi.ts
  app/views/NotificationPreferencesView/index.tsx
Labels: 🚚 chore, 👀 needs review

#3634 Chore: Update react-native-mmkv-storage to 0.6.12
  __tests__/Storyshots.test.js
  android/app/src/main/java/chat/rocket/reactnative/MainApplication.java
  android/app/src/play/java/chat/rocket/reactnative/Ejson.java
  app/containers/Passcode/PasscodeEnter.tsx
  app/index.tsx
  app/lib/encryption/encryption.ts
  app/lib/methods/logout.ts
  app/lib/rocketchat/rocketchat.js
  app/lib/userPreferences.ts
  app/sagas/deepLinking.js
  app/sagas/encryption.js
  app/sagas/init.js
  app/sagas/login.js
  app/sagas/selectServer.js
  app/share.tsx
  app/utils/localAuthentication.ts
  app/utils/openLink.ts
  app/utils/sslPinning.ts
  app/utils/theme.ts
  app/views/DefaultBrowserView.tsx
  app/views/DisplayPrefsView.tsx
  app/views/E2ESaveYourPasswordView.tsx
  app/views/NewServerView/index.tsx
  app/views/RoomsListView/ServerDropdown.tsx
  app/views/RoomsListView/index.tsx
  app/views/ScreenLockConfigView.tsx
  app/views/ThemeView.tsx
  ios/Podfile.lock
  ios/Shared/RocketChat/Storage.swift
  package.json
  patches/react-native-mmkv-storage+0.3.5.patch
  patches/react-native-mmkv-storage+0.6.12.patch
  patches/react-native-webview+10.3.2.patch
  patches/rn-fetch-blob+0.12.0.patch
  yarn.lock
Labels: 🚚 chore

#3830 Chore: Migrate REST API - getUserPreferences to Typescript
  app/definitions/rest/v1/users.ts
  app/lib/rocketchat/services/restApi.ts
  app/views/UserNotificationPreferencesView/index.tsx
Labels: 🚚 chore, 👀 needs review

#3869 Chore: Migrate REST API - getAvatarSuggestion to Typescript
  app/definitions/IProfileViewInterfaces.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore

#3870 Chore: Migrate REST API - resetAvatar to Typescript
  app/definitions/rest/v1/users.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore

#3871 Chore: Migrate REST API - setAvatarFromService to Typescript
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore

#3872 Chore: Migrate REST API - getUsernameSuggestion to Typescript
  app/definitions/rest/v1/users.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore

#3874 Chore: Migrate REST API - searchMessages to Typescript
  app/definitions/IMessage.ts
  app/definitions/rest/v1/chat.ts
  app/lib/rocketchat/services/restApi.ts
  app/views/SearchMessagesView/index.tsx
Labels: 🚚 chore, 👀 needs review

#3873 Chore: Migrate REST API - getFiles to Typescript
  app/definitions/IAttachment.ts
  app/definitions/rest/v1/channels.ts
  app/definitions/rest/v1/groups.ts
  app/definitions/rest/v1/im.ts
  app/lib/rocketchat/services/restApi.ts
  app/views/MessagesView/index.tsx
Labels: 🚚 chore, 👀 needs review

#3878 Chore: Migrate REST API - editLivechat to Typescript
  app/definitions/ILivechatEditView.ts
  app/lib/rocketchat/services/restApi.ts
  app/views/LivechatEditView.tsx
Labels: 🚚 chore

#3887 Chore: Migrate REST API - editMessage to Typescript
  app/definitions/rest/v1/chat.ts
  app/lib/rocketchat/rocketchat.js
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore

#3888 Chore: Migrate REST API - e2eResetOwnKey to Typescript
  app/definitions/IRocketChat.ts
  app/lib/rocketchat/rocketchat.js
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore

#3886 Chore: Migrate REST API - emitTyping to Typescript
  app/lib/rocketchat/rocketchat.js
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore

#3868 Chore: Migrate REST API - getRoomRoles to Typescript and fix getRoomMembers
  app/definitions/IRole.ts
  app/definitions/rest/v1/channels.ts
  app/definitions/rest/v1/groups.ts
  app/lib/rocketchat/rocketchat.js
  app/lib/rocketchat/services/restApi.ts
  app/views/RoomMembersView/index.tsx
Labels: 🚚 chore, 🛠 fix

#3884 Chore: Migrate REST API - addUsersToRoom to Typescript
  app/definitions/rest/v1/channels.ts
  app/definitions/rest/v1/groups.ts
  app/lib/rocketchat/rocketchat.js
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore

#3885 Chore: Migrate REST API - createGroupChat to Typescript
  app/lib/rocketchat/rocketchat.js
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore

#3894 Chore: Migrate REST API - getCommandPreview to Typescript
  app/containers/MessageBox/index.tsx
  app/definitions/rest/v1/commands.ts
  app/definitions/rest/v1/index.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore, 👀 needs review

#3897 Chore: Migrate REST API - executeCommandPreview to Typescript
  app/containers/MessageBox/CommandsPreview/index.tsx
  app/containers/MessageBox/index.tsx
  app/definitions/ISlashCommand.ts
  app/definitions/rest/v1/commands.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore

#3898 Chore: Migrate REST API - getDirectory to Typescript
  app/definitions/rest/v1/directory.ts
  app/definitions/rest/v1/index.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore

#3900 Chore: Migrate REST API - getServerInfo to Typescript
  app/lib/rocketchat/services/connect.ts
  app/lib/utils.ts
Labels: 🚚 chore

#3823 Chore: Migrate REST API - getRoomInfo to Typescript
  app/views/DirectoryView/index.tsx
  app/views/TeamChannelsView.tsx
Labels: 🚚 chore

#3891 Chore: Migrate REST API - sendEmailCode to Typescript
  app/lib/rocketchat/rocketchat.js
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore, 👀 needs review

#3892 Chore: Migrate REST API - saveAutoTranslate to Typescript
  app/lib/rocketchat/services/restApi.ts
  app/views/AutoTranslateView/index.tsx
Labels: 🚚 chore, 👀 needs review

#3893 Chore: Migrate REST API - runSlashCommand to Typescript
  app/containers/MessageBox/index.tsx
  app/definitions/rest/v1/commands.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore, 👀 needs review

#3896 Chore: Migrate REST API - getSyncThreadsList to Typescript
  app/definitions/rest/v1/chat.ts
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore, 👀 needs review

#3899 Chore: Migrate REST API - getRoomMembers to Typescript
  app/definitions/rest/v1/channels.ts
  app/definitions/rest/v1/groups.ts
  app/definitions/rest/v1/im.ts
  app/lib/rocketchat/rocketchat.js
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore, 👀 needs review

#3903 Chore: Migrate REST API - removePushToken to Typescript
  app/lib/rocketchat/rocketchat.js
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore

#3753 Chore: Dehydrate share extension from rocketchat.js
  app/containers/Avatar/index.tsx
  app/definitions/ICredentials.ts
  app/lib/database/index.ts
  app/lib/rocketchat/rocketchat.js
  app/lib/rocketchat/services/sdk.ts
  app/lib/rocketchat/services/shareExtension.ts
  app/reducers/share.ts
  app/share.tsx
  app/views/SelectServerView.tsx
Labels: 🚚 chore, 👀 needs review

#3895 Chore: Migrate REST API - getThreadsList to Typescript
  app/definitions/rest/v1/chat.ts
  app/lib/rocketchat/services/restApi.ts
  app/views/ThreadMessagesView/index.tsx
Labels: 🚚 chore, 👀 needs review

#3918 Chore: evaluate Header components - TypeScript
  app/containers/Header/index.tsx
  app/containers/List/ListHeader.tsx
  app/containers/List/ListInfo.tsx
  app/views/RoomsListView/Header/Header.tsx
  app/views/RoomsListView/Header/index.tsx
  app/views/RoomsListView/ListHeader/index.tsx
  app/views/RoomsListView/index.tsx
Labels: 🚚 chore, 👀 needs review

#3917 Chore: Evaluate BackgroundContainer - TypeScript
  app/containers/BackgroundContainer/index.tsx
Labels: 🚚 chore, 👀 needs review

#3914 Chore: Evaluate ActivityIndicator - TypeScript
  app/containers/ActivityIndicator.tsx
  app/containers/MessageBox/CommandsPreview/Item.tsx
  app/containers/TextInput.tsx
  app/containers/UIKit/Overflow.tsx
  app/containers/message/Audio.tsx
  app/containers/message/Reply.tsx
  app/containers/message/Video.tsx
  app/views/AttachmentView.tsx
  app/views/AuthenticationWebView.tsx
  app/views/CannedResponsesListView/index.tsx
  app/views/DirectoryView/index.tsx
  app/views/DiscussionsView/index.tsx
  app/views/JitsiMeetView.tsx
  app/views/MessagesView/index.tsx
  app/views/ModalBlockView.tsx
  app/views/RoomMembersView/index.tsx
  app/views/RoomView/List/index.tsx
  app/views/RoomsListView/index.tsx
  app/views/SearchMessagesView/index.tsx
  app/views/ShareListView/index.tsx
  app/views/TeamChannelsView.tsx
  app/views/ThreadMessagesView/index.tsx
  app/views/UserNotificationPreferencesView/index.tsx
Labels: 🚚 chore, 👀 needs review

#3915 Chore: Migrate containers: Loading to Typescript
  app/containers/Loading.tsx
Labels: 🚚 chore

#3942 Chore: Migrate REST API - e2eFetchMyKeys to Typescript
  app/definitions/rest/v1/e2e.ts
  app/lib/rocketchat/rocketchat.js
  app/lib/rocketchat/services/restApi.ts
Labels: 🚚 chore

#3943 [FIX] Wrong param sent to system message
  app/containers/message/utils.ts
  storybook/stories/__snapshots__/Message.storyshot
Labels: 🛠 fix

#3883 [NEW] Redesign quoted messages
  app/constants/colors.ts
  app/containers/markdown/Table.tsx
  app/containers/markdown/TableCell.tsx
  app/containers/markdown/TableRow.tsx
  app/containers/markdown/index.tsx
  app/containers/markdown/styles.ts
  app/containers/message/Attachments.tsx
  app/containers/message/Audio.tsx
  app/containers/message/Image.tsx
  app/containers/message/Message.tsx
  app/containers/message/Reply.tsx
  app/containers/message/User.tsx
  app/containers/message/Video.tsx
  app/containers/message/interfaces.ts
  app/containers/message/styles.ts
  app/definitions/IAttachment.ts
  app/lib/utils.ts
  app/views/RoomView/LoadMore/__snapshots__/LoadMore.stories.storyshot
  storybook/stories/Message.js
  storybook/stories/__snapshots__/Message.storyshot
Labels: 🎉 feature, 👀 needs review

#3912 Chore: Clean TwoFactor - Typescript
  app/containers/TwoFactor/index.tsx
  app/views/RoomView/JoinCode.tsx
Labels: 🚚 chore, 👀 needs review

#3919 Chore: Clean Check - TypeScript
  app/containers/Check.tsx
  app/containers/UIKit/MultiSelect/Items.tsx
  app/presentation/ServerItem/index.tsx
  app/views/DirectoryView/Options.tsx
  storybook/stories/ServerItem.js
  storybook/stories/__snapshots__/ServerItem.storyshot
Labels: 🚚 chore, 👀 needs review

#3920 Chore: Clean InAppNotification - TypeScript
  app/containers/InAppNotification/NotifierComponent.tsx
  app/containers/InAppNotification/index.tsx
Labels: 🚚 chore, 👀 needs review

#3935 Chore: Clean LoginServices - TypeScript
  app/containers/LoginServices.tsx
  app/definitions/ICredentials.ts
  app/selectors/login.ts
  app/stacks/types.ts
  app/views/LoginView.tsx
  app/views/RegisterView.tsx
Labels: 🚚 chore, 👀 needs review

#3931 Chore: Evaluate Passcode - TypeScript
  app/containers/Passcode/Base/Button.tsx
  app/containers/Passcode/Base/Dots.tsx
  app/containers/Passcode/Base/LockIcon.tsx
  app/containers/Passcode/Base/Locked.tsx
  app/containers/Passcode/Base/Subtitle.tsx
  app/containers/Passcode/Base/Title.tsx
  app/containers/Passcode/Base/index.tsx
  app/containers/Passcode/PasscodeChoose.tsx
  app/containers/Passcode/PasscodeEnter.tsx
  app/containers/Passcode/constants.ts
  app/containers/Passcode/utils.ts
  app/views/ChangePasscodeView.tsx
  app/views/ScreenLockedView.tsx
Labels: 🚚 chore

#3947 [FIX] "Sent an attachment" text on media preview for threads
  app/containers/message/Content.tsx
  storybook/stories/__snapshots__/Message.storyshot
Labels: 👀 needs review, 🛠 fix

#3945 [FIX] Audio thumb's size
  app/containers/message/Audio.tsx
  storybook/stories/__snapshots__/Message.storyshot
Labels: 👀 needs review, 🛠 fix

#3954 Chore: Update codecov version
  package.json
  yarn.lock
Labels: 🚚 chore, 👀 needs review

#3925 Chore: Evaluate HeaderButton - TypeScript
  app/containers/HeaderButton/Common.tsx
  app/containers/HeaderButton/HeaderButtonContainer.tsx
  app/containers/HeaderButton/HeaderButtonItem.tsx
  app/containers/HeaderButton/HeaderButtonItemBadge.tsx
  storybook/stories/__snapshots__/HeaderButtons.storyshot
Labels: 🚚 chore, 👀 needs review

#3953 [FIX] Navigate to team from directory
  app/views/DirectoryView/index.tsx
Labels: 👀 needs review, 🛠 fix

#3962 [FIX] Param privacy when editing room info
  app/views/RoomInfoEditView/index.tsx
Labels: 🛠 fix

#3963 [FIX] Drawer failing to open/close on ProfileView
  app/containers/HeaderButton/Common.tsx
  storybook/stories/__snapshots__/HeaderButtons.storyshot
Labels: 🛠 fix

#3948 Chore: Evaluate Markdown - TypeScript
  app/containers/markdown/AtMention.tsx
  app/containers/markdown/BlockQuote.tsx
  app/containers/markdown/Hashtag.tsx
  app/containers/markdown/Link.tsx
  app/containers/markdown/List.tsx
  app/containers/markdown/ListItem.tsx
  app/containers/markdown/Preview.tsx
  app/containers/markdown/Table.tsx
  app/containers/markdown/TableCell.tsx
  app/containers/markdown/TableRow.tsx
  app/containers/markdown/interfaces.ts
  app/containers/markdown/new/BigEmoji.tsx
  app/containers/markdown/new/Bold.tsx
  app/containers/markdown/new/Code.tsx
  app/containers/markdown/new/CodeLine.tsx
  app/containers/markdown/new/Emoji.tsx
  app/containers/markdown/new/Heading.tsx
  app/containers/markdown/new/Image.tsx
  app/containers/markdown/new/Inline.tsx
  app/containers/markdown/new/InlineCode.tsx
  app/containers/markdown/new/Italic.tsx
  app/containers/markdown/new/Link.tsx
  app/containers/markdown/new/OrderedList.tsx
  app/containers/markdown/new/Paragraph.tsx
  app/containers/markdown/new/Plain.tsx
  app/containers/markdown/new/Quote.tsx
  app/containers/markdown/new/Strike.tsx
  app/containers/markdown/new/TaskList.tsx
  app/containers/markdown/new/UnorderedList.tsx
  app/containers/markdown/new/index.tsx
Labels: 🚚 chore

#3922 Chore: Migrate containers: FormContainer to Typescript
  app/containers/FormContainer.tsx
  app/views/ForgotPasswordView.tsx
  app/views/LoginView.tsx
  app/views/NewServerView/index.tsx
  app/views/RegisterView.tsx
  app/views/SendEmailConfirmationView.tsx
  app/views/WorkspaceView/index.tsx
Labels: 🚚 chore

#3921 Chore: Migrate containers: List to Typescript
  app/containers/List/ListContainer.tsx
  app/containers/List/ListHeader.tsx
  app/containers/List/ListIcon.tsx
  app/containers/List/ListItem.tsx
  app/containers/List/ListSection.tsx
  app/containers/List/ListSeparator.tsx
  app/dimensions.tsx
  app/lib/rocketchat/services/restApi.ts
  app/views/AddChannelTeamView.tsx
  app/views/ScreenLockConfigView.tsx
  app/views/ThemeView.tsx
  storybook/stories/__snapshots__/List.storyshot
Labels: 🚚 chore

#3960 [FIX] User status missing translate
  app/views/StatusView.tsx
Labels: 👀 needs review, 🛠 fix

#3939 Chore: Evaluate UiKit - TypeScript
  app/containers/ReactionsModal.tsx
  app/containers/SearchBox.tsx
  app/containers/UIKit/Actions.tsx
  app/containers/UIKit/DatePicker.tsx
  app/containers/UIKit/Image.tsx
  app/containers/UIKit/MultiSelect/Chips.tsx
  app/containers/UIKit/MultiSelect/Input.tsx
  app/containers/UIKit/MultiSelect/Items.tsx
  app/containers/UIKit/MultiSelect/index.tsx
  app/containers/UIKit/Overflow.tsx
  app/containers/UIKit/Section.tsx
  app/containers/UIKit/Select.tsx
  app/containers/UIKit/index.tsx
  app/containers/UIKit/interfaces.ts
  app/containers/UIKit/utils.ts
  app/containers/message/Attachments.tsx
  app/containers/message/Image.tsx
  app/definitions/IAttachment.ts
  app/externalModules.d.ts
  app/views/AttachmentView.tsx
  app/views/CreateDiscussionView/SelectChannel.tsx
  app/views/CreateDiscussionView/SelectUsers.tsx
  app/views/LivechatEditView.tsx
  app/views/RoomInfoEditView/index.tsx
Labels: 🚚 chore

#3985 [FIX] Animation to show all login services options
  app/containers/LoginServices.tsx
Labels: 🐛 bug, 👀 needs review

#3989 [FIX] `AttachedActions`'s button
  app/containers/message/Attachments.tsx
  storybook/stories/__snapshots__/Message.storyshot
Labels: 👀 needs review, 🛠 fix

#3952 [FIX] Omnichannel's "Availability" toggle button is hard to interact with on Android devices
  app/ee/omnichannel/containers/OmnichannelStatus.tsx
Labels: 🛠 fix
