Repository RocketChat/Rocket.Chat.ReactNative, pull requests merged in 2022-08, with the labels that each got.

#4366 [IMPROVE] Add emoji picker to iOS
  app/containers/EmojiPicker/EmojiCategory.tsx
  app/containers/EmojiPicker/index.tsx
  app/containers/MessageBox/EmojiKeyboard.tsx
  app/containers/MessageBox/LeftButtons.ios.tsx
  app/containers/MessageBox/LeftButtons.tsx
  app/containers/MessageBox/RecordAudio.tsx
  app/containers/MessageBox/RightButtons.ios.tsx
  app/containers/MessageBox/RightButtons.tsx
  app/containers/MessageBox/constants.ts
  app/containers/MessageBox/index.tsx
  app/containers/message/index.tsx
  app/views/RoomView/ReactionPicker.tsx
  app/views/RoomView/RightButtons.tsx
  app/views/RoomView/index.tsx
  package.json
  yarn.lock
Labels: 👍 improvement

#4427 Regression: Room header not showing room type when not joined
  app/views/RoomView/index.tsx
Labels: 🛠 fix

#4393 [FIX] Text composer is pushing modals outside the screen on Android's tablet
  app/stacks/MasterDetailStack/ModalContainer.tsx
Labels: 🛠 fix

#4445 Chore: Hooks app/views/SelectServerView
  app/share.tsx
  app/views/SelectServerView.tsx
Labels: 🚚 chore

#4417 Chore: Hooks App/share
  app/share.tsx
Labels: 🚚 chore

#4424 Chore: Hooks app/views/DefaultBrowserView
  app/stacks/InsideStack.tsx
  app/stacks/MasterDetailStack/index.tsx
  app/views/DefaultBrowserView.tsx
  app/views/DefaultBrowserView/Item.tsx
  app/views/DefaultBrowserView/index.tsx
Labels: 🚚 chore

#4446 [FIX] Pagination when search by members and fix the duplicated members in a Room's member's list
  app/lib/services/restApi.ts
  app/views/RoomMembersView/index.tsx
Labels: 🛠 fix

#4435 [IMPROVE] Remove show message in main thread preference
  app/containers/MessageActions/index.tsx
  app/containers/MessageBox/index.tsx
  app/definitions/ILoggedUser.ts
  app/i18n/locales/en.json
  app/i18n/locales/pt-BR.json
  app/lib/methods/subscriptions/rooms.ts
  app/lib/services/connect.ts
  app/views/RoomView/index.tsx
  app/views/UserPreferencesView/ListPicker.tsx
  app/views/UserPreferencesView/index.tsx
  e2e/helpers/data_setup.js
Labels: 👍 improvement

#4399 [NEW] Unify members section
  app/containers/RadioButton/index.tsx
  app/containers/UserItem.tsx
  app/i18n/locales/en.json
  app/i18n/locales/pt-BR.json
  app/lib/methods/helpers/helpers.ts
  app/lib/methods/helpers/log/events.ts
  app/lib/navigation/appNavigation.ts
  app/stacks/InsideStack.tsx
  app/stacks/MasterDetailStack/index.tsx
  app/stacks/MasterDetailStack/types.ts
  app/stacks/types.ts
  app/views/CreateChannelView.tsx
  app/views/NewMessageView.tsx
  app/views/RoomActionsView/index.tsx
  app/views/RoomMembersView/components/ActionsSection.tsx
  app/views/RoomMembersView/helpers.ts
  app/views/RoomMembersView/index.tsx
  app/views/RoomMembersView/styles.ts
  app/views/SelectedUsersView.tsx
  e2e/tests/room/03-roomactions.spec.js
  e2e/tests/team/02-team.spec.js
Labels: android-build, ios-build

#4381 [IMPROVE] Redesign flow of create room
  .storybook/storybook.requires.js
  __tests__/containers/Chip/__snapshots__/Chip.stories.storyshot
  __tests__/views/CreateChannelView/RoomSettings/__snapshots__/SwitchItem.stories.storyshot
  app/containers/Chip/Chip.stories.tsx
  app/containers/Chip/Chip.test.tsx
  app/containers/Chip/index.tsx
  app/containers/TextInput/ControlledFormTextInput.tsx
  app/containers/TextInput/index.ts
  app/containers/UserItem.tsx
  app/i18n/locales/ar.json
  app/i18n/locales/de.json
  app/i18n/locales/en.json
  app/i18n/locales/es-ES.json
  app/i18n/locales/fr.json
  app/i18n/locales/it.json
  app/i18n/locales/ja.json
  app/i18n/locales/nl.json
  app/i18n/locales/pt-BR.json
  app/i18n/locales/pt-PT.json
  app/i18n/locales/ru.json
  app/i18n/locales/tr.json
  app/i18n/locales/zh-CN.json
  app/i18n/locales/zh-TW.json
  app/stacks/InsideStack.tsx
  app/stacks/MasterDetailStack/index.tsx
  app/views/CreateChannelView.tsx
  app/views/CreateChannelView/RoomSettings/SwitchItem.stories.tsx
  app/views/CreateChannelView/RoomSettings/SwitchItem.test.tsx
  app/views/CreateChannelView/RoomSettings/SwitchItem.tsx
  app/views/CreateChannelView/RoomSettings/SwitchItemEncrypted.test.tsx
  app/views/CreateChannelView/RoomSettings/SwitchItemEncrypted.tsx
  app/views/CreateChannelView/RoomSettings/SwitchItemReadOnly.tsx
  app/views/CreateChannelView/RoomSettings/SwitchItemType.tsx
  app/views/CreateChannelView/RoomSettings/index.tsx
  app/views/CreateChannelView/index.tsx
  app/views/NewMessageView.tsx
  app/views/NewMessageView/ButtonCreate.tsx
  app/views/NewMessageView/HeaderNewMessage.tsx
  app/views/NewMessageView/index.tsx
  app/views/RoomInfoEditView/index.tsx
  app/views/RoomInfoView/Channel.tsx
  app/views/RoomMembersView/helpers.ts
  app/views/SelectedUsersView.tsx
  app/views/SelectedUsersView/Header.tsx
  app/views/SelectedUsersView/index.tsx
  e2e/helpers/app.js
  e2e/tests/assorted/02-broadcast.spec.js
  e2e/tests/assorted/03-profile.spec.js
  e2e/tests/room/04-discussion.spec.js
  e2e/tests/room/06-createdmgroup.spec.js
  e2e/tests/room/08-roominfo.spec.js
  e2e/tests/team/01-createteam.spec.js
  package.json
  yarn.lock
Labels: 👍 improvement

#4476 Regression: Jump to message from search view
  app/containers/message/index.tsx
Labels: 🛠 fix
